### ISSUE TITLE
[Suggestion] Sub claims

### ISSUE THREAD

**Issue by samuelh2005** [thexaero/open-parties-and-claims#102]
Sub claims are claims within claims. This would be made by the owner of the main claim.
These sub claims **should be measured in blocks** (not chunks). This would allow for vertical sub claims (good for apartments). 

These sub claims should be able to be 'put up for sale' which would allow a controllable set of players to claim these. Once claimed, the sub claim owner can control what happens inside (like a normal claim). 
However the main claim owner are still able to override what occurs. 
The sub claim count should not add up with the normal claim count, because these sub claims are all ready part of a real claim. 

Sub claims would allow the main claim owner to give control of some areas to people (e.g. rooms in an apartment building), but still keep the rest of the real claim restricted.
This would be similar to how players can buy chunks of a town with the Towny plugin. Instead of chunks these **should be measured in blocks**. 
A similar system to World Edit would allow these sub claims to be selected and sized in blocks. By having something like the World Edit poly selection this would allow for triangular or any shaped sub claims.

**Comment by thexaero** [comment]
I literally just added sub-claims today. 
Vertical claims or block-based claims do not become "possible" with the introduction of sub-claims. I will never add them to this mod. The existence of sub-claims alone already brings up the claim sync time when joining the server. 
The whole point of this mod is to have claims that are viewable on a 2D map on the client side. If you want 3D claims, there are other mods that do that. Their claims cannot be viewed on a map and do not scale well on big servers over time and it's not a coincidence. It might be technically possible but nobody has 10 years to work on that.

**Comment by thexaero** [comment]
And the whole selling claims thing is not going to be built into this mod. That is a very niche feature that can and should be a mod of its own. I am planning to improve the API for such purposes.

**Comment by samuelh2005** [comment]
Thanks!

**Comment by thexaero** [comment]
Thanks for understanding!
