### ISSUE TITLE
[request] [semi-related] Upload Mini/World Map releases to Modrinth

### ISSUE THREAD

**Issue by Merith-TK** [thexaero/open-parties-and-claims#107]
So you have OPAC on Modrinth, Yay!

But I have an vanilla+ Client modpack that I cant upload anywhere because an select few mods are stuck on curseforge!  (pack uses packwiz)

Now an good chunk of them have alternatives on modrinth, but your Mini/World maps have proven to be some of the better minimap mods I have seen in an while, (personally really dont like journey map, too many config options for so little customization and an dated UI), 

Would you be willing to upload releases of the mods to Modrinth? 

(the mods in question)
![image](https://user-images.githubusercontent.com/10422110/193478571-eefdb5a4-7e65-46c8-8b1b-9d4636768fc7.png)

**Comment by thexaero** [comment]
Thanks for the suggestion
