### ISSUE TITLE
Full crash after pressing the "Menu" keybind

### ISSUE THREAD

**Issue by mathgeniuszach** [thexaero/open-parties-and-claims#108]
## Crash Report
https://mclo.gs/W71d5mP

## Information
OS: Linux (Elementary OS, Arch)
Modloader: Quilt 0.17.4
Minecraft Version: 1.18.2

Important Mod Versions:
Open Parties and Claims: b0.14.1
Xaero's Minimap: 22.15.1
Xaero's World Map: 1.28.0
Not Enough Crashes: 4.1.6

I have a large collection of other mods, which I can provide on request.

## Overview
Stacktrace
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "args[0]" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2 build.4)
	at xaero.pac.client.gui.MainMenu.lambda$static$17(MainMenu.java:118)
	at xaero.pac.client.gui.component.CachedComponentSupplier.get(CachedComponentSupplier.java:38)
	at xaero.pac.client.gui.MainMenu.drawClaimsInfo(MainMenu.java:298)
	at xaero.pac.client.gui.MainMenu.render(MainMenu.java:322)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	...
```

Relavant files:

[CachedComponentSupplier.java](https://github.com/thexaero/open-parties-and-claims/blob/1.18.2/Common/src/main/java/xaero/pac/client/gui/component/CachedComponentSupplier.java)
[MainMenu.java](https://github.com/thexaero/open-parties-and-claims/blob/1.18.2/Common/src/main/java/xaero/pac/client/gui/MainMenu.java)

**Comment by thexaero** [comment]
Thanks for reporting!
Is claim sync disabled in the server config? Or did you open the menu as soon as you logged in? Can you get it to happen again?

**Comment by mathgeniuszach** [comment]
This full crash consistently happens after I join the official PolyMC Minecraft server (the modpack I'm using is a modified version of [HexMC](https://modrinth.com/modpack/hexmc) on modrinth) and _then_ press the key after I'm fully loaded in; this problem does not occur in Singleplayer.

I'm unsure if that server has claim sync disabled in the server config, but I have asked the server owner. I should have a response soon.

**Comment by thexaero** [comment]
Oh. I bet they simply have an outdated version of OPAC. The modpack you linked has 0.13.0 and you have 0.14.1. These are not compatible.

**Comment by mathgeniuszach** [comment]
Oh! Alright. I'll downgrade for now then. Thank you! I guess I didn't check the commit history on those files thoroughly enough.
