### ISSUE TITLE
Tags for Claim Permissions

### ISSUE THREAD

**Issue by im-hyps** [thexaero/open-parties-and-claims#109]
Using tags in order to whitelist certain blocks & entities for claim permissions would make configuring for servers and modpacks far easier and compact.

Currently, only vanilla buttons are able to be used in claims with 'Block Interactions' as true.

Creating a tag, openpac:claim_usable, for example, would mean it is more intuitive for modpack creators to be able to properly configure the mod rather than having to manually write down ~400 different varieties of doors as I've just had to do.

**Comment by thexaero** [comment]
Thanks for the suggestion!
A bit confused. Why would I create a tag like _openpac:claim_usable_ instead of adding existing tag support to the current options? The 400 doors would not be in the tag automatically.

**Comment by im-hyps** [comment]
Adding existing tag support would also work!

**Comment by thexaero** [comment]
Alright, great! I added another issue for that #113 and closing this one.
