### ISSUE TITLE
Armor stands XD.  b0.14.1 for Forge 1.18.2

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#115]
https://youtu.be/Gyp-wKyvPGo

I also broke it

![image](https://user-images.githubusercontent.com/86433158/194373003-7be7efcf-6506-4837-b17b-07f827ec7bd7.png)

**Comment by thexaero** [comment]
Is their "entity against players" protection even turned on? There should be no conflicts on Forge.

**Comment by thexaero** [comment]
Have you checked it?

**Comment by DonorKrovi** [comment]
> Owner

For some reason, I have the same

**Comment by DonorKrovi** [comment]
Can you clarify what should be included for protection?

**Comment by thexaero** [comment]
Alright, I see. This actually is broken in a non-dev environment. I'll see what I can do.
