### ISSUE TITLE
can't break blocks in chunk group

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#117]
I'm using your latest version for 1.18.2, like I've disabled group protection but still can't break blocks in the player's chunk.  Maybe I did something wrong?

https://youtu.be/UZziIYzh6U4

**Comment by thexaero** [comment]
You've disabled your own protection, not the claim owner's if I understand you correctly. Each player has their own player config.
You also changed it in the default config, which means new players will have it disabled by default. 

To enforce it to all players, you need to change the "player configurable options" list in the server config file, while the server isn't running.
