### ISSUE TITLE
More fine grained claim protection exclusions

### ISSUE THREAD

**Issue by Krimsar** [thexaero/open-parties-and-claims#118]
It would be helpful to be able to select what is allowed and what isn't directly from the claim gui and specific to a claim / subclaim config. 

For example, if I have a tree farm on a server, I want to allow for players to be breaking logs (which I wouldn't want to allow if they were part of a build). Having those options configured in the config-tomls (/reload doesn't seem to pick up changes to those files btw) and applying to all config/subconfigs that have the "allow some xyz" enabled is too restrictive. 

Sorry if I'm missing something obvious here, but the documentation is rather sparse ;)

**Comment by thexaero** [comment]
Custom groups instead of all or nothing "allow some" are planned: https://github.com/thexaero/open-parties-and-claims/issues/27
