### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by SqdGoodlol** [thexaero/open-parties-and-claims#120]
![image](https://user-images.githubusercontent.com/86075284/195021416-1814cbd4-7d5d-498d-9160-2c2d58ce0982.png)

**Comment by thexaero** [comment]
This is not related to any of my mods.

**Comment by SqdGoodlol** [comment]
![image](https://user-images.githubusercontent.com/86075284/195026517-b8cfed5f-d948-4a69-af53-d6c4518ea4a2.png)

**Comment by SqdGoodlol** [comment]
![image](https://user-images.githubusercontent.com/86075284/195026693-f7f828a3-0301-4664-8ca6-cbbac7501e65.png)

**Comment by SqdGoodlol** [comment]
> This is not related to any of my mods.

![image](https://user-images.githubusercontent.com/86075284/195027742-3a8991d2-c23d-4dc2-8f4a-d96ac50fe068.png)
