### ISSUE TITLE
Where to find permission for players for groups

### ISSUE THREAD

**Issue by SqdGoodlol** [thexaero/open-parties-and-claims#121]
![image](https://user-images.githubusercontent.com/86075284/195028497-15b907f8-3eb4-432e-9a12-89f83b55c014.png)
![image](https://user-images.githubusercontent.com/86075284/195028540-dc6e8e65-904f-4d57-978b-eb1f607ff317.png)

**Comment by thexaero** [comment]
This is not related to any of my mods. You have another mod that handles command permissions. It affects ALL commands. Nothing to do with me.
