### ISSUE TITLE
Bypass chunk with broken protection

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#122]
As far as I understood in the fashion there is protection from teleporter fruits of chorus, in fact it is included in me but other players can still use it

**Comment by XionioXMaster** [comment]
Other than that, I can't break the reservation rack, but I can take things off of it.
![image](https://user-images.githubusercontent.com/86433158/195436423-3a16f71b-089c-4ea5-bf87-4ddd747f82a9.png)
![image](https://user-images.githubusercontent.com/86433158/195436445-dd62cfd0-fb8f-45e2-8c73-59a533a29231.png)

**Comment by XionioXMaster** [comment]
![image](https://user-images.githubusercontent.com/86433158/195436795-fb2718e6-a89b-4c8e-8be0-d67994b47f0c.png)
Opening doors creates visual bugs

**Comment by thexaero** [comment]
Armor stands are fixed. Door bug isn't critical and will be fixed later. Create a separate issue for the chorus fruit teleportation and please give more info.

**Comment by XionioXMaster** [comment]
> Armor stands are fixed. Door bug isn't critical and will be fixed later. Create a separate issue for the chorus fruit teleportation and please give more info.

As for the armor stand, I was able to take things off it on the latest version, but couldn't break it.

**Comment by thexaero** [comment]
I don't think you used the latest version.

**Comment by thexaero** [comment]
And if you did, then you probably added armor stands to an exception list or something while trying to fix it earlier.

**Comment by XionioXMaster** [comment]
> Owner

[Archive WinRAR ZIP.zip](https://github.com/thexaero/open-parties-and-claims/files/9777555/Archive.WinRAR.ZIP.zip)
My config

![image](https://user-images.githubusercontent.com/86433158/195621670-a307487a-0db8-4c21-ba31-7ca4ccfd9bdf.png)
Version

I demolished all my modifications and used the clean version **b0.15.1**

**Comment by thexaero** [comment]
Is it the same version on the server side as well? Please test again. I was able to reproduce the issue on my end, fixed it, and now it's fixed for me. I have tested it again just now.

**Comment by XionioXMaster** [comment]
> Это та же версия на стороне сервера? Пожалуйста, протестируйте еще раз. Я смог воспроизвести проблему с моей стороны, исправил ее, и теперь она исправлена для меня. Я проверил его снова только сейчас.

![image](https://user-images.githubusercontent.com/86433158/195665016-1e226324-cd92-4504-bd6d-d53ed4cdb53a.png)
I will try to demolish the server config with players this Saturday to be sure if some other mod interferes
