### ISSUE TITLE
Chorus fruit protect doesn't work

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#123]
I have the use of chorus fruit disabled but players can use it, the protection does not seem to work

Version: [b0.15.1 for Forge 1.18.2](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims/files/4021873)
Forge: 1.18.2 - 40.1.80

**Comment by thexaero** [comment]
How do you expect it to work? What it does is prevent players from teleporting into claims protected from it, not disable it completely.

**Comment by XionioXMaster** [comment]
> 



> How do you expect it to work? What it does is prevent players from teleporting into claims protected from it, not disable it completely.

Maybe I didn't understand correctly how protection works but... I could use the chorus in the chunk or outside the chunk to teleport to the player's chunk so I could ignore the walls and teleport to the player's base.

I fixed this by adding a usage check in the config

**Comment by thexaero** [comment]
This protection uses a built-in Forge event, so it is very unlikely to be broken by a mod conflict. It works for me. Did you actually teleport to a chunk that has the chorus protection enabled?

**Comment by XionioXMaster** [comment]
Thanks
