### ISSUE TITLE
Add a shop plot system and an option to increase chunks

### ISSUE THREAD

**Issue by RFKreborn** [thexaero/open-parties-and-claims#136]
I love this mod so far! It's been desperately needed, so thank you for working on it!

Two suggestions for the mod.

1) A shop plot system where players can rent chunks with in-game items or economy currency.

2) Parties gain a set increment of claim chunks when other players join the party. Ex. 2 players = 20 chunks, 3 players = 30 chunks.

Thank you for considering these suggestions and keep up the amazing work!

**Comment by thexaero** [comment]
Thanks!
A shop system is not going to  be built into this. I am planning some API changes to make it possible for an addon.
Incrementing claim limit for parties makes no sense because parties don't have a claim limit. Each player has their own limit, so it effectively already does this.
