### ISSUE TITLE
Add LuckPerms support

### ISSUE THREAD

**Issue by thexaero** [thexaero/open-parties-and-claims#139]

**Comment by XionioXMaster** [comment]
Mmmm, it would be nice to give players chunks private through LP, as well as it is practical

**Comment by samuelh2005** [comment]
Maybe just add support for the [Fabric Permissions Api](https://github.com/lucko/fabric-permissions-api). Luck Perms uses it and many other mods to.

**Comment by thexaero** [comment]
@ajh123 Alright, I'll look into it.

**Comment by ryleu** [comment]
using luckperms for all of your permission stuff would bring this mod from being a nightmare to work with to being the best of its kind

**Comment by thexaero** [comment]
@ryleu Now that's a backhanded compliment if I've ever seen one.

**Comment by samuelh2005** [comment]
> @ryleu Now that's a backhanded compliment if I've ever seen one.

Lol

**Comment by ryleu** [comment]
I'm just trolling, I really like your mod, it just can be a bit... difficult to work with.

**Comment by Sewdohe** [comment]
I support adding luckPerms support as well. Just ditched all FTB mods for luck perms and openparties and can't restrict who can claim

**Comment by Sewdohe** [comment]
Okay, I successfully made a smaller mod luckPerms compatible a few days ago and I'm going to try to put together a PR for this mod to work with luckPerms as I need it badly

**Comment by Sewdohe** [comment]
@thexaero are you currently accepting PR's?

**Comment by thexaero** [comment]
@Sewdohe No, sorry.

**Comment by Dr-WeiAL** [comment]
Is it supported now?

**Comment by samuelh2005** [comment]
Thanks Xaero!
@Dr-WeiAL It looks like it is now!

**Comment by thexaero** [comment]
@ajh123 You're welcome! Going to release it in a moment.

**Comment by Dr-WeiAL** [comment]
Is there an example of increasing max claims? I don't quite understand

**Comment by thexaero** [comment]
@Dr-WeiAL Integer values are stored as "meta", not as permissions, in LuckPerms. The default node used by the mod for this is "xaero.pac_max_claims" which you can change in the server config file.
