### ISSUE TITLE
issues with Integrated Dynamics

### ISSUE THREAD

**Issue by Polarite** [thexaero/open-parties-and-claims#140]
Claim doesnt allow to use world block importer, as in this basic system should work, but doesnt in claim
![image](https://user-images.githubusercontent.com/34978332/197347722-eb87e82a-2ebc-469e-9ac0-6a6a2fca39c9.png)

**Comment by thexaero** [comment]
It's just the block being protected from being broken. Try turning off mob griefing protection for the claim, if the server has that option configured to be accessible. 
I probably should rename the option though.

**Comment by Polarite** [comment]
is there a way to only enable this fake player named [IntegratedTunnels]

**Comment by Polarite** [comment]
also I am the owner of the server yet I cant modify my claim options, how can I enable them

**Comment by thexaero** [comment]
If it's a fake player, then I'm afraid you can't fix this through the configs. I'd have to manually add support for this mod.
You can change what options are player-configurable in the main server config file while the server isn't running.

**Comment by Polarite** [comment]
then it would be great if you could add compatibility for that mod, its pretty popular as well

**Comment by thexaero** [comment]
Please let me know if anything else from that mod doesn't work.

**Comment by Polarite** [comment]
redstone emitters etc also doesnt work.

**Comment by glektarssza** [comment]
Pretty sure, if I recall correctly, the player simulator also doesn't work without completely disabling chunk protection. Probably the same root cause given the nature of the interaction.

**Comment by Polarite** [comment]
any idea when that would be fixed, I am having some issues because of that.

**Comment by thexaero** [comment]
Not sure, but I think I'll have something for it in the next update.
