### ISSUE TITLE
[Forge][1.18.2-0.5.0] Compatibility crash with Computercraft

### ISSUE THREAD

**Issue by kombarus** [thexaero/open-parties-and-claims#15]
I wasn't really sure if I should report the bug / incompatibility here or on the computercraft mod but I will try it here first.
As soon as a Turtle from [Computercraft](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked) tries to break and or place blocks in claimed chunks, the server crashes instantly.

Crash logs:
[crash-2022-07-10_16.04.32-server.txt](https://github.com/thexaero/open-parties-and-claims/files/9085236/crash-2022-07-10_16.04.32-server.txt)
[crash-2022-07-09_11.47.35-server.txt](https://github.com/thexaero/open-parties-and-claims/files/9085316/crash-2022-07-09_11.47.35-server.txt)

If more information is needed, let me know.

PS: I know we're running version 0.5.0 and you released 0.5.1, thou I didn't saw any patch notes for CC for 0.5.1 and I update the modpack in a bulk every week since I need to send it to my Alpha testers every time I change the modpack.

**Comment by thexaero** [comment]
Thanks! You reported it in the right place. 
Going to be fixed soon.
