### ISSUE TITLE
[1.19] Way to bypass claims as OPs

### ISSUE THREAD

**Issue by jinkhya** [thexaero/open-parties-and-claims#150]
Hello, I hope I didn't miss the info somewhere but could you add a command for OPs to bypass claims, and if possible with its own permission node so it could be given through ranks mods. 
Thanks in advance ! 
Jin

**Comment by jinkhya** [comment]
I'm an idiot, after looking for like 10 minutes I actually found the command, sorry about that lol
If anybody comes across this thread, the command is /openpac-claims admin-mode

**Comment by thexaero** [comment]
Glad you found it. I am planning to add a permission for it too.
