### ISSUE TITLE
[SUGGESTION] Allow using specific blocks regaurdless of claim

### ISSUE THREAD

**Issue by Camawama** [thexaero/open-parties-and-claims#157]
Certain blocks like the one from the SIMPLE SHOP mod cannot be used in someone else's claim.

**Comment by thexaero** [comment]
You can already configure that.

**Comment by Camawama** [comment]
My apologies. I couldn't figure it out so I assumed it wasn't a thing.

**Comment by Nvvlife** [comment]
How can you configure that?
