### ISSUE TITLE
[Forge][1.18.2-0.5.0] Clientcrash if "Claimed Area Name" is set

### ISSUE THREAD

**Issue by kombarus** [thexaero/open-parties-and-claims#16]
Heyhey, me again with another bug:
When you set the `Claimed Area Name` to anything, everyone, who enters the chunk with a set name, will crash.

![crash-report](https://user-images.githubusercontent.com/5245087/178371337-7943ec6e-4725-46e2-8d52-cb23a93aa358.png)

This is a running Console log when this happened:
[server-log.txt](https://github.com/thexaero/open-parties-and-claims/files/9087980/server-log.txt)

This is a client log of the person who crashed the first time:
[crashed-client-latest.log](https://github.com/thexaero/open-parties-and-claims/files/9087985/crashed-client-latest.log)

If any more information are needed, please tell me.

**Comment by thexaero** [comment]
Thanks for reporting.
It's already fixed in the latest version though.
