### ISSUE TITLE
land claims permission problems`

### ISSUE THREAD

**Issue by AqualisaH4U** [thexaero/open-parties-and-claims#161]
A friend of mine and I are on a modded minecraft and he created a claim on some land but i can't use anything on it and he can't work out how to change it so I can.
![image](https://user-images.githubusercontent.com/118817556/203312214-f2773d91-2abf-4974-89a3-316a2105197c.png)

**Comment by thexaero** [comment]
You can disable protection from your party/allies on your player config screen.

**Comment by thexaero** [comment]
Oh, and, in case that's the issue, creating a party works through chat commands under `/openpac-parties`

**Comment by AqualisaH4U** [comment]
we did that, does the server need to be restarted for it to work?? or can it be ok with it just open

**Comment by thexaero** [comment]
You don't have to restart the server for the player configs. What exactly did you do? Did the person who made the claim turn off "Protect From My Party" or "Protect From Ally Parties", depending on which party you are in?

**Comment by AqualisaH4U** [comment]
he created the party and invited me to it and then turned off to protect from my party.

**Comment by thexaero** [comment]
Did you accept the invite?

**Comment by AqualisaH4U** [comment]
he has got it working, thank you for the help
