### ISSUE TITLE
[1.19.2] Failed to join the server with this mod installed

### ISSUE THREAD

**Issue by jellybean13** [thexaero/open-parties-and-claims#167]
Minecraft version: 1.19.2
Mod loader: Forge
Forge version: 43.1.57
Mod version: 0.16.2
Server type: Dedicated server
Descriptions: The client fails to join the server if this mod is installed on both the client side and the server side. However, this issue won't occur if the client side doesn't install this mod.
Client logs: https://pastebin.com/a8i731Xu

**Comment by thexaero** [comment]
Your game fires the mob griefing event on the client side, which isn't something I thought was even a possibility. Probably related to the mob griefing mod you have. I'll check it out.
