### ISSUE TITLE
admin doesnt seem to do anything. 

### ISSUE THREAD

**Issue by frikinjay** [thexaero/open-parties-and-claims#168]
On the latest version for 1.18.2 of open parties and claims I am using it alongside FTB ranks, and admin-mode command says that i am in admin mode but it still cant interact with anyone else's claims as if admin mode is off.

**Comment by thexaero** [comment]
Can you provide screenshots?

**Comment by frikinjay** [comment]
Nvm, it was a mod messing with op perms. Thank you for the response.

**Comment by thexaero** [comment]
Did it say that you were in admin mode though? That part doesn't seem like another mod doing something.

**Comment by frikinjay** [comment]
It did say I was in admin mode despite op perms being 1 instead of 4.

**Comment by thexaero** [comment]
You think you can set your perms back to 1 and get a screenshot of what it says?
