### ISSUE TITLE
[Crash] Singleplayer crashes when generating chunks

### ISSUE THREAD

**Issue by moninformateur** [thexaero/open-parties-and-claims#171]
[Here is the log](https://mclo.gs/eBU80wz), everything points to OPC being the culprit. This happens when generating chunks using the mod "Chunk pregenerator" mod.

**Comment by thexaero** [comment]
Nothing points at this mod in the crash report. It's listed in the core mods for the involved classes but that has nothing to do with what's crashing.
Does it crash without OPAC installed?

**Comment by moninformateur** [comment]
All clues point to it having an impact on the crash. It is the only mod I saw mentionned in the crash log, but I'm not expert.

This crash does not happen with the mod disabled.

**Comment by thexaero** [comment]
Please test with the mod enabled again.

**Comment by thexaero** [comment]
And no, no real clues point at the mod. Stuff like this does not mean that the mod has anything to do with the crash:
```
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:905) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
```
It's simply listed in the core mods of the MinecraftServer class.
In fact, that's not even the real stack trace of the exception. The real one is this, which gives us nothing:
```
java.lang.ArrayIndexOutOfBoundsException: null
```
You'll have to add the `-XX:-OmitStackTraceInFastThrow` to your JVM arguments to disable the stack trace omission and get the full thing.

**Comment by moninformateur** [comment]
I've tried a few more times after re-enabling OPC and the crash seems to be gone. Sorry to have bothered, it doesn't seem to be linked.

**Comment by thexaero** [comment]
Thanks for the info!
