### ISSUE TITLE
Configurable interaction with smokers

### ISSUE THREAD

**Issue by snatella** [thexaero/open-parties-and-claims#172]
Hey, would it be possible to add an option to allow party etc access to smokers in the claimed area? Or even have it use the setting for the furnaces?

Thanks for all your mod work by the way, they're awesome.

**Comment by thexaero** [comment]
You can add your own exception block groups or modify existing ones in the main config file. Search for "Furnaces" and read the comment for the option, which explains all you need to know. Stop the server before you make changes to the config though.
