### ISSUE TITLE
Twilight Forest Hydra Fight Causing Crash

### ISSUE THREAD

**Issue by Tyre4770** [thexaero/open-parties-and-claims#173]
Hello! I'm currently running Better MC 1.19.2 on my personal server, and the TwiFo staff said that the crash is happening due to openpac. Info can be found on my post [here](https://github.com/TeamTwilight/twilightforest/issues/1700).

**Comment by thexaero** [comment]
Thanks for reporting!
It's the same as https://github.com/thexaero/open-parties-and-claims/issues/167 so I'm closing this one.
