### ISSUE TITLE
Description: Ticking entity

### ISSUE THREAD

**Issue by OmikronOverload** [thexaero/open-parties-and-claims#174]
Sup developer :)

So i got this very specific problem.
We play BetterMc v10.5 on our Server.
When an Ender Golem from Cataclysm hits the ground, onMobGriefEvent makes the game crash somehow.

Here is the crash log
[crash-2022-12-02_00.24.21-client.txt](https://github.com/thexaero/open-parties-and-claims/files/10137099/crash-2022-12-02_00.24.21-client.txt)

**Comment by OmikronOverload** [comment]
This is a Real bummer, no Idea how to fix this

**Comment by thexaero** [comment]
Thanks for reporting!
Same as #167 though. Haven't released the fix yet.

**Comment by OmikronOverload** [comment]
is there a way to make opac Ignore MobGriefing as a temporary fix? ;)

**Comment by thexaero** [comment]
I just released the fix. No, there wasn't. The option for mob griefing was checked after the crash.

**Comment by OmikronOverload** [comment]
Thank you so much for your effort :)

**Comment by thexaero** [comment]
@OmikronOverload Turns out I introduced a new bug where only OPs can join the servers. So you'll have to wait a bit more, sorry. I'll try to fix it as quickly as I can.
