### ISSUE TITLE
Ticking Entity Crash on Multiplayer

### ISSUE THREAD

**Issue by ShowTeKPT** [thexaero/open-parties-and-claims#176]
Hello, when interacting with bosses from L´Ender Cataclysm my client crashes with Ticking Entity Error.
It doesn't happen on Singleplayer.

Without this mod it doesn't crash.

[crash-2022-12-11_18.42.29-client.txt](https://github.com/thexaero/open-parties-and-claims/files/10203159/crash-2022-12-11_18.42.29-client.txt)

**Comment by thexaero** [comment]
It's already fixed. You need to update the mod.
