### ISSUE TITLE
/openpac-create invalid argument

### ISSUE THREAD

**Issue by ghost** [thexaero/open-parties-and-claims#177]
not possible to create a party. by typing a command i get a error Incorrect argument for command.
Seems to be a client error.

[latest.log](https://github.com/thexaero/open-parties-and-claims/files/10214623/latest.log)

**Comment by thexaero** [comment]
You're not supposed to type "Test" after the command.

**Comment by ghost** [comment]
thank you ^^

**Comment by thexaero** [comment]
No problem!
