### ISSUE TITLE
Dynmap support

### ISSUE THREAD

**Issue by samuelh2005** [thexaero/open-parties-and-claims#179]
Could we have support to show regions on [Dynmap](https://github.com/webbukkit/dynmap)?

Can it be like how its done on your (Xaero) map mod?
If you need an example on how to use their APIs try looking at the [Minecraft Transit Railway](https://github.com/jonafanho/Minecraft-Transit-Railway) mod, they use Dynmap in a few places even for Forge and Fabric!

**Comment by thexaero** [comment]
That's not something to ask me about. I do not use or develop anything for Dynmap, or have interest in starting. It doesn't have to be me. I have plenty to do in my own map mods.
