### ISSUE TITLE
BUG REPORT: After death and respawn in Nether, cannot claim in Overworld

### ISSUE THREAD

**Issue by juicebin** [thexaero/open-parties-and-claims#18]
**OPAC version**: 0.5.3
**Forge version**: 40.1.60

**Log**: [latest.log](https://github.com/thexaero/open-parties-and-claims/files/9095570/latest.log)

See the below comment for updated details. I kept the old description just in case.

This is a modpack! I can provide the modlist if needed, just let me know.

~~**Description**:~~
~~I'm attempting to claim chunks, and they say they're claimed, but fail to show up on the World Map. I'm also unable to claim things that are within my range, and it says that it is not within my range (assuming the range is the blue cube around me).~~

~~I eventually quit the game and rejoined, and tried to claim the same chunks that didn't work previously. It worked now, and I can see them. So, that means when I previously attempted and it said I claimed them, it never did.~~

~~**How to reproduce**:~~

~~The only thing I did prior to this was:~~
- ~~Go into the Nether~~
- ~~Do some redstone testing and die with the respawn anchor~~
- ~~Come back through the portal~~
- ~~Break some blocks~~
- ~~Attempt to claim area~~

~~There is one server claim in my range. No other claims other than the ones I'm attempting for now.~~

~~It may have an issue to do with the Nether, likely not anything with the redstone or respawn anchor. I didn't see anything in my log file that was out of the ordinary. 🤷~~

~~This could also have been a one-time thing. I'll try and reproduce it a couple more times.~~

**Comment by juicebin** [comment]
I have done a bit more testing! Here is the updated version of this bug:

**Description**:
If you die and respawn in the Nether using a respawn anchor, then go to the Overworld, the chunks you attempt to claim in the Overworld will not claim there and instead claim in the Nether. It's as if you'll be looking at the Overworld map but interacting with the Nether map.

**Steps to reproduce**:
1. Create a Nether portal
2. Enter the Nether
3. Place a respawn anchor
4. Fill it up and set spawn
5. Die!
6. Respawn and go back through the portal
7. Claim chunks in the Overworld. These shouldn't claim
8. Go through the Nether portal
9. The chunks should be claimed in the Nether

**Comment by thexaero** [comment]
Thanks for reporting!
That is very weird. I'll investigate soon.

**Comment by thexaero** [comment]
Does not happen to me, but I think I see how this would be possible.

**Comment by thexaero** [comment]
You're using the world map to claim, right?

**Comment by juicebin** [comment]
> You're using the world map to claim, right?

Yes, I am

**Comment by thexaero** [comment]
Thanks again! Going to release the fix very soon.
