### ISSUE TITLE
Title of claimed areas

### ISSUE THREAD

**Issue by MeryBence** [thexaero/open-parties-and-claims#180]
So, I put this mod into my survival server. I figured out how to claim and create parties, and also how to name the claimed area. I have 2 questions:
1.
How can I make it so that the claimed area has no info on who claimed it? Example: Lunar Fields - BenceMery's claim.  
2.
How can I make it, so that 2 players have the same claimed area limit, or can they claim the chunks? but with the same colour and name.

**Comment by thexaero** [comment]
1. You can't.
2. Each player has their own limit. Both players can set their color and name to the same thing.

**Comment by MeryBence** [comment]
Thank you. But I got another question. So I saw the mod in action. Is there a way to edit the claims, so that every player, everybody can open chests, use furnaces, etc.?
