### ISSUE TITLE
Editing settings for all claims the same time

### ISSUE THREAD

**Issue by MeryBence** [thexaero/open-parties-and-claims#181]
So I saw the mod in action. Is there a way to edit the claims, so that everybody can open chests, use furnaces, etc. in the claimed area?

**Comment by samuelh2005** [comment]
Yes, but it looks like you need to be an admin (operator) and edit the "Default Player Config". This will effect all players though. 

Or you can create a special "Server Claim" and modify it's permissions - but you need to be an admin again.

**Comment by thexaero** [comment]
Yes, you can edit the default player config, which affects all claims for options that are not configurable by every player. You can choose which options are configurable by players. Check the main server config file.
