### ISSUE TITLE
Please make the configs easier to read

### ISSUE THREAD

**Issue by Camawama** [thexaero/open-parties-and-claims#182]
Having so much text clustered together without spacing makes it extremely difficult to focus on one line. I keep losing my place.

**Comment by thexaero** [comment]
I don't control what TOML is. Please use a better text editor that supports it.

**Comment by Camawama** [comment]
I use Notepad++ and there have been many other configs files that I've gone through which are easier to read. I have nothing against it, just seeing if it's something you would consider.

**Comment by thexaero** [comment]
It's something I have no control over. Switch language to Python in Notepad++, it works pretty well.

**Comment by Camawama** [comment]
Oh, thank you! That helped a LOT!
