### ISSUE TITLE
New 'player-claim-mode' admin command.

### ISSUE THREAD

**Issue by samuelh2005** [thexaero/open-parties-and-claims#183]
A new player claim mode command would be nice for server admins to claim / unclaimed chunks for inactive players.
It could look like this ...

`/openpac-claims player-claim-mode <profile> [<sub-id>]`

This will switch the player to use the config of 'sub-id' which belongs to profile. If 'sub-id' isn't filled the 'main' one will be used. All 'open parties and claims' operations will switch to this config just like the `/openpac-claims server-claim-mode`.

`/openpac-claims player-claim-mode`

This will deactivate the config just like `/openpac-claims server-claim-mode` would.

This would probably be simple to implement as 'on the fly' config switching already exists.

**Comment by samuelh2005** [comment]
Admins could also use this command to solve conflicts between players.

**Comment by thexaero** [comment]
Thanks for the suggestion. It's basically the same suggestion as #53 but I'll consider your additions.
