### ISSUE TITLE
Add config option to be able to specify what blocks can be broken/interacted with by non-ally-members for claims and sub-claims

### ISSUE THREAD

**Issue by l3dotdev** [thexaero/open-parties-and-claims#186]
I would be happy to have a go at making a PR for this if you would like.

**Comment by thexaero** [comment]
There are already config options for that.

**Comment by l3dotdev** [comment]
Sorry if it was unclear but I am talking about on a per claim basis, so along with the server list of blocks, players can add their own to their claim configs

**Comment by l3dotdev** [comment]
If this already exists pointing me towards some documentation on how this works would be wonderful!

**Comment by thexaero** [comment]
Through the main server config file you can create exception groups for blocks/entities/items, similar to the default groups like Chests, Doors, Furnaces, Livestock. The custom groups become options in the player configs. The options can be toggled by any player per claim if you make them player-configurable. 

I think giving every player the ability to type in specific blocks themselves is not the best idea. It would significantly increase the potential size of each sub-config and I don't know how I would even limit it without making it unusable. I think server owners handling exception options is a way better system and works for any server. If a specific player thinks there needs to be a specific toggle added, they can ask the server staff and it'll be added for everyone. It's way more user-friendly and works way better with sub-config overrides. It's not like every player on the server plays with completely different content.
