### ISSUE TITLE
Expired Claims

### ISSUE THREAD

**Issue by SimonasVS** [thexaero/open-parties-and-claims#188]
Hey there,
I joined a server I haven't played in a while and noticed that they've updated the mod pack, thus adding the claim mod. I claimed some land and about a week later noticed that I couldn't do anything in my claim. It said 'Expired Claim' but I couldn't find any info about claims expiring anywhere. Is there a way to fix this? :)

**Comment by thexaero** [comment]
After a configured period of time, claims get expired to save server resources. It's supposed to be a very long time, more than a year of server uptime by default I think, but I guess the server you're playing on configured it very low. Only a server admin can fix this for you by unclaiming the expired claims so you can reclaim them.
