### ISSUE TITLE
Feature Request: Block interaction logging

### ISSUE THREAD

**Issue by MrHipsterG** [thexaero/open-parties-and-claims#191]
Hey! Something that I think would be really useful is some kind of block interaction logging system in the same vein as coreprotect. It'd make tracking down who griefed in a publicly accessible claim much easier.
It'd be an opt-in feature per claim so not every claim has to store block data by default.

Simply knowing who broke something in the last week would be extremely helpful.
Thank you for considering!

**Comment by thexaero** [comment]
There are other mods that do specifically that. You can use any claim protection mod on top of them, e.g. this one. Have you tried it?

**Comment by MrHipsterG** [comment]
I've been researching a mod that does blocklogging for 1.18 for a while, the only one I've found doesn't quite work right sadly. It'd be amazing to have an instance of that available for modern minecraft versions.

**Comment by thexaero** [comment]
I see. Well, I don't think it should be a part of a claim mod like this one. It's better if it's a separate mod completely.
