### ISSUE TITLE
[Feature Request] [Fabric 1.19] use grief defender events world guard.

### ISSUE THREAD

**Issue by MrJorman** [thexaero/open-parties-and-claims#20]
https://www.curseforge.com/minecraft/mc-mods/flan Take from here all the options for protecting territories, as well as flags on them, this is the coolest mod and the best for private territories, just take note of this topic, otherwise players protect chunks for themselves, but I can trample crops, kill them and do all sorts of things, and the Flan mod fixes this

**Comment by thexaero** [comment]
What specific things do you want from that mod? Not all of it is possible or a good idea in a mod that syncs with the clients. 
Crop trample protection and protection from killing the claim owner player? Please create a separate issue for each specific suggestion.

**Comment by MrJorman** [comment]
@thexaero Why would I create a separate one if you just need to move all the events from there, everything is private there, even things from mods and the configuration is convenient.

**Comment by MrJorman** [comment]
I wrote to the developer, unite with him and you will have the coolest privates that are better than FTB CHUNKS.
