### ISSUE TITLE
A solution for Pull Requests?

### ISSUE THREAD

**Issue by samuelh2005** [thexaero/open-parties-and-claims#201]
At the moment I know your [not accepting pull requests](https://github.com/thexaero/open-parties-and-claims/pull/156#issuecomment-1311561351). If you're scared about the licensing take a look at the [Contributor License Agreement assistant](https://github.com/cla-assistant/cla-assistant). It will require all people to "sign" a  'Contributor License Agreement' which gives you (Xearo) the rights to use their contributions.

For a normally closed source (e.g. your map mods) developer open source might be a bit scary at first (and for a long time?)! 

I could probably have these down by now:
* https://github.com/thexaero/open-parties-and-claims/issues/179
* https://github.com/thexaero/open-parties-and-claims/issues/183
* https://github.com/thexaero/open-parties-and-claims/issues/185
* https://github.com/thexaero/open-parties-and-claims/issues/200
* And probably the [Fabric Permissions Api](https://github.com/lucko/fabric-permissions-api) (LuckPerms) support

**Comment by samuelh2005** [comment]
If you want to see it in action, take a look at my [History Survival](https://github.com/ajh123-development/HistorySurvival) repository.

**Comment by thexaero** [comment]
Thanks.
Please chill out with trying to help me with every little thing all the time. You always seem to wrongly assume that everything is incredibly easy to implement and yet have no faith in me doing anything on my own. It's not helpful. It's disrespectful and very annoying.

**Comment by thexaero** [comment]
I forgot to add that I am going to accept PRs in the future.

**Comment by samuelh2005** [comment]
@thexaero A little apology:
Apart from I what I said - your mod is a very good mod as it is right now. A lot better than Towny!
Sorry if I have annoyed you.

**Comment by thexaero** [comment]
Thank you. I appreciate the apology. I hope you understand that if everything was a simple as you assume then every other claim mod would be a million times better than it is, considering some of them have been developed for ~ 10 years. Realistically, #200 could easily take longer than a month to implement even if it's all that I'm doing. It actually requires so much rewriting and complicates protection checks and the UI so much that I'm not sure that it's even worth it. I'll consider it though.

I'm going to end the beta very soon. Just trying to catch any significant bugs left in the mod. I'll probably start accepting PRs shortly after.
