### ISSUE TITLE
Add a way to disable ANY protection and not make claims expire

### ISSUE THREAD

**Issue by Amythyss** [thexaero/open-parties-and-claims#206]
Hello, today I tried your mod for my server and I really liked it. However I'd like to see: A way to disable ALL protections.
 
_I know you can disable player protection but there are still many protections that are kept, I'd like a way to disable that part completely, maybe similar to how the 'parties' part can be completely disabled_

**Comment by thexaero** [comment]
The "Claimed Chunk Protection" option in the player config does exactly that.

**Comment by thexaero** [comment]
To make claims not expire, configure it extremely high. Your server isn't going to run for hundreds of years is it?

**Comment by Amythyss** [comment]
Oh, that removes everything under [playerConfig.claims.protection] ? (including piston barrier and spawner hostile)

Why is it not grayed out in the player settings then?

**Comment by Amythyss** [comment]
> To make claims not expire, configure it extremely high. Your server isn't going to run for hundreds of years is it?

Hope not! haha
Thank you for your help though, this mod is awesome

**Comment by thexaero** [comment]
Yes, that disables everything. It's not supposed to grey out anything. There is no reason to block other options from being changed. Greyed out options are the ones not configured to be accessible by individual players. If you don't want players to turn protection back on, you can remove everything from the _playerConfigurablePlayerConfigOptions_ in the main config file. That will grey everything out.
> Hope not! haha
Thank you for your help though, this mod is awesome

Thanks!

**Comment by Amythyss** [comment]
Ok, so long story short if I want nothing to be protected (and players can't turn it back on) and claims to not expire I have:
- Set **playerClaimsExpirationTime** (openpartiesandclaims-server.toml) higher to make claims never expire
- Set **protectClaimedChunks** to false in every claim type (including wilderness)
- Remove everything under **playerConfigurablePlayerConfigOptions** in **openpartiesandclaims-server.toml**

Correct?
(Also, how would I make it so that players can't forceload either?)

**Comment by thexaero** [comment]
If nothing is in _playerConfigurablePlayerConfigOptions_, then all player claims use the default player config values. If forceloading is turned off there, then it's off for everyone. Server, wilderness and expired claims are not affected by this. You can configure them however you want.
You don't have to increase the expiration time for this purpose. That is a completely separate feature.

**Comment by Amythyss** [comment]
1. Can you please give me the specific names for disabling expiration?
```
#Whether to convert expired player chunk claims to "expired claims" instead of completely freeing them. This shouldn't be too bad for performance because it still reduces the number of unique claims.
playerClaimsConvertExpiredClaims = true
```
Will remove them directly, I want them to be permanent.
3. So I remove everythng in **playerConfigurablePlayerConfigOptions** and set **protectClaimedChunks** to false to disable claim protection. Correct?
4. Force loading is in **playerConfig.claims.forceload**

**Comment by riddemon** [comment]
Up

**Comment by Amythyss** [comment]
Hello? I'd like an answer to my last messge. Thank you
