### ISSUE TITLE
BlueMap integration

### ISSUE THREAD

**Issue by SzczurekYT** [thexaero/open-parties-and-claims#207]
Hello
[Bluemap](https://modrinth.com/plugin/bluemap) is a mod that renders a 2d/3d map in browser.
It would be nice if the claims were visible on it, just like in Xaero's Worldmap.
There's an [api](https://github.com/BlueMap-Minecraft/BlueMapAPI), so it shouldn't be too hard to implement using shape markers or extrude markers.

Thanks

**Comment by thexaero** [comment]
This mod does not implement any map integrations. You can make it a separate mod if you want to.
