### ISSUE TITLE
Server-claim Unable to interact with npc and villagers

### ISSUE THREAD

**Issue by Voidrunner42** [thexaero/open-parties-and-claims#214]
I found no way to configure server claims for "normal" players to be able to interact with villagers, NPCs, holograms etc.

If any additional info is needed tag me, and I will reply shortly.

**Comment by thexaero** [comment]
Well, there is a way that isn't even that obscure. Where were you looking?

**Comment by Voidrunner42** [comment]
> Well, there is a way that isn't even that obscure. Where were you looking?

I looked in the server-claims config
