### ISSUE TITLE
Ability to force unload all chunks as admin

### ISSUE THREAD

**Issue by vivvyinks** [thexaero/open-parties-and-claims#215]
A command that force unloads all chunks that players aren't in would be extremely helpful. I help manage a server that has a couple dozen players total and 10-20 online at any given time, and we have 16k chunks loaded, which, needless to say, takes a toll on the TPS. Something to lighten the load would be amazing.

**Comment by thexaero** [comment]
This seems completely unrelated to this mod. It's also how Minecraft works by default.
