### ISSUE TITLE
Server claim config lacking lectern option

### ISSUE THREAD

**Issue by LyndaFox** [thexaero/open-parties-and-claims#217]
Hello, I have spent some time looking over server claim config and is unable to find a setting to allow player to interact with lectern block to read the book on them. Tried turning on book reading setting to everyone but it only work for book in player inventory as it keep saying "you are not allowed to interact with this block". Please advise.

MC version: 1.19.2 Forge
Mod version: 0.16.6

**Comment by thexaero** [comment]
You can create your own options by editing the main config file, while the server isn't running. Find the option that has block groups like Controls and Doors. Read through the comment above the option. Use Notepad++ with language set to Python, for better readability.
