### ISSUE TITLE
[Suggestion] Add support for a quest mod like FTB Quests

### ISSUE THREAD

**Issue by xieve** [thexaero/open-parties-and-claims#218]
I love to finally see something moving in the space of Forge chunk claiming mods, I didn't really like FTB Chunks. But that mod has something this one doesn't have: the same teams for chunks and quests. Maybe it would be possible to integrate with the FTB Teams API? Doesn't necessarily have to be FTB Quests at all, but it'd be great if modpack developers could choose this and some compatible quest mod with it.

**Comment by thexaero** [comment]
Thanks for the suggestion.
It's something that should be done by quest mods themselves. I don't think I can affect what team system FTB Quests uses.

**Comment by xieve** [comment]
It should be possible to "synchronize" the teams that are created with this mod with FTB Teams

**Comment by thexaero** [comment]
I don't know if that's a good idea.

**Comment by thexaero** [comment]
Instead of this, I'm planning to add support for other team/party systems that already support quests.
