### ISSUE TITLE
Waystones mod

### ISSUE THREAD

**Issue by Themuteferret** [thexaero/open-parties-and-claims#219]
When using Fabric Waystones by LordDeathHunter, there is no way to allow players to use waystones in claims without owning the claim. I can't allow my players to use them inside of a server claim.

**Comment by Sewdohe** [comment]
I'm having the exact same issue. I'm fairly certain there is a setting to fix it, I'm just unsure how

**Comment by thexaero** [comment]
Have you tried adding a global block exception in the main config file?

**Comment by Themuteferret** [comment]
How would I do that?

**Comment by thexaero** [comment]
Look for it in the main config file.
