### ISSUE TITLE
Forceloaded chunks are not forceloaded in dimensions with no players

### ISSUE THREAD

**Issue by unilock** [thexaero/open-parties-and-claims#220]
If a chunk is marked as "forceloaded" in one dimension, and some sort of process is set in place that can be observed interdimensionally, then when all players leave that dimension, the aforementioned process will seize.

More concisely, an example (in singleplayer):

If I go to the Nether and put down an "Ender Tank" and a pump to pipe lava into it + forceload the chunk that it's in, then travel to the overworld and put down another Ender Tank, the tank in the overworld will never fill up with lava - as if there was nothing filling the tank. (note that the tank will still do so while I'm in the same dimension as it)

If I then forceload the chunk in the overworld with the tank + automatically pipe the fluid in the tank into some sort of void (trash can?), then travel back to the Nether, the tank will never empty of its lava - as if there was nothing emptying the tank. You get the idea.

This issue also exists in multiplayer - in the scenario above, if *no* players are in the Nether, the same will happen - the tank in the overworld will remain empty (or stagnant).
*However,* if there's at least one player in both the overworld *and* the Nether, the system will function as expected - lava goes into the tank in the Nether, and lava goes out of the tank in the overworld.

Mods used during testing:
- Minecraft: 1.18.2
- Forge: 40.2.0
- [Open Parties and Claims](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims/files/4344793): 0.16.6
- [Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/files/4418097): 23.2.0
- [Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/4424632): 1.29.2
- [DimStorage](https://www.curseforge.com/minecraft/mc-mods/dimstorage/files/3737321): 6.1.0 (for interdimensional tanks)
- [Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/3875976): 10.2.5.465 (for tanks with infinite fluid)

...
(extra mods used for convenience)
- [Inventory Profiles Next](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4370587): 1.9.2
- [Jade](https://www.curseforge.com/minecraft/mc-mods/jade/files/4082408): 5.2.6
- [McMouser](https://www.curseforge.com/minecraft/mc-mods/mcmouser/files/3561231): 1.0.0 (mac moment :( )
- [Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/3578801): 2.21
- [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/4392674): 3.10.0
- [libIPN](https://www.curseforge.com/minecraft/mc-mods/libipn/files/4370454): 2.0.2

(love the mod, by the way - far less clunky than FTB Chunks ;) )
(on that note, a search function in the settings menu would be nice :v )

EDIT: [Ender Storage 1.8.+](https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8/files/3951068) also did not work in testing, so it's likely not an issue with DimStorage.

EDIT: FTB Chunks works correctly with both of the above mods. (i probably should've tested that first)

**Comment by thexaero** [comment]
This is such a weird issue. The chunks actually are forceloaded. You can test it by placing a wheat farm. OPAC uses a forceloading system built into Forge. So it's not really on my end.
I don't know why the same doesn't happen with FTB Chunks. They're probably using a workaround or something.

**Comment by thexaero** [comment]
Are those all the mods that you're using? No server optimization mods?

**Comment by unilock** [comment]
That's correct; those are the only mods installed.
Maybe it's something to do with tile entities...? I'll check that with a furnace.

**Comment by unilock** [comment]
Update: The issue persists with vanilla furnaces, too.

**Comment by thexaero** [comment]
It does? Give me a moment. Going to test that.

**Comment by thexaero** [comment]
You are correct. Going to look if it's really something on my end or otherwise for a workaround.

**Comment by thexaero** [comment]
Alright. I see what's wrong. When it comes to keeping dimensions ticking entities, only persistent forceload tickets are considered for some reason, which isn't something that I'm using. 
So, as a workaround, there needs to be at least 1 ticket added with _/forceload_ in a dimension and all claim-based forceloads will also work then. Please test if that works for you.
I'll try to fix it though.

**Comment by unilock** [comment]
That does appear to have fixed it; thanks!

(although, what i was initially trying to do still doesn't work - that being running an enderman farm in the End, automatically collecting the XP as a fluid, and transporting it interdimensionally via an Ender Tank. but i'm pretty sure that can just be chalked up to vanilla mob spawning mechanics :P )

**Comment by thexaero** [comment]
Great!
Yeah, mob spawning is always tied to distance to players, not ticking chunks.
