### ISSUE TITLE
1.19.4 - Startup Crash ``InvocationTargetException`` Null 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [thexaero/open-parties-and-claims#224]
Forge 1.19.4-45.0.27
Mod Version ``open-parties-and-claims-forge-1.19.4-0.17.0``

Latest Log https://gist.github.com/P3rf3ctXZer0/ee23bf3d71d8ff1ad7b7eb4f8b7f0156
Crash Log https://gist.github.com/P3rf3ctXZer0/710fd7eb8a00cc01e04d928b9bb1e1da

I hope that helps you figure out the crash :D

**Comment by thexaero** [comment]
Thanks for reporting!
Try Forge 45.0.22 or older. Going to fix this though.

**Comment by P3rf3ctXZer0** [comment]
Minecolonies needs latest. I understand though :D

**Comment by thexaero** [comment]
Forgot to mention it in the commit but it's fixed now. Try 0.17.1.
