### ISSUE TITLE
Config for stream-water block for mobs

### ISSUE THREAD

**Issue by superhealing** [thexaero/open-parties-and-claims#225]
Hey, i was searching for hours this toggle that prevents any mobs to go past block simply water, that makes almost all vanilla mob farms not working. I didn't find a singular toggle with ctrl+f, issues here. Neither in-game sadly.

**Comment by thexaero** [comment]
I don't think that is caused by this mod.

**Comment by superhealing** [comment]
> I don't think that is caused by this mod.

When i unclaim from [Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap) (integrated from open-parties-and-claims) the mob can swim freely.
Additional, i'm using betterminecraft fabric v16.5

**Comment by thexaero** [comment]
Nothing in OPAC affects mobs passing water. If the issue is only happening inside claims then you're not describing the issue correctly. 
I just tested it myself and did not encounter any issues.

**Comment by thexaero** [comment]
If you're talking about the fluid barrier on claim edges, then that has a toggle in the player config. It has nothing to do with mobs though.

**Comment by superhealing** [comment]
The fluid barrier is disabled
And yes i may not explained correctly, however is the inside claims.

**Comment by thexaero** [comment]
Is it possible for you to film a video of it? Otherwise I don't think I understand what the problem is.

**Comment by thexaero** [comment]
Or you can try explaining it differently.

**Comment by superhealing** [comment]
I hope this is easier to see 
https://user-images.githubusercontent.com/34381388/228912349-95d401c0-33fb-4460-901a-6a09446d6f9f.mp4

**Comment by thexaero** [comment]
Thanks, now I understand. It has nothing to do with water. It's protection against raids which you can toggle.
