### ISSUE TITLE
Parties keep getting deleted 

### ISSUE THREAD

**Issue by B-DUB99** [thexaero/open-parties-and-claims#229]
I'm playing with friends on my server, and for some odd reason, they don't stay in there Parties, now and then they get deleted. once they "rejoin" by creating a new party, all the settings are good and the party is back. very annoying since we have to re-invite everyone.
For Some Reason this ONLY seems to affect all non-admin (oped) Party Claims,... any idea, how to fix this? 
Thank you!

Great Work BTW 👍

**Comment by thexaero** [comment]
Thanks for reporting!
What version of the mod (not Minecraft) are you using?
I fixed a bug like this months ago.

**Comment by thexaero** [comment]
Or I guess it wasn't the same exact issue. 
Please post your main config file at `[world directory]/serverconfig/openpartiesandclaims-server.toml`

**Comment by B-DUB99** [comment]
I think the mod version would be `0.16.5` if that helps, the main config file ( I had to change over to txt since `toml files` are not supported )

[openpartiesandclaims-server-claim-config.txt](https://github.com/thexaero/open-parties-and-claims/files/11153730/openpartiesandclaims-server-claim-config.txt)


EDIT: 
We're running on Fabric, not sure if I mentioned that at all

**Comment by thexaero** [comment]
Please tell me the full name of the .jar file you're using for the mod.
Also, that's not the config file that I asked for. Check the name.

**Comment by B-DUB99** [comment]
My Bad,

I'm using : `open-parties-and-claims-fabric-1.19.2-0.16.5.jar`


[openpartiesandclaims-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11158921/openpartiesandclaims-server.txt)

**Comment by thexaero** [comment]
Thanks! Seems fine. Do the members of the parties that get deleted not login for 168 hours straight of server uptime? That's the default party expiration time, which you can increase with `partyExpirationTime` in the _openpartiesandclaims-server_ config.

**Comment by B-DUB99** [comment]
I think the longest we did not sign in is around 72 hours, ish , 

is there a setting to disable the Party Expiration time, or should I just set it to a very very large number, is there a max number after all?

**Comment by thexaero** [comment]
I was asking about players from specific parties not signing in. Sounds like it's possible.
Set it really high. If you set it to 1000000, that's more than 100 years of server uptime.

**Comment by B-DUB99** [comment]
I mean, we all are playing relatively regularly, I't say at least once every 3 days

**Comment by thexaero** [comment]
Can you be more specific about when the parties get deleted? Does it happen on server restart or just randomly?

**Comment by thexaero** [comment]
By the way, please let me know if increasing the expiration time fixed the issue, when you're sure about it. Would be really helpful.

**Comment by B-DUB99** [comment]
I will let you know, I changed the number to a very high one, to see if that changed the issue.

Thank you for the Help!

**Comment by thexaero** [comment]
Hey, 
Has the issue happened since your last reply?

**Comment by B-DUB99** [comment]
I think it is fixed now, not sure tho. Since we don't play right now due to Finals coming Up, this is the Perfect Test if it works. 

as of right now, it does look good tho! 

Thank You

**Comment by B-DUB99** [comment]
After 2 Weeks of on / Off-line testing, this Issue has been resolved by increasing the Number of days/hours it takes before an inactive party is deleted to a very high Number. 

If it comes back and annoys me again, I'll let you know 

Great work!

**Comment by thexaero** [comment]
Alright, thanks for letting me know!
