### ISSUE TITLE
Corail Tombstone Items not working in claims

### ISSUE THREAD

**Issue by Archangelion** [thexaero/open-parties-and-claims#230]
So I'm running a server and found that tombstones and keys do not work in claims at all. I found the item and block names and entered them into the exception area of the server config file but it still denies the useage.

**Comment by thexaero** [comment]
Did you stop the server before editing the file?
Please also show me where you put the block/item ids for this.

**Comment by Archangelion** [comment]
> Did you stop the server before editing the file? Please also show me where you put the block/item ids for this.

`#Blocks to partially exclude from chunk protection. Supports block tags.
			#Just a block/tag ID in the list, e.g. "minecraft:lever" allows block interaction across the server if the item in the used hand isn't blocking it.
			#Prefix "hand$" is the same as no prefix but enforces an empty hand requirement in protected chunks. Prefix "break$" allows breaking the block(s).
			#Prefix "anything$" is the same as no prefix but allows interaction with any item held in the hand. Please make sure that no item does anything bad when used at a block with such an exception.
			#Add the same block/tag multiple times to use multiple prefixes. Supports patterns with special characters *, (, ) and |, where * matches anything, ( ) are used for grouping and | means OR.
			#For example ["minecraft:lever", "minecraft:*_button", "break$minecraft:*_button", "break$minecraft:(*_|)sand"]
			forcedBlockProtectionExceptionList = ["minecraft:crafting_table", "waystones:waystone","waystones:mossy_waystone","waystones:sandy_waystone", "mcwdoors:wooden_portcullis", "tombstone:decorative_grave_simple", "tombstone:decorative_grave_normal", "tombstone:decorative_grave_cross", "tombstone:decorative_grave", "tombstone:decorative_subaraki_grave", "tombstone:decorative_grave_original"]
`

**Comment by Archangelion** [comment]
And yes I did stop the server before editing. I had to do this for the Waystones mod which worked after I put them in the same location, however for Corail Tombstone it doesn't seem to work.

**Comment by Archangelion** [comment]
It's important to note as well that I added the key here and it didn't work either. Although weirdly enough neither did the rockets which was already in the code.

`#By default, most item right-click uses are disabled in protected chunks. To make an exception for a specific item, add it to this list. This option has a higher priority than "additionalBannedItemsList".
			#This list applies to both using an item at air and using it at a block/entity. Supports item tags. Supports patterns with special characters *, (, ) and |, where * matches anything, ( ) are used for grouping and | means OR.
			#For example ["minecraft:fishing_rod", "minecraft:ender_pearl", "minecraft:(red|green)_bed", "#minecraft:beds"]
			itemUseProtectionExceptionList = ["minecraft:firework_rocket", "tombstone:grave_key"]`

**Comment by thexaero** [comment]
Have you tried adding the tombstones in the entity exceptions? They might not be blocks.

**Comment by Archangelion** [comment]
> Have you tried adding the tombstones in the entity exceptions? They might not be blocks.

Just tested that out, including using anything$ to see if that would allow the key to work but I still get the error message: (Main Hand) You are not allowed to interact with this block!

**Comment by thexaero** [comment]
How did you get the block IDs? What is the ID on the F3 screen when you look at one? Having "decorative" in there does not seem right.

**Comment by thexaero** [comment]
It's exactly what I said. I had to go test it myself. Use "tombstone:grave_*" to include the actual gravestones. Not every block is an item and not every item is a block. Get block IDs from the F3 screen, not your inventory.
