### ISSUE TITLE
Redstone does not work with the offline forceload 

### ISSUE THREAD

**Issue by ZvandeKamp** [thexaero/open-parties-and-claims#235]
I have built a simple sugar cane farm with a observer detecting if the third block of sugar cane is grown and triggering the piston beneath it. 

Like this:
![image](https://user-images.githubusercontent.com/85412664/230725784-824e12c8-3908-4e48-b448-e53c2b821053.png)

It works fine when i am Online. But if am offline the sugar cane just grows to full length without the observer detecting it. 

Like this: 
![image](https://user-images.githubusercontent.com/85412664/230725863-5cef84e1-6267-43fd-b500-9f7c6c353299.png)

Should redstone work in forceloaded chunks? Or is this an expected behaviour?

**Comment by thexaero** [comment]
Thanks for reporting.
What version of the mod are you using? I'm pretty sure this is caused by an issue fixed somewhat recently.

**Comment by ZvandeKamp** [comment]
Hey, sorry for not mentioning that i am running on 0.16.6 and yeah it seems quite outdated.

The problem is that it is included in the newest version of the BetterMC Forge 1.19.2 modpack so i guess i have to open an issue on their github if you can confirm that this has been fixed in the newer versions.

**Comment by thexaero** [comment]
I can confirm that this works in the latest version and 0.16.6 is the last version that had the issue.

**Comment by ZvandeKamp** [comment]
Thank you for the quick reply your mods are really great!
