### ISSUE TITLE
Force Chunk Loading not working.

### ISSUE THREAD

**Issue by LucanC** [thexaero/open-parties-and-claims#237]
I've marked chunks as force loaded, yet they do not appear to be force loading the area. Using chunk loaders from a different mod, the entities appear to be working as intended. I've checked the config for references to force loading and they all appear to be set to on. Not sure if there's some other override I'm missing.

**Comment by thexaero** [comment]
Is it not #235?

**Comment by thexaero** [comment]
What version are you using?

**Comment by LucanC** [comment]
Version 0.16.6. The issue is happening with Create Trains, where they are not filling when at their station which is marked as force loaded. The station is in the Nether and it does not seem to fill when players are not in that dimension.

**Comment by thexaero** [comment]
Then I'm sure it's the #235 and #220 which has been fixed a long time ago.

**Comment by LucanC** [comment]
Brilliant, thanks for the help.
