### ISSUE TITLE
A little help with the config :)

### ISSUE THREAD

**Issue by breeece** [thexaero/open-parties-and-claims#241]
Hey Xaero! Love using your mods. They work really great for our server. Just curious how I would setup a new button for interacting with modded blocks/items such as a modded enchantment table and a mail box while in other player's claims. Setting it up so it has it's own category such as MODDED ITEMS interact: on or off so that I can add every modded item to the exception list. I found a way to add items into the controls category but I would like to make my own category. I was looking in the 
playerConfigurablePlayerConfigOptions
but..... I am not sure what I would start with.
claims.protection.exceptionGroups.block.interact.Controls   something like this but can I name it anything? such as
claims.protection.exceptionGroups.block.interact.Modded then add all the items/block from the mods that I want to add exceptions for. 
Didn't want to make a github post but, I couldn't find your discord if it exists. :X heh... Thanks buddy! Hope to hear from you soon.

**Comment by thexaero** [comment]
Thanks for the support!
The place where you were adding them to controls is where you can make new groups. Read the comment above that option which explains everything.

**Comment by breeece** [comment]
> Thanks for the support! The place where you were adding them to controls is where you can make new groups. Read the comment above that option which explains everything.

Any chance you could give an example? I'm having a bit of a hard time getting it to not crash on server launch. 

Keep getting an invalid separator "c" in array message. Might have accidentally hit a key somewhere.

**Comment by thexaero** [comment]
Every other group is already an example.

**Comment by breeece** [comment]
Ah okay. Well, I think I would of had it working had I not accidentally placed a random letter c in an array somewhere :'(
Any tips of finding which line this could be in ? the crash report doesn't specify.

**Comment by thexaero** [comment]
Please post the crash report

**Comment by breeece** [comment]
[crash-2023-04-29_01.01.59-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11358499/crash-2023-04-29_01.01.59-server.txt)

**Comment by breeece** [comment]
I just deleted the config and let it regenerate. :')
My new category is working but it's grayed out by default.  
I figured out how to change it but I do want the players to be able to set that to on/off/every/party, not be stuck on whatever I set it to by default.

EDIT: I've figured it out. Thank you :D

**Comment by thexaero** [comment]
Glad you figured it out!
