### ISSUE TITLE
Allowing access to Waystones from Waystones mod

### ISSUE THREAD

**Issue by jangro** [thexaero/open-parties-and-claims#242]
I've read around here and see suggestions to add "waystones:waystone" to the exception list, which I've done with this:

`forcedEntityProtectionExceptionList = ["minecraft:minecart", "force$waystones:waystone", "minecraft:villager", "break$minecraft:(trader_|)llama"]`

in `serverconfig/openpartiesandclaims-server.toml`
(I also added the examples to it for testing)

I also tried it without "force$" as that now seems redundant as this functionality has moved to this forcedEntityProtectionExceptionList

It doesn't seem to work. I _can_ activate the waystone and it is added to my waystone list, but it cannot be used with empty hand, and I can't teleport to it from my own waystone.

I'm doing this currently in Valhelsia 5.0.18a
thanks.

**Comment by thexaero** [comment]
There is no protection against teleporting to waystones, so you're probably not actually activating it.
The problem is that you're adding the id to entity exceptions, but it should be the one for blocks.

**Comment by thexaero** [comment]
Also, make sure it's the right block ID with the F3 screen.

**Comment by jangro** [comment]
Thanks, that was it! Putting it in `forcedBlockProtectionExceptionList` worked.

`forcedBlockProtectionExceptionList = ["waystones:waystone", "minecraft:crafting_table"]`

Is this the place to ask questions? I don't see a discord but want to ask in the right place. I have another issue with create deployers not being able to act on entities like breeding cows and using a knife on beef on a Farmer's delight cutting board.

**Comment by thexaero** [comment]
I have a Discord for my Patreon supporters.
Feel free to ask here but I'll only give short answers, not provide a whole guide.

Pretty sure you're either trying to use deployers on claim edge blocks or you're not using the latest OPAC version.

**Comment by jangro** [comment]
I'm an idiot. I'm a Patreon for months now and forgot there's a discord. see you there.
