### ISSUE TITLE
openpartiesandclaims-server.toml is resetting itself each time.

### ISSUE THREAD

**Issue by RosivDamotil** [thexaero/open-parties-and-claims#245]
I did try to make an exception for Waytones like this:

blockProtectionOptionalExceptionGroups = ["Controls{minecraft:lever, #minecraft:buttons}", "Doors{#minecraft:doors, #minecraft:fence_gates, #forge:fence_gates, #minecraft:trapdoors}", "Chests{minecraft:chest, minecraft:trapped_chest, #forge:chests/wooden}", "Waystones{waystones:waystone, waystones:mossy_waystone}", 

But the openpartiesandclaims-server.toml doesn't save the changes, instead creating a .bak file.
I have NO clue (as there is also no documentation how to exclude or include interactions) how to make an exception for Waystones.

The code is not documentation enough. ;)

**Comment by thexaero** [comment]
Absolutely everything that you can do in the config is explained in the config in full detail. 
If that's really the full option value, then it is not formatted correctly. Would have to be like this:
```
blockProtectionOptionalExceptionGroups = ["Controls{minecraft:lever, #minecraft:buttons}", "Doors{#minecraft:doors, #minecraft:fence_gates, #forge:fence_gates, #minecraft:trapdoors}", "Chests{minecraft:chest, minecraft:trapped_chest, #forge:chests/wooden}", "Waystones{waystones:waystone, waystones:mossy_waystone}"]
```
And make sure to stop the server before editing this file. The config system is implemented by the Forge Config API (port). That is what you're failing to work with, not my mod.

**Comment by RosivDamotil** [comment]
Ok, but the server was always offline.
I will give it a try though.

But honestly I have no clue how to configure all of it when it still resets each start of the server.

Now it worked!
Just have to figure out, how to enable it to be edited in the Server-Settings or the "My Player Config"...

**Comment by thexaero** [comment]
That is also explained above the option.

**Comment by RosivDamotil** [comment]
Thank you for your support! I mean it!
Finally read something and almost understood it.

Thank you! Also for your great mods! :)

**Comment by thexaero** [comment]
No worries. Thanks for the feedback!
