### ISSUE TITLE
Unlisted Dependency: Forge Config API Port

### ISSUE THREAD

**Issue by n4sr** [thexaero/open-parties-and-claims#246]
A fabric server will fail to launch and output an error saying that Forge Config API Port is a required dependency and is unmet. This is not mentioned within the README.md. I believe that it would be worth adding a line to the README.md that makes mention of it. I have not tested or seen if this same issue happens on the client, but that would be worth looking into.

**Comment by DannyGames023** [comment]
I have a Forge server running 1.19.4, but the Forge Config API Port is only available for Fabric 1.19. That may be why when I start the game, it crashes.
