### ISSUE TITLE
Unexpected Party Disbanding Bug

### ISSUE THREAD

**Issue by troybaxter99** [thexaero/open-parties-and-claims#247]
For some reason my friend's party keeps disbanding and kicking people from the party without him doing anything. One minute it is fine, and the next we are suddenly not in the same party.

Minecraft Version: 18.2

**Comment by thexaero** [comment]
Did no member of the party log in for a week straight of server uptime?
There is an option called "partyExpirationTime" in the main config file that you might want to increase.

**Comment by troybaxter99** [comment]
No. In fact the party owner/server owner had logged in earlier that day and
left while the party was intact. I'll contact him to check to see the
configs.

**Comment by thexaero** [comment]
What version of the mod is used?
In the latest update I fixed an issue which I now realize could easily cause something like this.

**Comment by troybaxter99** [comment]
We are using version 0.16.5.

**Comment by thexaero** [comment]
That version is old and bugged

**Comment by troybaxter99** [comment]
Gotcha. I will tell the server owner that we should probably upgrade to
version 17.3 on the mod.

**Comment by thexaero** [comment]
Awesome! Please create a new issue if the issue persists on 0.17.3.
