### ISSUE TITLE
SERVER CRASH ON BOOT

### ISSUE THREAD

**Issue by breeece** [thexaero/open-parties-and-claims#248]
Can't seem to figure this one out Xaero. :( Never had an issue before. Haven't made any changes recently. This is what I'm getting.
[crash-2023-05-21_21.38.04-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11527424/crash-2023-05-21_21.38.04-server.txt)
[debug.log](https://github.com/thexaero/open-parties-and-claims/files/11527428/debug.log)

Seems to kinda mention the open pac :\ Not sure if it could be the cause? Even though I have no running server in the background I get a failed to bind to port message.

**Comment by thexaero** [comment]
I don't think it's related to OPAC. You can easily test by removing the mod jar and retrying.

**Comment by breeece** [comment]
> I don't think it's related to OPAC. You can easily test by removing the mod jar and retrying.

Okay, thank you. Not sure if there is something else going on within my system. :\ failing to bind to port randomly. Idk. But thank you Xaero!

**Comment by thexaero** [comment]
Did you test it? It could be related, I'm not 100% certain.
