### ISSUE TITLE
Request/Suggestion: Dynmap support?

### ISSUE THREAD

**Issue by Waterspark63** [thexaero/open-parties-and-claims#250]
I was wondering if theres any possibility/if it's possible to get claims to appear on dynmap, even if you can't configure them on that screen. Also, a bit off topic to that, how do I add the flair things I see in other issues (i.e. how it says 'enhancement', 'bug', etc?)

**Comment by thexaero** [comment]
If someone makes a mod for that then probably yes. Not going to be me though.
