### ISSUE TITLE
Received following crash report 

### ISSUE THREAD

**Issue by Neferite** [thexaero/open-parties-and-claims#252]
Evening, as per title please refer to attached crash report.

Thank you.

Nef

**Comment by Fuzss** [comment]
The missing class had been deprecated for a while now and has been removed in the 1.20 port of FCAPI.
Configs are now registered in `fuzs.forgeconfigapiport.api.config.v2.ForgeConfigRegistry`.

**Comment by thexaero** [comment]
@Fuzss Thanks for the info!
