### ISSUE TITLE
[Bug] Crash when making a new world, on latest OPAC [Fabric 1.19.2 0.14.21]

### ISSUE THREAD

**Issue by pokesmells** [thexaero/open-parties-and-claims#253]
https://mclo.gs/RU5sW81

open-parties-and-claims-fabric-1.19.2-0.17.4

**Comment by thexaero** [comment]
Yeah, I'm already on it. Noticed it as soon as I released everything.
Appreciate the report though!

**Comment by pokesmells** [comment]
No problem boss, thanks for the feedback much appreciated👍
