### ISSUE TITLE
Config file on server resets to default during startup

### ISSUE THREAD

**Issue by Guy-IV** [thexaero/open-parties-and-claims#257]
As the title mentioned the config file will reset any and all changes made to it when the server is booted up. 

15.06 09:55:21 [Server] Server thread/WARN Configuration file /./world/serverconfig/openpartiesandclaims-server.toml could not be parsed. Correcting
15.06 09:55:21 [Server] Server thread/WARN Configuration file ./world/serverconfig/openpartiesandclaims-server.toml is not correct. Correcting
15.06 09:55:21 [Server] Server thread/WARN Incorrect key serverConfig was corrected from null to its default, SimpleCommentedConfig:{}.
15.06 09:55:21 [Server] Server thread/WARN Incorrect key serverConfig.defaultLanguage was corrected from null to its default, en_us.
15.06 09:55:21 [Server] Server thread/WARN Incorrect key serverConfig.autosaveInterval was corrected from null to its default, 10.
15.06 09:55:21 [Server] Server thread/WARN Incorrect key serverConfig.playerSubConfigLimit was corrected from null to its default, 64.

This continues for every line and includes many that I did not touch. All edits were done through Visual Studio Code and other mod configs are not experiencing resets. This mod is being run as part of BetterMinecraft v18.5.

This is one of the lines of code that I have changed to show the way I made the changes, all changes are in the same format.

forcedBlockProtectionExceptionList = ["minecraft:crafting_table, yigd:grave"]

**Comment by thexaero** [comment]
Resetting or parsing this config is not up to my mod.
The Forge config system is saying the following:
```
Configuration file /./world/serverconfig/openpartiesandclaims-server.toml could not be parsed. Correcting
```

You are probably breaking the toml format. The fact that the only line that you provided as an example is also incorrectly formatted isn't helping your case, although it's not incorrect enough to break the toml parsing. There is most likely something else you're doing very wrong. 
This is how the line you posted should actually look:
```
forcedBlockProtectionExceptionList = ["minecraft:crafting_table", "yigd:grave"]
```

**Comment by Guy-IV** [comment]
That is embarrassing, to say the least, I am going back through it and hopefully, it was a basic mess up with my edits. I will mention that I have not added or removed any lines or changed the format of the overall code in any way. As my incompetence was proven previously I will add all the changes I have made.

openpartiesandclaims-server.toml
=======================================

This is part of the playerConfigurablePlayerConfigOptions section and I put it between beds and beacons
"claims.protection.exceptionGroups.block.interact.Waystones"

maxPlayerClaimForceloads = 1

This is part of the blockProtectionOptionalExceptionGroups and has a comma before and after.
"Waystones{fwaystones:waystone, fwaystones:desert_waystone, fwaystones:red_desert_waystone, fwaystones:stone_brick_waystone, fwaystones:nether_brick_waystone, fwaystones:red_nether_brick_waystone, fwaystones:end_stone_brick_waystone, fwaystones:deepslate_brick_waystone, fwaystones:blackstone_brick_waystone}"

forcedBlockProtectionExceptionList = ["minecraft:crafting_table", "yigd:grave"]

entityProtectionOptionalExceptionGroups = ["Traders{minecraft:villager, minecraft:wandering_trader, goblintraders:goblin_trader, goblintraders:vein_goblin_trader}", 
This section continues with the rest as default

itemUseProtectionExceptionList = ["minecraft:firework_rocket", "fwaystones:pocket_wormhole"]

Nothing else in this config was edited. I attempted to add the settings on the other config as required.

openpartiesandclaims-default-player-config.toml
=======================================

#When enabled, claimed chunk protection makes an exception for interaction with the following blocks: Waystones, All Types.
#
#1) Party - players or entities owned by players in the same party as you.
#2) Allies - players or entities owned by players in parties that are allied by yours.
#3) Every - all players/entities.
Waystones = 3

This lies between furnaces and beacons.

Thank you for helping fix the mess I made for myself.

**Comment by Guy-IV** [comment]
Well, would you look at that, somehow that was the issue that was making it fall apart. The server is up and the changes have not been reverted, thank you for the help!

**Comment by thexaero** [comment]
No worries, these configs aren't the easiest thing to work with, but it's necessary when you want detailed customization.
