### ISSUE TITLE
[1.19.2 Forge] Crash on SMP with Create Deployers

### ISSUE THREAD

**Issue by katubug** [thexaero/open-parties-and-claims#258]
Hi! I'm using version 0.7.5 of OPAC and 0.5.1b of Create. Forge 43.2.8

I get the following crash on my server for the Cottage Witch modpack: https://pastebin.com/DridWDpF

I see in previous patch notes that Deployers are addressed, but I wonder if the new version of Create reopened an old issue?

Thanks in advance for your time!

**Comment by thexaero** [comment]
Thanks for reporting!
Wish someone told me sooner about this.

**Comment by thexaero** [comment]
Yeah, turns out the latest Create version isn't supported at all. Going to fix that.

**Comment by thexaero** [comment]
And it turns out there is a lot I need to change.
Use version 0.5.0 for now while I work on the 0.5.1b support.

**Comment by katubug** [comment]
I think people tend to assume "oh someone else will report it" and then
they don't check, haha.

Thanks for the quick response, I hope it's not too hard to fix! Unfortunately I can't downgrade Create on my server, but we can hold off updating to the modpack version where we switch from FTB Chunks to OPAC. We're looking forward to switching though!

**Comment by thexaero** [comment]
> I think people tend to assume "oh someone else will report it" and then
they don't check, haha.

Probably exactly what happened. It's been like a month though! I guess the crash is somewhat rare and none of the Create mechanics being protected anymore isn't as obvious as it sounds. Everyone just assumes it works.

I already started working on this and fixed most things but there are new/reworked mechanics in 0.5.1, so it'll take some more time.

**Comment by katubug** [comment]
Never underestimate the power of "someone else will do it" haha. And yeah, I think you're correct that folks probably just assume it's all working.

And sounds good! Looking forward to the update! Thank you :D

**Comment by Dr-WeiAL** [comment]
Also Open Parties and Claims cannot protect the blocks inside the block from being destroyed by the Contraption of Create outside the block

**Comment by thexaero** [comment]
@Dr-WeiAL Nothing works, which I already said

**Comment by Dr-WeiAL** [comment]
Okay, sorry.

**Comment by katubug** [comment]
How's it going? Not trying to pressure you, just curious! I am working on an in-dev project which uses OPAC and Create and would love a rough estimate so I can figure out how much time I have to get the rest of my ish together. 😂

Thanks for your time, and for all your hard work! It's greatly appreciated!

**Comment by thexaero** [comment]
@katubug I'm almost done.

**Comment by katubug** [comment]
Thanks so much! I appreciate all the effort you put into your excellent mods. :)

**Comment by thexaero** [comment]
@katubug You're very kind, thank you!
