### ISSUE TITLE
Server crashes when I join

### ISSUE THREAD

**Issue by UnstableStrafe** [thexaero/open-parties-and-claims#259]
[latest.log](https://github.com/thexaero/open-parties-and-claims/files/11780245/latest.log)
 Here's the error: java.lang.RuntimeException: (Open Parties and Claims) Please report this! f9f55ae2-aa4e-47b3-baf2-3b9788755e7c

**Comment by thexaero** [comment]
This isn't the log file that contains what you're quoting. Can you find the right one?

**Comment by UnstableStrafe** [comment]
[latest.log](https://github.com/thexaero/open-parties-and-claims/files/11781942/latest.log)

I think this might be it

**Comment by thexaero** [comment]
Thanks! Yeah, that's it. 
Does this happen often?

**Comment by UnstableStrafe** [comment]
Yeah it happens every time the server is loaded. I tried downgrading the mod version to one that worked before but that didn't help so idk if its an issue with another mod too

**Comment by thexaero** [comment]
Can you try removing OPAC? I have a feeling it will still crash.
