### ISSUE TITLE
Add player protection option

### ISSUE THREAD

**Issue by thexaero** [thexaero/open-parties-and-claims#26]

**Comment by lynnpye** [comment]
@thexaero Upvoting fwiw :)

**Comment by GitJhopa** [comment]
@thexaero please add protection PVP on / PVP off , flag in region.

**Comment by DonorKrovi** [comment]
good idea

**Comment by XionioXMaster** [comment]
not bad

**Comment by DonorKrovi** [comment]
> _No description provided._

Good afternoon, my server has significantly upgraded its online! Thanks to your fashion I have great protection! But unfortunately, even the server chunk can not protect players from Grappling, cases of killing new players during generation have become more frequent, is it possible at the moment to disable PVP in the server chunks?

**Comment by thexaero** [comment]
@DonorKrovi You can't do that yet.
