### ISSUE TITLE
Diamond Spikes from Kibe Utilities causing crash in claimed chunk

### ISSUE THREAD

**Issue by SCPRedMage** [thexaero/open-parties-and-claims#260]
Minecraft 1.19.2 with Fabric 0.14.21
Kibe Utilities 1.9.11-BETA

Server is crashing when a mob is damaged by diamond spikes in a claimed chunk.

It appears the problem is that hasChunkAccess() in ChunkProtection.java checks if accessor is an instance of Player, but then tries to cast it as ServerPlayer.

This can be fixed by changing line 449 to:
```boolean isAPlayer = accessor instanceof ServerPlayer;```

[crash-2023-06-19_07.01.35-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11788923/crash-2023-06-19_07.01.35-server.txt)

**Comment by thexaero** [comment]
Thanks for reporting!
Ideally, I'd prefer all fake players to be ServerPlayer as well, which is usually so, but I'll change it.
