### ISSUE TITLE
"*" special character not matching modIDs

### ISSUE THREAD

**Issue by Chubblezap** [thexaero/open-parties-and-claims#261]
Hello, big fan of your mods and trying to set up something for my server.

I want players to be able to sit in benches, chairs, stools etc in any claim, so I'm trying to add them to the block exceptions config like i've already done for a number of other blocks. However, there are *many* mods that add these kinds of things, so to keep things relatively painless I simply put in "*_chair", etc. but this doesn't seem to work.

Is this something that's possible to do and I'm just not formatting it right, or do I need an entry like this for every modID?

**Comment by thexaero** [comment]
I'm pretty sure this should work.

**Comment by thexaero** [comment]
Yeah, I'm even more sure now. Where are you putting this?

EDIT: Please post the whole option.

**Comment by Chubblezap** [comment]
It's for forcedBlockProtectionExceptionList, to exclude the block interact function from chunk protection. The whole list looks like this

`forcedBlockProtectionExceptionList = ["minecraft:crafting_table", "cobblemon:*", "waystones:*waystone", "waystones:*sharestone", "lootr:*", "universal_shops:*", "*bench", "*chair", "*seat", "*stool", "*lamp"]`

EDIT: I can interact with them in admin mode, but not in normal mode

**Comment by thexaero** [comment]
And what's the ID of the chair that you're testing on the F3 screen when you point at it?

**Comment by Chubblezap** [comment]
I've been testing on another_furniture:spruce_bench, but after testing this morning, i went back to the server and it seems to work now? I'm starting to think this was an issue with changing the configs while the server was on, and the daily reset gave the server a chance to pick up the changes, which i wasn't expecting because the rest of the configs seem to update in real time. Sorry for the trouble, seems to be user error on my part.

**Comment by thexaero** [comment]
You can't change the main config while the server is running. A restart will usually just reset it too. You need to stop the server before making changes. I mention this everywhere.
