### ISSUE TITLE
Hey guys Making Fabric Waystones work for our server, What am I doing wrong?

### ISSUE THREAD

**Issue by SiennaWesty** [thexaero/open-parties-and-claims#262]
openpartiesandclaims-server.

[serverConfig.claims.protection]
blockProtectionExceptionList = ["fwaystones:waystone", "minecraft:crafting_table", "fwaystones:blackstone_brick_waystone", "fwaystones:desert_waystone", "fwaystones:deepslate_brick_waystone", "fwaystones:end_stone_brick_waystone", "fwaystones:nether_brick_waystone",  "fwaystones:stone_brick_waystone", "fwaystones:red_nether_brick_waystone"]

**Comment by thexaero** [comment]
Is that a super old version of OPAC? This option isn't used anymore.

**Comment by SiennaWesty** [comment]
> Is that a super old version of OPAC? This option isn't used anymore.

Ahh Yes that's right, its in the new config now and is working well!! Thank you

This one: forcedBlockProtectionExceptionList =

**Comment by thexaero** [comment]
@SiennaWesty Great! By the way, try replacing all of the waystone entries with 2: 
`"fwaystones:waystone", "fwaystones:*_waystone"`
Can even do the following to not be mod specific:
`"*:waystone", "*:*_waystone"`
Just `"*:*waystone"` would work too I guess but doesn't guarantee that "waystone" is a separate word, although it probably would be in practice.
