### ISSUE TITLE
[BUG] Crash with latest version of OPAC when joining a world [Fabric 1.19.2/0.14.21]

### ISSUE THREAD

**Issue by pokesmells** [thexaero/open-parties-and-claims#263]
MC version: 1.19.2
Fabric Version: 0.14.21
OS: Win 11 Pro
Mod version: open-parties-and-claims-fabric-1.19.2-0.17.6

Crash log - https://mclo.gs/9Im3Zho

**Comment by thexaero** [comment]
It's the [NumismaticClaim](https://github.com/Globox1997/NumismaticClaim) mod crashing.

**Comment by pokesmells** [comment]
Thanks for the info :)

**Comment by thexaero** [comment]
No problem!
