### ISSUE TITLE
How do I make it so that others can left click but not destroy the block?

### ISSUE THREAD

**Issue by Dr-WeiAL** [thexaero/open-parties-and-claims#265]
Can this be done with the existing functionality to make this possible please?
I want to use [QuickShop](https://www.spigotmc.org/resources/quickshop-reremake-1-20-1-ready-multi-currency.62575/) in a Chunk, but it has to be left-click sign to buy/sell, and if it is allowed to be destroyed directly, the other non-shop area notice boards will be destroyed

**Comment by thexaero** [comment]
Nope.
I'll consider adding that though! #266

**Comment by Dr-WeiAL** [comment]
Okay, thank you very much!
