### ISSUE TITLE
Turn off region protection by proximity

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#268]
Tell me, please, where to turn off the function so that the private will act a few more blocks from the main private? And then the players make the regions close to each other, and it turns out that the owner cannot interact with objects next to someone else's region.

**Comment by thexaero** [comment]
It's in the player configs.

**Comment by GitJhopa** [comment]
Sorry, but I can't find.

**Comment by GitJhopa** [comment]
How to make the nearest blocks next to the region not be protected?

**Comment by thexaero** [comment]
The only thing that neighbor chunks are protected against by default is item-on-air use with a lot of exceptions. Feel free to turn it off with "Protect Item Use in Neighbors", if you want to experience the reason it exists.

**Comment by GitJhopa** [comment]
thaank bro

**Comment by thexaero** [comment]
No problem!
