### ISSUE TITLE
Supplementaries:blue_bomb breaks plants in a foreign region

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#270]
Supplementaries:blue_bomb breaks plants in a foreign region

**Comment by thexaero** [comment]
Have you added it to the forced entity barrier list?

**Comment by GitJhopa** [comment]
no , bro.

**Comment by GitJhopa** [comment]
What if I want to enable PVP in the region and make a pvp arena? I need these bombs.

**Comment by GitJhopa** [comment]
I can't completely block them for the region, please note that I can make PVP arenas where these bombs should be, but they break crops and grass.

**Comment by thexaero** [comment]
Then make a barrier group for the entity `supplementaries:bomb`, as exists for ender pearls, and don't enable it in the PVP arenas.

**Comment by thexaero** [comment]
Should probably not have the bomb usage as an exception in claims besides the arena too.
