### ISSUE TITLE
BlueMap Listing

### ISSUE THREAD

**Issue by Romaq** [thexaero/open-parties-and-claims#271]
https://github.com/BlueMap-Minecraft/BlueMapAPI should allow a mod to provide data so Bluemap can mark claims on the map. Would this be easy enough to impliment?

**Comment by thexaero** [comment]
It is providing data to anything that wants to use it. Not my job to improve bluemap though.

**Comment by mikaba-eu** [comment]
Seems not that hard to implement?

https://github.com/pop4959/ChunkyBorder/blob/master/common/src/main/java/org/popcraft/chunkyborder/integration/BlueMapIntegration.java

https://github.com/Flemmli97/Flan/pull/199/commits/666d67e62e68e7990ee60406bde9c54ef6e7d834

I can create in thems repo a issue too. But its seems they have exactly the same policy that another should implement the integration?

**Comment by Romaq** [comment]
I believe both mod authors take the view, "I provide the data. What *you* do with it is a *you* problem." Because we both really want both "them" authors to focus on making their own mods better, their position on it really isn't a bad one. I'm simply not in a position to accept this as a "me" problem right now, likely not ever. But it is an opportunity for someone to take on as their own.

**Comment by thexaero** [comment]
@Romaq Me and the BlueMap authors aren't the only people who can make this happen. Anyone can use the APIs. The best thing for this would be an addon made by a third person. I think you get that though.
But if anyone between the two of us would have to add visual map features, it would be the map mod, not the claim mod. I find it strange when people expect me to make addons for other map mods when I already have my own I should be working on.

**Comment by Romaq** [comment]
Right. As my wife tells me, I don't get told, "no" unless I ask. ;-) But in all seriousness, if it isn't something you find fits with your VERY good work with Xaero's Mini/ World map business, I'm interested in keeping you working on *THAT* to your best ability without added distraction.

My hope is that someone else can step up to the plate for making an add-on connector bridge. :) If not, that's ok. Life happens.

**Comment by thexaero** [comment]
@Romaq Thanks for understanding. Let's hope. If it's as simple as people claim, then it might happen soon.

**Comment by mikaba-eu** [comment]
I understand the point of view. But I also have to say that you or the other team could simply implement the whole thing super quickly. Because at least you know your own API inside out and at bluemap the api looks very easy because they have an example for it. I would like to do it myself, but I'm a total java noob and I'm currently having a hard time with the minecraft mods because I can't find the entry points and then cross compile between forge and fabric is complete black magic for me.

**Comment by thexaero** [comment]
> I understand the point of view.

Proceeds to not understand it.
