### ISSUE TITLE
[Feature Request] A very complex Party system.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#273]
Please make commands to add a player to your private, something like /rg addowner or /rg addmember - and the player will be added to your private. And then the players complain to me that nothing is clear with the Party, that if a player is invited to his Party, then he cannot create his own, and if he creates his own and in order to invite him, I need to have my own too ... In short, I got confused, like other players, please do simple 2 commands /rg addmember or /rg addowner and that's it! Removing a player from my region /rg removeowner or /rg removemember

**Comment by thexaero** [comment]
The problem you described isn't even real.

**Comment by thexaero** [comment]
And if you keep patronizing me, I'll simply block you.
