### ISSUE TITLE
When I go by boat to a foreign region, I can break other people's frames, armor racks and other entities.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#274]
When I go by boat to a foreign region, I can break other people's frames, armor racks and other entities. I forbade boats in a foreign region, but these boats can be entered from Wilderness or from your region

**Comment by thexaero** [comment]
I'm very surprised that boats break item frames. Had no idea.
I can't seem to break armor stands or any other entities. How did you manage that and what other entities?

**Comment by GitJhopa** [comment]
> I'm very surprised that boats break item frames. Had no idea. I can't seem to break armor stands or any other entities. How did you manage that and what other entities?

mod Zetter check. Zetter:easel.

**Comment by thexaero** [comment]
Thanks, I'll check it out.

**Comment by GitJhopa** [comment]
And don't forget the frames from Quark mod!)

**Comment by GitJhopa** [comment]
In short, boats can destroy some entity
