### ISSUE TITLE
create:display_link Can be opened in a foreign region

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#276]
create:display_link Can be opened in a foreign region

**Comment by thexaero** [comment]
Give me an example of griefing that lets you do on version 0.17.6 because changes to the display link are protected.

**Comment by GitJhopa** [comment]
Yes, you can't change it. But the GUI opens.

**Comment by thexaero** [comment]
Please give me an example of when that would be a problem.

**Comment by thexaero** [comment]
Create opens that screen on the client side. Anything that is displayed there is already on the client side.

**Comment by GitJhopa** [comment]
> Please give me an example of when that would be a problem.

I wrote that I was able to open this GUI in a foreign region.

**Comment by GitJhopa** [comment]
And that's all.

**Comment by thexaero** [comment]
Alright. Well, that's not the only screen that Create opens without asking the server first. I could send a packet to close the screen after it opens, but that wouldn't be protecting anything.

**Comment by GitJhopa** [comment]
It will be great if you do this.

**Comment by thexaero** [comment]
Why would that be great?

**Comment by GitJhopa** [comment]
In a foreign region, I cannot open the GUI of stoves and other blocks, mechanisms, but this one can. I consider this a bug.

**Comment by thexaero** [comment]
It would be even weirder if it opened for a split second though. It's probably better to keep it open so that it's more transparent to the claim owner that any player can see inside (with a modified client?).
