### ISSUE TITLE
Potato cannon from mod Create Sets players on fire in a foreign region where PVP is disabled

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#284]
Potato cannon from mod Create Sets players on fire in a foreign region where PVP is disabled

1. Enter a foreign region where PVP is disabled
2. Get a potato cannon and create:blaze_cake
3. Shoot a player and he will burn.

P.S: I will not ban the use of the cannon in foreign regions, since this can be done on the border of the region, a fix is needed, thanks!

**Comment by thexaero** [comment]
Thanks for reporting!
