### ISSUE TITLE
[Feature Request] Add please xaero.pac_max_claims for LuckPerms support.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#285]
Add please xaero.pac_max_claims for LuckPerms support. I want to use the LuckPerms mod and I would like to give the rights to the maximum number of private chunks to the player in it. Thank you!

**Comment by thexaero** [comment]
I did.

**Comment by GitJhopa** [comment]
No working. xaero.pac_max_claims.1000

**Comment by GitJhopa** [comment]
permissionSystem = "luck_perms"

**Comment by thexaero** [comment]
That's not how LuckPerms works.

**Comment by GitJhopa** [comment]
And how to add claim  chunks to a group?

**Comment by thexaero** [comment]
By setting meta value of xaero.pac_max_claims to 1000. I don't have to explain how to use LuckPerms.

**Comment by GitJhopa** [comment]
oh thank

**Comment by celophys** [comment]
Hi have the same problem, how can i change the max claims with luckperms?

**Comment by timiliris** [comment]
> By setting meta value of xaero.pac_max_claims to 1000. I don't have to explain how to use LuckPerms.

no but you don't make the effort of giving good documentation it's why you need to explain that ! i use luckperms on java server for years now and i'm there trying to figure why it's not working ... 

good dev , but really bad on support and explication of your product , make a fucking wiki it's free there !

**Comment by thexaero** [comment]
> > By setting meta value of xaero.pac_max_claims to 1000. I don't have to explain how to use LuckPerms.
> 
> no but you don't make the effort of giving good documentation it's why you need to explain that ! i use luckperms on java server for years now and i'm there trying to figure why it's not working ...
> 
> good dev , but really bad on support and explication of your product , make a fucking wiki it's free there !

You didn't have to come here to embarrass yourself like that...
