### ISSUE TITLE
Spam about incorrect key on config initialization

### ISSUE THREAD

**Issue by RhythmicSys** [thexaero/open-parties-and-claims#288]
This only happens on the first startup, after the config has been initialized, subsequent restarts do not have this issue

Log:
https://mclo.gs/sFwYIa4#L312

**Comment by thexaero** [comment]
It's not an issue. That's how the forge configs work.

**Comment by RhythmicSys** [comment]
This is on fabric, but I guess you're writing for forge then using an api port or something in that case.
