### ISSUE TITLE
SUGGESTION: diamond economy integration

### ISSUE THREAD

**Issue by diznover** [thexaero/open-parties-and-claims#29]
In the [diamond economy](https://modrinth.com/mod/diamond-economy) modification, there is a game currency inside, inside the game digital wallet can be replenished with in-game items, and in your modification there is the possibility of private chunk. What if the players had to pay for what they owned the territory for? With any period of time, a day, a week, a month, and they would pay a certain amount of money for 1 chunk, for example, a player will privatize 4 chunks, and 1 chunk is worth 10 conventional units of currency, so he must pay 40 units of currency. I think it would be cool and the players wanted to get back into the game.

**Comment by thexaero** [comment]
Thanks for the suggestion.
I don't think I want to build something like this into the mod. Maybe somebody else will make a separate addon, if it has high enough demand. Storing separate timers for each chunk claim is very incompatible with the current claim storage, which is optimized for server-client sync, so those values would likely need to be stored separately anyway.

**Comment by diznover** [comment]
Thanks for the answer. High demand you say? I think I can do something.

**Comment by thexaero** [comment]
Alright, closing the issue then.
