### ISSUE TITLE
[BUG] A player who is in other regions as a member or ally cannot start their mechanisms.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#291]
The owner Wayder added a friend Welic to his region, his friend Welic is trying to place his drill to clear the area for the train rail, but the drill does not work in the Wayder region, although Welic is added to it.

**Comment by GitJhopa** [comment]
Bur Welic places in his region, which is in contact with the Wayder-a region.

**Comment by GitJhopa** [comment]
![image](https://github.com/thexaero/open-parties-and-claims/assets/86250668/24ff9809-d100-4c9e-9b27-5bde67c0aa05)
![image](https://github.com/thexaero/open-parties-and-claims/assets/86250668/05225ad6-b1c3-4e21-83e3-022894e13e15)
![image](https://github.com/thexaero/open-parties-and-claims/assets/86250668/a1910943-d642-447d-844a-7779f73f010b)

**Comment by thexaero** [comment]
This is not really a bug. It's not supposed to check parties there.
If that was the case, then Welic would be able to let other players build or place something in Welic's claim that would later affect Wayder's claim.

**Comment by GitJhopa** [comment]
very confusing commands like /openpac-parties , it would be nice to see things much simpler like in WorldGuard.

**Comment by GitJhopa** [comment]
I use the command /openpac-parties ally add and somehow it works strangely that players from other groups can break other people's privates, I don't know how it works, it's very confusing both for me and for my players

**Comment by GitJhopa** [comment]
Previously, there were adequate commands / rg addowner / rg addmember / rg removeowner / rg removemember and that's it, no hemorrhoids

**Comment by thexaero** [comment]
You can't add anyone to a claim. You keep calling it that. That's where your confusion is.
Each player has their own claims. Parties are a separate feature.
If you are in a party, you can open your claims to your party members and allies or make exceptions. You don't have to own the party. You don't have to open your claims to your party members or allies either.
I have absolutely nothing to do with whatever mod you were previously using that has those commands.

**Comment by GitJhopa** [comment]
Is it possible to somehow add a person to the region so that he does not press the consent button? Just write a team and that's it, without his consent

**Comment by thexaero** [comment]
Nobody is being "added to a region". Such a thing does not exist in this mod.

`/openpac-parties ally add` adds an ally party to your party. There is nothing confusing about that. If you have members in your party that open their claims to party allies, then whoever you added will get access to their claims. They have already consented. It is disabled by default.

**Comment by GitJhopa** [comment]
How to add only one player? For him to use?

**Comment by thexaero** [comment]
`/openpac-parties member invite` adds a player to your party, not to your region.
If you are a regular member in party, you can't add other members. Only party moderators can. 

If you want to play in a way where every player has their own player/friend list, then every player should create their own party and add other 1-player parties with `/openpac-parties ally add`. Stop the server and set the `maxPartyMembers` to 1 in the main config file so that nobody can add people without consent.

**Comment by thexaero** [comment]
I am planning to add personal player lists as a separate feature unrelated to parties.

**Comment by GitJhopa** [comment]
> I am planning to add personal player lists as a separate feature unrelated to parties.

nice. this needed.
