### ISSUE TITLE
[BUG] I'm writing to supplementaries:bomb, supplementaries:blue_bomb

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#293]
I'm writing to supplementaries:bomb, supplementaries:blue_bomb

I made a barrier as you wrote, and also banned it inside the region, but it didn’t work, since they are needed in PVP regions, there’s no way without them, but they break grass, flowers and crops of players in a foreign region.

**Comment by thexaero** [comment]
Enable them only in the pvp regions.

**Comment by GitJhopa** [comment]
Okay, i go to write to the Supplementaries developer so that he adds a hook to your mod

**Comment by thexaero** [comment]
You don't need to do that.

**Comment by thexaero** [comment]
You can enable/disable barriers and exceptions in specific claims.

**Comment by GitJhopa** [comment]
He then helped me with the Flan privates mod, he was able to implement bomb protection

**Comment by GitJhopa** [comment]
> You can enable/disable barriers and exceptions in specific claims.

I don't need this obfuscation! The players won't do it! Many do not even know about the management of privates, they privatized, turned off pvp and forgot. You just need to make sure that the bombs do not break grass and crops in foreign regions.

**Comment by thexaero** [comment]
There is no obfuscation. You can make the barrier enabled and exception disabled by default with no ability to toggle for players. You will still be able to enable it in the pvp claims, which I assume are server claims or wilderness.

**Comment by thexaero** [comment]
Ideally, mods should fire Fabric/Forge events when they affect things which would prevent all issues with no explicit support from me, but you can definitely get it working with just the config.

**Comment by thexaero** [comment]
And if you're talking about pvp claims set up by the players, then they can definitely figure out how to toggle things. 
This isn't even about pvp protection, it's about protecting blocks. They're not going to think "I'm done" when they toggle pvp off. If they do, it's on them.
It's interesting how much you're expecting from a claim mod to work out the box in a heavily modded environment with no thinking needed. You are never going to run out of things like this, and you're not the only user. I'm not planning to add explicit support for 1000s of mods.

**Comment by GitJhopa** [comment]
I heard you, I'm sorry, it's okay. I'll try to resolve the issue with the Supplementaries developer to add support.

**Comment by thexaero** [comment]
Had a quick look at their code and I think they are firing the correct event on Forge. Are you playing on Fabric?

**Comment by GitJhopa** [comment]
Forge bro

**Comment by thexaero** [comment]
Interesting. What Minecraft version and what Supplementaries and Moonlight Lib version?

**Comment by GitJhopa** [comment]
1.19.2 Forge
latest moonlight lib and latest Supplementaries for 1.19.2

**Comment by thexaero** [comment]
That's strange. It looks like it should be protected then. Is OPAC block protection from explosions in claims definitely enabled by default on your server?

**Comment by GitJhopa** [comment]
yes

**Comment by thexaero** [comment]
Regular TNT next to a claim is fine?

**Comment by GitJhopa** [comment]
Dynamites don't blow up regions, creepers don't blow up either. But bombs from Supplementaries break crops and grass.

**Comment by thexaero** [comment]
Alright, let me test myself, because it definitely looks like it should work. One moment.

**Comment by GitJhopa** [comment]
Ok bro

**Comment by thexaero** [comment]
Oooh. I think Supplementaries simply has a bug. They are not overriding `getToBlow()` with their own block position list in their BombExplosion class, so the Forge event isn't usable for blocks.

**Comment by thexaero** [comment]
Feel free to report this to them.

**Comment by GitJhopa** [comment]
Ok

**Comment by thexaero** [comment]
If this is the only compatibility issue left with that mod, then I don't think explicit support will be needed from me.

**Comment by GitJhopa** [comment]
yes.

**Comment by thexaero** [comment]
I'll report it myself, btw, no need to do it.

**Comment by thexaero** [comment]
Here https://github.com/MehVahdJukaar/Supplementaries/issues/688
