### ISSUE TITLE
Ars Turrets in Claimed Chunks

### ISSUE THREAD

**Issue by katubug** [thexaero/open-parties-and-claims#294]
Hi! First off, thank you so much for making this mod! It's nice to have a claims mod that integrates with Xaero's and doesn't force its own map/death points on users.

Secondly, I do have to admit that it takes quite a lot of tweaking to get everything right! I've had to add exceptions for a lot of things, like Lootr chests and Ars Nouveau turrets. It would be nice if the mod was a little more "out of the box."

So about the turrets. I added the fake player UUID to the config and they can now place blocks, but still cannot break them. The "breakfromother" is set to 0. I'm not sure how else to address this.

Here is my default-player-config: https://pastebin.com/cExMJ3F8

And my openpartiesandclaims-server.toml: https://pastebin.com/jD98iQD7

I also want to know whether it's possible to add players or parties as allies to the server, for public builds and such?

**Comment by thexaero** [comment]
The fake player option should work for everything, including breaking blocks.
Are you sure the blocks to be broken or the turret itself aren't on the very edge blocks of a claim?

**Comment by katubug** [comment]
According to my mod, they were not at the edge of the claim.

**Comment by thexaero** [comment]
Can you test this yourself?

**Comment by katubug** [comment]
Just tested it, and yeah, the Projectile > Break spell fires, but does not break the dirt block in front of it. Nothing of note is produced in the latest.log either.

**Comment by thexaero** [comment]
Please enable chunk grid with F3+G and make a screenshot of the turret and the block to be broken. And before you do that, make sure it still doesn't work.

**Comment by thexaero** [comment]
Although it sounds like the fake player isn't the one breaking the block, it's a projectile. If I had to guess, it probably doesn't have the fake player as its owner either.

**Comment by thexaero** [comment]
Or maybe it does have the owner set and uses it, after looking at their code for a bit.
EDIT: Yeah, I think it should work but doesn't. Placing blocks doesn't either though. Looking into it.

**Comment by thexaero** [comment]
Ok, I know what's wrong. Basically, fake players, for some unknown reason have to be very difficult when it comes to providing their position. There are several ways to get the position and for some reason they can never all return the same one when they clearly should. 
Usually, when a position is incorrect it is exactly (0, 0, 0), so the mod knows to try a different method. In the case of AN, one of the methods returns something completely random, so the mod assumes it is correct. 
Luckily I might have a way to fix this.

**Comment by thexaero** [comment]
As for your other question, the server itself can't have a party. You'll have to temporarily use normal claims for that.
There is a permission node that gives regular players access to server claim mode though.

**Comment by katubug** [comment]
Thank you for figuring this out, and for your response regarding the server ally thing. I appreciate you!
