### ISSUE TITLE
Crashing when joining singelplayer me.lucko.fabric.api.permissions.v0.Options

### ISSUE THREAD

**Issue by SHXRKIEgg** [thexaero/open-parties-and-claims#296]
Hi, when trying to join singelpalyer in my modpack OPAC seems to crash the instant after it loads the world.
Crash https://pastebin.com/Q8SyQiUW

**Comment by SHXRKIEgg** [comment]
seems like reverting to b0.17.5 fixes it

**Comment by thexaero** [comment]
I guess the Fabric Permissions API only introduced the options/metadata API that I'm using in 0.2 and the version that spark still embeds is 0.1.
The simplest thing to do is to download 0.2 and include it in your modpack: https://github.com/lucko/fabric-permissions-api/releases

**Comment by SHXRKIEgg** [comment]
It for a modpack to release so cant add mods not on the platform, will keep it reverted

**Comment by thexaero** [comment]
You should be able to include that mod as a jar because it's licensed under MIT. That's why people can embed it.

**Comment by thexaero** [comment]
Your second option is to ask spark devs to update it.

**Comment by SHXRKIEgg** [comment]
so removing spark fixes it?

**Comment by thexaero** [comment]
Yes, but I assume you want to use that.

**Comment by SHXRKIEgg** [comment]
I used it for testing, so will just remove and update the mods. Thanks
