### ISSUE TITLE
Change Fabric Permission API detection to ignore 0.1

### ISSUE THREAD

**Issue by thexaero** [thexaero/open-parties-and-claims#297]

**Comment by HaXrDEV** [comment]
Possibly related. I keep getting a crash related to Fabrics Permission API on 1.19.2 when loading into singleplayer.

Mod version: open-parties-and-claims-fabric-1.19.2-0.19.0

Crash-log: https://mclo.gs/xafq2qT

**Comment by thexaero** [comment]
Install Fabric Permissions API 0.2.
