### ISSUE TITLE
Can i remove permissions from players to protect and forceload their claimed chunks?

### ISSUE THREAD

**Issue by Hayaomushi** [thexaero/open-parties-and-claims#302]
We building a private minecraft server. So we need players to be able to claim their territory, but this was only a cosmetic option on the map and that all other players that are not in the party can freely interact with the selected regions, and the owners of this regions can`t enable protecting flags.
It`s need just to leave all the functionality of the minimap (displaying allies on it), as well as claim chunks just for hilghlighting territory.

**Comment by thexaero** [comment]
Read the FAQ on the CurseForge or Modrinth pages.
