### ISSUE TITLE
Question about server claims!

### ISSUE THREAD

**Issue by pokesmells** [thexaero/open-parties-and-claims#304]
Can you have server claims on for spawn/Ops but turn them off for players?

**Comment by thexaero** [comment]
What does "on" mean here?

**Comment by pokesmells** [comment]
> What does "on" mean here?

To elaborate, have the claim functionality for server claims, but disable claim functionality for regular players

**Comment by thexaero** [comment]
Just set maxPlayerClaims to 0. Server claims are not affected by it.
If you want some ranks/players to still have personal claims, then use permissions or give them bonus claims in their player config.

**Comment by pokesmells** [comment]
Thank you very much I greatly appreciate it :D
