### ISSUE TITLE
Crash creating new singleplayer world

### ISSUE THREAD

**Issue by ghost** [thexaero/open-parties-and-claims#305]
latest log
[latest.log](https://github.com/thexaero/open-parties-and-claims/files/12003852/latest.log)

crash report
[crash-2023-07-10_09.37.40-server.txt](https://github.com/thexaero/open-parties-and-claims/files/12003855/crash-2023-07-10_09.37.40-server.txt)

Yea I have quite a bit of other fabric mods active, they are listed in the log & report

**Comment by thexaero** [comment]
Same as #296
