### ISSUE TITLE
I cannot sit on seats in a foreign region, although I added them to the list of allowed blocks.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#306]
I cannot sit on seats in a foreign region, although I added them to the list of allowed blocks.
![image](https://github.com/thexaero/open-parties-and-claims/assets/86250668/22e25481-3c59-4a4c-8a70-b07eae4e9951)

**Comment by GitJhopa** [comment]
forcedBlockProtectionExceptionList = ["anything$create:red_seat"]

**Comment by thexaero** [comment]
If you read the message you would see that it's an entity, not a block.

**Comment by thexaero** [comment]
And you're probably using the wrong ID too.

**Comment by thexaero** [comment]
Just realized that this is a contraption. They are protected as a whole as a single entity, not each block separately. You are not really interacting with blocks. I have no plans to change how this works.
