### ISSUE TITLE
hello. please add support mod L_Ender 's Cataclysm

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#307]
https://legacy.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm Please add mod support, as there are items through which you can grab and pull from regions. Thank you!

**Comment by GitJhopa** [comment]
no interesting.

**Comment by thexaero** [comment]
No interesting?

**Comment by GitJhopa** [comment]
yes bro

**Comment by GitJhopa** [comment]
The mod is complete nonsense for the server, not worth the attention to fix it

**Comment by GitJhopa** [comment]
https://github.com/thexaero/open-parties-and-claims/issues/279 i wait this fix, very needed.

**Comment by thexaero** [comment]
Alright, I see.
