### ISSUE TITLE
[Suggestion] support for modular routers

### ISSUE THREAD

**Issue by ianm1647** [thexaero/open-parties-and-claims#309]
The use of modular routers in claimed chunks does not work, ftb chunks has a feature to give the modular routers chunk perms, i didnt know if the same thing was possible here.

**Comment by thexaero** [comment]
Haven't used it but at first glance seems like a case of "static" fake players, which you can configure in the main config file.
Please read through the comment above that option.

**Comment by thexaero** [comment]
The fake player name seems to be "[Modular Routers]".

**Comment by ianm1647** [comment]
okay thank you, ive looked further into modular routers as well, and i found a security upgrade that makes the router act as the player

**Comment by thexaero** [comment]
I see, yeah I saw that in their code too. Wasn't sure how accessible that was.
