### ISSUE TITLE
[Feature Request] Limit spam to privates (chunk's claim's) on servers with 100+ online

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#311]
Having 100+ online players on the server, I ran into the problem that 1 player has about 64 private chunks and he scatters these chunks around the map in different places and prevents other players from building. I have an idea, could you add a function that if a player puts 1 region block (chunk) then he can privatize the next chunks only if they connect with the first one? To avoid spam by the number of regions. Or, for example, add a command and a button that could private 8x8 chunks from the place where the player stands or so that you can specify the amount, for example, the player found a place for the house and he has access to the team. / rg claim and automatically from its place where it stands, the chunks themselves are privatized 8x8 or 10x10 (can be specified in the config) and to delete these chunks, you can write / rg delete - and they are cleared. I think this will solve the problem with private chunk spam all over the map.

**Comment by GitJhopa** [comment]
I don’t know how to explain it to you more precisely, but just think, please, how can you get rid of private chunk spam all over the map? For example, in the WorldGuard plugin, you can limit the number of regions for a player, he cannot privatize 1-2 chunks 100 times.

**Comment by GitJhopa** [comment]
I would see a solution to this problem by disabling privatization and deletion of chunks through Xaero'sWorldMap, but only viewing them there. I would give rights to the number of regions to some donation groups, for example, a player may have the right to create 1 region with limits of 64 chunks. For example, a player is looking for a place for a house, stands in the middle and writes /rg claim and the region is automatically privatized from its 8x8 positions (64 chunks), and to delete it, he can simply write /rg delete and it will be deleted, this will solve the problem by spamming private chunks.

**Comment by thexaero** [comment]
I'll look into it. #312 
Seems complicated though.
