### ISSUE TITLE
mod is supposed to support argonauts but it does not

### ISSUE THREAD

**Issue by S0apyy** [thexaero/open-parties-and-claims#313]
so when i try to start my server with argonauts and open parties and claims the server crashes when loading the world, wich im guessing is not supposed to happen

crash log:
[crash-2023-07-16_22.56.43-server.txt](https://github.com/thexaero/open-parties-and-claims/files/12065070/crash-2023-07-16_22.56.43-server.txt)

Edit: forgot to mention but the mod version i used was: 1.20.1 0.19.0 for fabric
Edit 2: forgot to mention it also happens when trying to load in a singleplayer world

**Comment by thexaero** [comment]
Thanks for reporting!
I need to update it to support 0.1.0.
