### ISSUE TITLE
Create Deployer in claim invokes crash

### ISSUE THREAD

**Issue by Romaq** [thexaero/open-parties-and-claims#314]
Environment:
  fmlloader-1.20.1-47.1.28.jar
  Create 0.5.1d (Forge)
  OPaC 0.19.0

Instructions: With only those two mods, claim an area, and in creative place a deployer into the claimed area.

Key start of error:
`[17:32:35] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: 'void net.minecraftforge.event.entity.EntityEvent$Size.setNewEyeHeight(float)'
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.simibubi.create.content.kinetics.deployer.DeployerFakePlayer deployerHasEyesOnHisFeet(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
java.lang.NoSuchMethodError: 'void net.minecraftforge.event.entity.EntityEvent$Size.setNewEyeHeight(float)'
`

`[17:32:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23132!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
`

My suspicion is "OPaC" sees the "fake player" introduced by the deployer and freaks out with an unhandled exception.

This bug was originally found in a modded game played in survival, and no other aspect of Create appears to have interfered with OPaC.

**Comment by thexaero** [comment]
Did you test without OPAC? This doesn't look related.

**Comment by Romaq** [comment]
You are correct, my apologies. I should have done more thorough testing.

**Comment by Romaq** [comment]
https://github.com/Creators-of-Create/Create/issues/5132#issuecomment-1636772787

This is just an FYI post in case someone encounters this here. The next comment, "nope, nothing to do with OPAC"
