### ISSUE TITLE
Trying to load a world with version 1.20.1 0.19.0 fabric crashes the game

### ISSUE THREAD

**Issue by S0apyy** [thexaero/open-parties-and-claims#315]
Hi me again, weird bug but apperantly loading a singleplayer world without argonauts on the newest version of the mod, also crashes the game. it however does not crash servers weirdly enough.

Crash report: [crash-2023-07-17_22.02.59-server.txt](https://github.com/thexaero/open-parties-and-claims/files/12073512/crash-2023-07-17_22.02.59-server.txt)

**Comment by thexaero** [comment]
Same as #296
