### ISSUE TITLE
[Question] Party owner takes over claims

### ISSUE THREAD

**Issue by TheStarlessBandit** [thexaero/open-parties-and-claims#316]
This is a similar question to #166 , In context i am working on a modded server, and it would've been nice if there was a feature in the main server config, where when someone creates a party and invites another player, that player looses his ability to claim but the party owner gains more claims, as in 1 giant claimed base under a single party instead of 5 people individually claiming part of a base.
(I limited the claim limit for reasons)

**Comment by TheStarlessBandit** [comment]
Basically, Claims would scale per person and what i was meant to ask in the first place. Any updates on #166 ?

**Comment by thexaero** [comment]
A system like this is very easy to abuse by joining and leaving parties. You're basically giving players a way to increase their claim limit for no reason. When a player leaves a party, the mod can't just unclaim random chunks already claimed under a higher limit.

It's the reason why I didn't make claims belong to parties to begin with. It is not a good system.
I am planning to add an option for it, but I'm still not a fan.

**Comment by thexaero** [comment]
I am not planning to add claim limit adjustments based on party size. People will keep the ability to claim as themselves with an option to claim as the party.
