### ISSUE TITLE
bug 1.19.2 Forge - savage_and_ravage:wand_of_freezing give freeze effects in other's region

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#318]
bug 1.19.2 Forge - savage_and_ravage:wand_of_freezing give freeze effects in other's region

**Comment by GitJhopa** [comment]
Mod: https://legacy.curseforge.com/minecraft/mc-mods/savage-and-ravage

**Comment by GitJhopa** [comment]
and can destroy entity (item_frame)

**Comment by thexaero** [comment]
Stop reporting every single mod in existence as a bug.
