### ISSUE TITLE
Carpet fake player bypass protect

### ISSUE THREAD

**Issue by yoku0206** [thexaero/open-parties-and-claims#322]
How should I make the fake player of the carpet ignore protection

**Comment by thexaero** [comment]
Can the fake player move around or is it tied to a block position where you place something?

**Comment by yoku0206** [comment]
I think so fake player can move around

**Comment by thexaero** [comment]
In that case, you can't add an exception for such a fake player. If there's a way to get it to use your player UUID, then that would bypass protection.
