### ISSUE TITLE
Separate Block breaking and block clicking 

### ISSUE THREAD

**Issue by Mintymits** [thexaero/open-parties-and-claims#323]
Is there a way to set up the permissions so that a player can right-click and interact with blocks but not break anything?

**Comment by thexaero** [comment]
Yes, but why would you even want all blocks to be usable? Right-clicking some blocks pretty much breaks them and people will be able to place items the use of which is allowed.

**Comment by Mintymits** [comment]
on my server, i have a spawn area which i want to be protected from block breaking, and i set up a shop with vending machines using the lightman's currency mod    so i want people to only be able to right-click  on things in that chunk but not break anything

**Comment by thexaero** [comment]
Configure an exception for vending machines, not all blocks.

**Comment by Mintymits** [comment]
how do i do that ?

**Comment by Mintymits** [comment]
I want to be able to have a shop where people can not destroy any blocks but they can Click on things and interact.

**Comment by thexaero** [comment]
It's all explained in the main config file.
