### ISSUE TITLE
[Feature Request] Limit on the creation of regions (claim's chunks in region map)

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#324]
Add a claim chunk limitation function, for example, about 100+ players play on my server and each one privates 1-2 chunks in different places, it infuriates. They protect themselves so much from the pvp mode, if they are killed, I would like them to be able to have 1 region, that is, if they privatize 1 chunk, then they can privatize the rest of the chunks only from hooking from 1 chunk, so that there is a limit on the creation of regions. That is, if a player has privatized 1 chunk in his territory, then he can privatize the rest of the remaining chunks only from the first chunk where he installed it, in another place he will not be allowed to do this until he completely removes the private from the chunks.

**Comment by thexaero** [comment]
Stop making duplicate suggestions. Very annoying.

**Comment by GitJhopa** [comment]
Sorry, I forgot that I already created it)

**Comment by thexaero** [comment]
You do this all the time. It happened for other suggestions where you kept spamming the same thing. You're not forgetting anything, you're just rude.

**Comment by GitJhopa** [comment]
I honestly forgot, I create issues in many places and I can forget, sorry.

**Comment by thexaero** [comment]
I could believe you this time but that doesn't explain spamming for other suggestions with little time in-between posts/comments. That doesn't make me address the issue faster, trust me.
