### ISSUE TITLE
Random crashes every day on dedicated server.

### ISSUE THREAD

**Issue by dandaifuku** [thexaero/open-parties-and-claims#325]
Can you let me know if this crash pertains to this mod? I don't understand how to read crash reports but I saw open-pac in there. The server will crash once every other day or so. I hope you can help! Thank you! 

[crash-2023-08-05_14.45.20-server.txt](https://github.com/thexaero/open-parties-and-claims/files/12268207/crash-2023-08-05_14.45.20-server.txt)

**Comment by thexaero** [comment]
It's a Watchdog crash.
Here's info about it: https://help.ggservers.com/en-us/article/what-is-watchdog-and-why-does-it-crash-my-server-n8aex/

**Comment by dandaifuku** [comment]
Thank you!!
