### ISSUE TITLE
Create Belt cant throw item through Nether Portal

### ISSUE THREAD

**Issue by VaitoSoi** [thexaero/open-parties-and-claims#328]
I'm working on an Andesite Farm in Create Back to Track modpack. When I try to toss the lava bucket through the portal in my claim chunk using Mechanical Belt, nothing happens, the bucket just goes through the portal but not to the overworld.

I am very sorry if I confused you because my English is quite bad.

Modpack: Create Back to Track v1.2.3
Minecraft: 1.18.2
Forge: 40.2.9

**Comment by thexaero** [comment]
Make a new sub-config in your player config, turn off nether portal protection from items and claim the chunk that the nether portal is in with the new sub-config.

**Comment by VaitoSoi** [comment]
It work. Thank you so much. Sorry for the late response.

**Comment by thexaero** [comment]
Great! No problem.
