### ISSUE TITLE
[FEATURE REQUEST] ability to view chunks in subclaims and server claims.

### ISSUE THREAD

**Issue by astxr22** [thexaero/open-parties-and-claims#331]
e.g. the command "/openpac-claims about server spawn" would give info about the chunks in the subclaim "spawn" in the server claim.

**Comment by thexaero** [comment]
This is basically #231

**Comment by thexaero** [comment]
Unless that's not what you mean?

**Comment by astxr22** [comment]
i was thinking more about the _amount_ of chunks in a certain claim, but that suggestion looks like that would include that info

**Comment by thexaero** [comment]
Gotcha, I'll close this then.
