### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by celophys** [thexaero/open-parties-and-claims#332]
With the last 1.19.2 fabric update, some random players claims are not protected, even if the server options say that everyone claim is protected against players

**Comment by thexaero** [comment]
Server options say that in what way exactly?

**Comment by celophys** [comment]
![2023-08-17_22 19 49](https://github.com/thexaero/open-parties-and-claims/assets/84269120/66431eee-86c1-433d-ae2e-1e759b77a21f)
These are the server default options, the players cant change them (sorry i am not english)

**Comment by celophys** [comment]
for no reason, players' claims lose their protection

**Comment by thexaero** [comment]
That's not specific enough. I can't do anything with this information. Your players probably don't understand how parties work, if I had to guess. I'm seeing this a lot.

**Comment by celophys** [comment]
the point is that i disabled the modification of the settings of the claims for all the players, they can't modify them. but often without reason the claims become destructible by everyone

**Comment by thexaero** [comment]
I don't think that's true. They probably become destructible by new party members.

**Comment by celophys** [comment]
No, all the players can destroy them, not only ally and party members.  I've been looking for the solution for days but I can't figure it out. I also turned off expired claims


https://github.com/thexaero/open-parties-and-claims/assets/84269120/d7e03d7d-c58f-4fed-9a56-7060d5aab5f9

**Comment by celophys** [comment]
for now the only thing I understand is that the problem concerns some random players, even if they are part of a party, their personal claims are not protected in any way

**Comment by thexaero** [comment]
Please do `/openpac-parties about` and send me a screenshot.

**Comment by celophys** [comment]
![2023-08-18_13 51 02](https://github.com/thexaero/open-parties-and-claims/assets/84269120/b263d9bc-5e54-481e-a5ae-ddd63553f7fb)

![2023-08-18_13 51 26](https://github.com/thexaero/open-parties-and-claims/assets/84269120/562d27db-b2f7-42f4-8636-146e562b98f4)

**Comment by thexaero** [comment]
Are you wolf218?

**Comment by celophys** [comment]
no, he is a random player from my server, but many others also have the same problem

**Comment by thexaero** [comment]
Did you do just `/openpac-parties about` without any name?

**Comment by celophys** [comment]
No, i did /openpac-parties about wolf218

**Comment by thexaero** [comment]
Ok, please do just `/openpac-parties about`.

**Comment by thexaero** [comment]
Please also send me a screenshot of your FTB Teams party.

**Comment by celophys** [comment]
![2023-08-18_13 56 51](https://github.com/thexaero/open-parties-and-claims/assets/84269120/e8330d7a-4015-49bd-ae5a-761dedf672dd)

![2023-08-18_13 57 12](https://github.com/thexaero/open-parties-and-claims/assets/84269120/3ce4e60b-fec4-4c7f-bc3e-04a53255b002)

**Comment by thexaero** [comment]
Thanks! Interesting. Do you have any other party systems?

**Comment by celophys** [comment]
No, only Open Parties and Claims and ftb teams, but in the config file i set this
primaryPartySystem = "default"
permissionSystem = "luck_perms"

**Comment by celophys** [comment]
[configCLAIMS.zip](https://github.com/thexaero/open-parties-and-claims/files/12379002/configCLAIMS.zip)
I send the server default config

**Comment by thexaero** [comment]
Thanks. Please take a screenshot of wolf218's player config.

**Comment by celophys** [comment]
Thank you for the help, here wolf218's player config is is correct, it says that the claim is protected and all options are the same as the default ones

![2023-08-18_14 03 48](https://github.com/thexaero/open-parties-and-claims/assets/84269120/f77aba0a-a31c-4373-8660-56b94400d4c2)
![2023-08-18_14 03 49](https://github.com/thexaero/open-parties-and-claims/assets/84269120/b7e1b834-c2a5-4bee-83f6-76c706516716)
![2023-08-18_14 03 51](https://github.com/thexaero/open-parties-and-claims/assets/84269120/aaceff1e-3a0e-48c8-8ad8-eabcf3b92cc9)

**Comment by thexaero** [comment]
So strange. What OPAC version exactly is this?

**Comment by thexaero** [comment]
And FTB Teams version too.

**Comment by celophys** [comment]
open-parties-and-claims-fabric-1.19.2-0.19.2

ftb-library-fabric-1902.4.1-build.236
ftb-teams-fabric-1902.2.14-build.123

**Comment by thexaero** [comment]
Thanks! And please check if turning on "Protect From Ally Parties" or "Protect From My Party" in the default config changes anything. First separately and then both.

**Comment by celophys** [comment]
ok i tried both, but nothing changes

**Comment by thexaero** [comment]
Were you changing it using the in-game screen?

**Comment by celophys** [comment]
yes

**Comment by thexaero** [comment]
And you could still break wolf218's blocks?

**Comment by celophys** [comment]
yes, the same goes for some other players' claims

**Comment by thexaero** [comment]
That doesn't make sense. It means that the mod thinks you're wolf218, if both "Protect From Ally Parties" and
 "Protect From My Party" are turned on.

**Comment by celophys** [comment]
yes, but not only i, all the players can break the wolf218 claim (as well as other players having this bug)

**Comment by thexaero** [comment]
Can you record turning "Protect From Ally Parties" and
"Protect From My Party" on and then breaking blocks in wolf218's claim? Very hard to believe.

**Comment by celophys** [comment]
https://github.com/thexaero/open-parties-and-claims/assets/84269120/abbaf3e0-fc17-4068-91f3-b7a83a5253ba

**Comment by thexaero** [comment]
Thanks! Ok, this is very strange. Now it shows you their claim in red, which means you shouldn't be able to break anything but you still can.

**Comment by thexaero** [comment]
What's strange is that the mod literally uses the same exact method to determine message color as for interaction checking.

**Comment by celophys** [comment]
do you want to try the server? the modpack is called "Regno di Craftia" on curseforge

**Comment by thexaero** [comment]
Ok, I just realized something. It can still be due to mod thinking you're allies or the same party. You have everything set to "Not Ally". You didn't have to do that. Try setting "Protect Blocks From Players" to "Not Party" and let me know if you can still break blocks. Next test it at "Every".

**Comment by thexaero** [comment]
Oh, and turn on "Protect From Ally Parties" and "Protect From My Party" again.

**Comment by celophys** [comment]
ok this worked thanks!! now i cant break blocks and interact, but now ally players can no longer interact right ?

**Comment by thexaero** [comment]
Alright, thanks for confirming! 
So it is because of some installed party mod after all. My mod only supports FTB Teams and Argonauts by default though. I'll go test the mod pack and let you know what I find.

**Comment by celophys** [comment]
Thanks for all, the server will work fine!

**Comment by thexaero** [comment]
Btw, did it work with "Not Party"?

**Comment by thexaero** [comment]
I wanted to know where it was specifically.

**Comment by thexaero** [comment]
And yes, there is still an issue because party members can't interact with each other's claims.

**Comment by celophys** [comment]
now i have every option to "not party" and all works fine, party members can build 
![Desktop Screenshot 2023 08 18 - 15 35 59 74](https://github.com/thexaero/open-parties-and-claims/assets/84269120/4f221cbc-6e6a-40ff-bf63-68dd0b08fa41)

![Desktop Screenshot 2023 08 18 - 15 35 54 96](https://github.com/thexaero/open-parties-and-claims/assets/84269120/b4e7bfde-c442-40c7-abd8-6e4f9ea3aaa1)

**Comment by thexaero** [comment]
I see. And if you turn off "Protect From Ally Parties" it lets you break things again, right?

**Comment by celophys** [comment]
yes exactly

**Comment by thexaero** [comment]
Are you sure wolf218's FTB team doesn't have you as an ally? That would make this make sense and not be a bug.

**Comment by celophys** [comment]
Yes, wolf218 is just a random player i chosed for this test, but also a lot of other players have this bug, but now it is fixed

**Comment by thexaero** [comment]
If wolf218's FTB team has you as an ally, then it's not a bug. The same can be true for the other players.

**Comment by celophys** [comment]
no, he is not my ally in ftb team, I don't have a ftb team (but as i said before, not only could i break blocks, any other player could do it)

**Comment by thexaero** [comment]
You don't have to add wolf218 as an ally or accept anything. If wolf218's team adds you as an ally (not a member), then you are his ally. With the old config, that would let you break their blocks.

**Comment by celophys** [comment]
I know, he didn't add me to the team as ally

**Comment by thexaero** [comment]
Are you sure? I really need to know if this is a bug or not.

**Comment by celophys** [comment]
yes

**Comment by thexaero** [comment]
That is very strange, because I'm almost certain that when my mod asks FTB Teams if you are wolf218's ally, it says yes.
Pretty sure it only does that for allies and invited players.

**Comment by thexaero** [comment]
Could be a FTB Teams bug, but I doubt it.

**Comment by celophys** [comment]
the player wolf218 confirmed to me that he never added me as an ally (he didn't even know it could be done). the point is that some players (for example wolf128) had the claim unprotected, and anyone (not just me) could break the blocks. I doubt it some random players added every single player on the server as allies.

**Comment by thexaero** [comment]
How are you sure that absolutely anyone can do it? Can wolf218 send you screenshots of his allies and invited players?

**Comment by celophys** [comment]
I tried teleporting some random players to try if they could break blocks, and they could. Antway how can we see our allies with ftbteams?

**Comment by thexaero** [comment]
Open the FTB Teams screen and there should be tabs for that.

**Comment by thexaero** [comment]
I believe you but I want to make absolutely sure.

**Comment by thexaero** [comment]
You know what. Maybe it's that they set their party "open for all" or whatever it's called. Can you ask them?

**Comment by thexaero** [comment]
You obviously wouldn't expect any protection if you do that. Anyone can join your party anyway.

**Comment by celophys** [comment]
![20230818_161947](https://github.com/thexaero/open-parties-and-claims/assets/84269120/1ae8dedb-d0cf-4409-8728-8f1a16608db0)
![20230818_161931](https://github.com/thexaero/open-parties-and-claims/assets/84269120/b00e5cef-71c3-4fe8-976a-b6c6edf750e8)

**Comment by thexaero** [comment]
I just tested it and "Free to Join" does in fact cause every player to be an ally. But of course they don't have that enabled. I don't know if they did an hour ago though.

**Comment by thexaero** [comment]
Anyway, thanks for all the information. I won't bother you anymore with this, even though I still don't know what caused it.

**Comment by celophys** [comment]
thanks you for all
