### ISSUE TITLE
Two questions about the commands and the server

### ISSUE THREAD

**Issue by RockZe** [thexaero/open-parties-and-claims#333]
The first question: is it possible to somehow add a team that will add chunks to those already available to the player? Issuing chunks through bonus ones will recreate the existing chunks. For example, a player has 100 and issuing 50 chunks through bonusclaim, he gets not 150 chunks, but 50. Is there a team that works differently?

The second question: is it possible to make OPaC commands be applied from the console? At the moment, it is required to enter a command from the player, but this makes it very difficult to interact with players on the server

**Comment by thexaero** [comment]
1) I have no idea what any of this means. 50 bonus claims with the 100 default gives the player 150 claims, not 50.

2) It is possible for anything that isn't related to the player using the command. Minecraft already supports calling commands as another player, if you need to.

**Comment by RockZe** [comment]
1. I mean that it is impossible to automate the receipt of chunks. For example, 1 command that will always give +100 chunks. Maybe I missed and there is such a command?

2. Hmm, I didn't know that you can call commands on behalf of the player through the console. I'll try, thanks!

**Comment by thexaero** [comment]
1. Oh, gotcha. I am already planning to add that.
2. Yep, it's done through "execute as". Only works for online players though.

**Comment by RockZe** [comment]
1. Oh, it's going to be just wonderful! I'm looking forward to it, thank you!
2. Got it, thanks for the help!

**Comment by thexaero** [comment]
No problem!

**Comment by RockZe** [comment]
And can I ask you to please let me know here when you add what you planned in paragraph 1.? I try to review all the changes of each version, but to be honest I'm already a little confused :D
