### ISSUE TITLE
Crash with supplementaries overcumbered effect (having too many sacks) 

### ISSUE THREAD

**Issue by Looxond** [thexaero/open-parties-and-claims#335]
So me and another guy had the same issue and we think it may do with openpac however just case im attaching the log here and a vid

[Crash goes here](https://mclo.gs/iglN4IL)

https://youtu.be/778LOmfvrgE

**Comment by thexaero** [comment]
I don't think it's related to OPAC. Please test without it to confirm.

**Comment by thexaero** [comment]
It has to be a mod that affects jumping it seems.

**Comment by Looxond** [comment]
yeah it seems its a forge issue with supps, the other guy had claimed this mod was at fault so i reported it here just in case

Sorry for wasting your time
