### ISSUE TITLE
Open Claims and Parties Advice

### ISSUE THREAD

**Issue by taintedvalor** [thexaero/open-parties-and-claims#336]
I am reaching out here since there doesn't seem to be an official Discord channel, and I need some assistance with the Open Claims and Parties mod. I have a few queries and issues that I'd like to address:

**1. Excluding Items from Protection:**
   - How can I exclude specific items from other mods from being protected within player claims and server claims? Specifically, I have Universal Shops and Waystones installed, and I'd like to exclude all items related to these mods.

**2. Disabling Phasing from Origins:**
   - Is it possible to disable phasing from Origins within a claim? For instance, I'd like to prevent Origins like Phantom from phasing through claim borders while still allowing them to enter the claim.

**3. Disabling Carry-On with External Mobs:**
   - Can I disable the "carry-on" feature for external mobs inside a claim? I want to ensure that mobs from other mods can't be carried by players within the claim.

**4. Enabling Portals for All:**
   - Lastly, how can I configure the mod to enable portals for everyone to access, regardless of the claim they are in?

Any guidance or solutions to these questions would be greatly appreciated. Thank you for your assistance!

**Mod Version:** [b0.19.3]

**Minecraft Version:** [Fabric API 0.76.0+1.19.2]

Thank you for your help in advance.

Best regards,

[valor]

**Comment by thexaero** [comment]
1. The main config file. Stop the server before you edit it.
2. Ask Origins devs to support this mod's claim protection.
3. Probably the same as number 2.
4. Disable portal protection in the default player config and make the option not toggleable in the main config file.
