### ISSUE TITLE
Which setting to enable for only allowing create cart contraptions to break blocks

### ISSUE THREAD

**Issue by Shunigate1** [thexaero/open-parties-and-claims#338]
I'm trying to use a design like [cyvack's cobblestone generator](https://www.youtube.com/watch?v=zOBmCCofEsM) but I don't know which protection I have to disable in order to allow this to work WITHOUT allowing players to simply mine the blocks around the contraption with a pickaxe. 

I've tried Protect Blocks From Mobs & Protect Blocks From Other, but neither seem to allow this functionality to work.

The issue is that instead of breaking the cobblestone as expected, the contraption simply stops moving and separates one of the trap doors from it, due to it being unable to move into the cobblestone to break it.

**Comment by thexaero** [comment]
Make sure none of the contraption is right on the edge blocks of a claim. Try claiming more chunks around it.

**Comment by Shunigate1** [comment]
I own a 3x3 of claimed chunks around it and the claim with the altered permissions in regards to entities being able to break blocks is a subclaim. The contraption is in the middle of that subchunk.

I am on forge 1.18.2

**Comment by thexaero** [comment]
You don't have to change any permissions to allow this to work. It's supposed to work by default.
The mod checks where the "anchor" position of a contraption is when it's disassembled or assembled. Only when it's on an edge of your claim or outside, it'll protect the claim blocks. 
What's actually considered an edge is a bit more complicated and based on sub-claim permissions, but you don't have to worry about that.

**Comment by thexaero** [comment]
Make the whole 3x3 the same claim type to see if it makes a difference.

**Comment by thexaero** [comment]
And make sure what needs to be glued together is still glued.

**Comment by Shunigate1** [comment]
Claiming a 3x3 around the chunk with the contraption seems to have fixed it, thanks :)

**Comment by thexaero** [comment]
I see. Then you must've messed something up in the sub-configs.

**Comment by Shunigate1** [comment]
Possible. What might it have been?

**Comment by thexaero** [comment]
If there are more possibilities to affect blocks in the outer claim than in the inner sub-claim, then it also protects the edge.
