### ISSUE TITLE
[1.20.1] Editing signs is not protected

### ISSUE THREAD

**Issue by LazyDope** [thexaero/open-parties-and-claims#339]
The ability to edit signs that aren't waxed is not protected by claims.

**Comment by thexaero** [comment]
Really?
Thanks for reporting.

**Comment by thexaero** [comment]
Are you sure you didn't make an exception for sign interaction? They're protected for me just fine.

**Comment by LazyDope** [comment]
An exception in the config file, or the config menu? There are no mentions of signs in the config file and I couldn't find an option that affected signs in the config menu either.

**Comment by LazyDope** [comment]
I also seem to have forgotten to mention that this is on the fabric version.

**Comment by thexaero** [comment]
You can make exceptions for any block. That would at least partially be done in the main config file.
If you can post your main config file, I can take a look.

**Comment by LazyDope** [comment]
Ah, I found the issue, someone did make an exception for signs in the config. Sorry for the trouble.

Now I just need to figure out why so I can get rid of it.

**Comment by thexaero** [comment]
I see. Thanks for confirming!
