### ISSUE TITLE
[Request] Economy Tie-In for Claimed Chunks

### ISSUE THREAD

**Issue by deveyus** [thexaero/open-parties-and-claims#34]
I'd love to have a way to pay for claiming chunks, via items or any of the more popular economy mods.  Something like the old Railcraft Chunkloader.  Ideally configurable, of course, as the rest of this mod.

I respect that your time is valuable and would happily contribute to the project for such a feature.

**Comment by thexaero** [comment]
Thanks for the suggestion.
Rather than doing this specifically, I think I'll improve the API to simplify achieving this with a separate addon mod.

**Comment by thexaero** [comment]
Alright, there it is then #35
We can continue the conversation there, if you'd like to add something.
