### ISSUE TITLE
Default Config changes not recognised

### ISSUE THREAD

**Issue by DoctorMage** [thexaero/open-parties-and-claims#343]
Minecraft Version: 1.19.2
Mod Vesion: open-parties-and-claims-forge-1.19.2-0.19.3.jar
Forge: 43.2.6

Edit default player config in defaultconfigs
```
					[playerConfig.claims.protection.exceptionGroups.entity.droppedItemAccess]
						#When enabled, claimed chunk protection makes an exception for dropped item access by the following entities: minecraft:villager. If the dropped item protection is based on the mob griefing rule check, then the claimed neighbor chunks must also allow the item access.
						#
						#1) Party - players or entities owned by players in the same party as you.
						#2) Allies - players or entities owned by players in parties that are allied by yours.
						#3) Every - all players/entities.
						Villagers = 3
```

delete serverconfig folder and let world generate a new one (this is also the same for a newly generated world)

one generated will be as default with no changes
![image](https://github.com/thexaero/open-parties-and-claims/assets/85318453/8c04bb80-8021-4eeb-8918-01c4fd81dd07)

**Comment by thexaero** [comment]
Thanks for reporting!
Does it work for the main config file of the mod?

**Comment by DoctorMage** [comment]
changes in openpartiesandclaims-server.toml
seem to be fine but none of the other config changes are recognised 
![image](https://github.com/thexaero/open-parties-and-claims/assets/85318453/945ac6d1-e5d6-4cfa-8d5f-8b701e6e30ee)

**Comment by thexaero** [comment]
Alright, thanks for confirming!

**Comment by thexaero** [comment]
Seems to be working in all my tests. I don't even remember how server claim forceloading is any different from player claim forceloading besides having unlimited forceloads. I don't think it is any different, which isn't making any sense in regards to this issue. I'll make sure though.
