### ISSUE TITLE
Creative simple shops

### ISSUE THREAD

**Issue by Solanito97** [thexaero/open-parties-and-claims#344]
I cant make this work, i already tried using: forcedBlockProtectionExceptionList = ["anything$simpleshops:creative_simple_shop"]
but didnt work

![2023-09-10_14 15 53](https://github.com/thexaero/open-parties-and-claims/assets/86885570/b79a100f-dde2-4f40-81de-5615cb4f30ef)

**Comment by thexaero** [comment]
Did you stop the server before making this change?

**Comment by Solanito97** [comment]
> Did you stop the server before making this change?

Yeah, I tried that

**Comment by thexaero** [comment]
Please try again.

**Comment by Solanito97** [comment]
It worked now, thanks
