### ISSUE TITLE
Question regarding lecterns and interaction with NPCs from Taterzens.

### ISSUE THREAD

**Issue by Corcustos** [thexaero/open-parties-and-claims#345]
Firstly, I'd like to use lecterns in server builds to relay information, but I couldn't figure out a way to allow interaction with a lectern to read the book while preventing the taking of the book. Is this possible with PAC? I got as far as using `{hand$minecraft:lectern}` to force lecterns to be interacted with a bare hand(to prevent placing books). 

Regarding the NPCs: The created NPCs use the ID minecraft:player, but adding minecraft:player to forced or optional exception groups doesn't seem allow interaction with them. I read that certain modded entities may not work correctly, but I figured I'd see if you had any idea as to if I'm doing something incorrectly. Disabling the blanket entity protection via the menu will allow interaction. Could it be related to exceptions not properly bypassing as mentioned in my [other ticket](https://github.com/thexaero/open-parties-and-claims/issues/346)?

**Comment by thexaero** [comment]
Lecterns is something I should look into. There might be a read-only lectern mod out there that you can use until then.

I assume the NPCs are recognized by the mod as players, so they use the player protection, which works differently. But since adding "minecraft:player" as an exception would affect all players anyway, you can probably get away with turning off "players from players" protection. The NPCs cannot normally be killed, can they?

**Comment by Corcustos** [comment]
> Lecterns is something I should look into. There might be a read-only lectern mod out there that you can use until then.
> 
> I assume the NPCs are recognized by the mod as players, so they use the player protection, which works differently. But since adding "minecraft:player" as an exception would affect all players anyway, you can probably get away with turning off "players from players" protection. The NPCs cannot normally be killed, can they?

Turning off "players from players" doesn't seem to work. Would this mean that minecraft:player isn't the correct ID to be using for these NPCs? Only "Entities from players" seems to work in allowing right-click interaction. I also tried adding their assigned UUIDS under `staticFakePlayers`

**Comment by thexaero** [comment]
What is their ID on the F3 screen?

**Comment by Corcustos** [comment]
> What is their ID on the F3 screen?

![image](https://github.com/thexaero/open-parties-and-claims/assets/15864775/985fbe54-0c36-42c5-8d41-479c71bddaf5)

Says minecraft:player but seems to be affected by entity targeted permissions and not player targeted.

**Comment by Corcustos** [comment]
> > What is their ID on the F3 screen?
> 
> ![image](https://user-images.githubusercontent.com/15864775/269561072-985fbe54-0c36-42c5-8d41-479c71bddaf5.png)
> 
> Says minecraft:player but seems to be affected by entity targeted permissions and not player targeted.

Seems that minecraft:player wasn't the correct ID to target as I suspected. I was finally able to locate it (not displayed in F3). Most of my issues were user-error. Apologies for the confusion and thanks for the help. Just looking for that lectern support now!

**Comment by thexaero** [comment]
You mean that minecraft:player is only the id on the client side?

**Comment by Corcustos** [comment]
> You mean that minecraft:player is only the id on the client side?

Yeah, but they have another ID apparently. I was able to resolve my issue by making an exception for `taterzens:npc` instead of `minecraft:player` despite `minecraft:player` being the only ID shown client-side.

**Comment by thexaero** [comment]
Alright, good to know! I'll close this then.
