### ISSUE TITLE
Can't properly make exceptions for boat and minecart interaction.

### ISSUE THREAD

**Issue by Corcustos** [thexaero/open-parties-and-claims#346]
I'm on the b0.19.3 for Fabric 1.20.1. I have added boats and minecarts to `additionalBannedItemsList` to enable protection against placing them and removed boats from `friendlyChunkProtectedEntityList` while set to ALL_BUT. This results in the expected outcome of both being completely protected by default. Afterwards, I included both in `itemUseProtectionOptionalExceptionGroups` and `entityProtectionOptionalExceptionGroups`. I then toggle them on to enable the exceptions to use(place) boats/minecarts and to interact/break them. However, it seems that the entityProtection group doesn't seem to properly bypass "Protect Entities Fr. Players" the same way the itemUse group bypasses "Protect Item Use". If I disable "Protect Entities Fr. Players, boats/minecarts can then be ridden/broken, but obviously this removes protection on all other friendly entities. It's possible that I misunderstand the way the mod is supposed to be configured, but I couldn't think of any other way to achieve my desired result.

**Comment by thexaero** [comment]
Sounds like it should work. Can you please post the config file?

**Comment by Corcustos** [comment]
> Sounds like it should work. Can you please post the config file?

Sure thing: [https://pastebin.com/zXEUyFfj](https://pastebin.com/zXEUyFfj)

Right now it's just oak boats and minecarts I've been testing with. I've also tried separating them into "break$Boats{minecraft:oak_boat}" and "Boats{minecraft:oak_boat}", the same way the default Crops entityProtection is shown, but that doesn't seem to work either.

**Comment by thexaero** [comment]
That's one of the issues I'm seeing. You can't add prefixes to elements of a group, only to the whole group. You must separate it.
And I'm pretty sure all boat entities are of type minecraft:boat. Only boat items are material specific. You can check entity types on the F3 screen.

**Comment by Corcustos** [comment]
> I'm pretty sure all boat entities are of type minecraft:boat. Only boat items are material specific.

That was my issue. I wasn't aware that the boat entity didn't share an ID with the item. Thank you for the help.

**Comment by thexaero** [comment]
Alright, great, closing this then.
