### ISSUE TITLE
How to add the number of chunks a player has claimed by command?

### ISSUE THREAD

**Issue by windy664** [thexaero/open-parties-and-claims#349]
For example , there're tow players A and B.

We want player A to cliam a maximum of 200 chunks, and player B to claim a maximum of 400 chunks. 

How to operate?

**Comment by thexaero** [comment]
You can give individual players bonus claims in the mod's UI screen or setup permissions, which is explained in the main config file.

**Comment by windy664** [comment]
> You can give individual players bonus claims in the mod's UI screen or setup permissions, which is explained in the main config file.

?????

![image](https://github.com/thexaero/open-parties-and-claims/assets/81475218/163e4230-3abc-45b7-9dae-c4e2e214b74a)
I cannot find it


is it?
`#The number of additional chunk claims that you can make on top of the normal limit.
bonusChunkClaims = 0
#The number of additional chunk claim forceloads that you can make on top of the normal limit.
bonusChunkForceloads = 0
`

However, these settings still appear to be global and not player-specific.

**Comment by thexaero** [comment]
You'd be a lot less confused if you read the mod's description.
https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims

**Comment by windy664** [comment]
![image](https://github.com/thexaero/open-parties-and-claims/assets/81475218/e0326990-2204-41e0-b460-d67f72dd8205)
can set，
but not add????
