### ISSUE TITLE
MCA Fabric mod  (Dupe)

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#350]
https://youtu.be/PGGDo1lHaKc

Mobs from the mod mine wood, coal, and other blocks, but in private they dupe these blocks without breaking them, I tried to ban this but it didn’t work

i'm true
			blockAccessEntityGroups = ["Villagers{minecraft:villager, mca:*}"]

			entitiesAllowedToGriefEntities = ["Villagers{minecraft:villager, mca:*}"]

**Comment by DonorKrovi** [comment]
![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/0389be49-4e5f-41ac-a385-6ab8d07aed96)

**Comment by thexaero** [comment]
Seems like MCA npcs are collecting the blocks even if they can't be broken. They have to fix this on their end. My mod isn't the only thing that can stop a block from breaking.

**Comment by DonorKrovi** [comment]
> Seems like MCA npcs are collecting the blocks even if they can't be broken. They have to fix this on their end. My mod isn't the only thing that can stop a block from breaking.

How, then, to allow them to break blocks in claim?

**Comment by thexaero** [comment]
Please read the comments above options in the main config file instead of asking me. It has examples and everything.

**Comment by DonorKrovi** [comment]
> Please read the comments above options in the main config file instead of asking me. It has examples and everything.

I tried, but I couldn't resolve it
