### ISSUE TITLE
添加一键控制左右建

### ISSUE THREAD

**Issue by wyxznx** [thexaero/open-parties-and-claims#351]
我们是模组服 很多额外模组的右键使用没有单独办法配置 只能关闭整个领地保护 如果能添加一个允许队伍或盟友使用左右建的配置就好了

**Comment by thexaero** [comment]
You can set that up with a block interaction exception group that includes all blocks. Making groups is explained in the main config file.

**Comment by thexaero** [comment]
You also don't want to do that at all. You should setup exceptions for specific blocks. Right click interaction with any blocks is almost as dangerous as breaking them, which is why there is no quick toggle for it.
