### ISSUE TITLE
Claim cost

### ISSUE THREAD

**Issue by quintaneous** [thexaero/open-parties-and-claims#352]
In previous issues you had mentioned adding some sort of claim cost feature, is there still plans to do this?

**Comment by thexaero** [comment]
I never had any plans to add a claim cost feature.

**Comment by quintaneous** [comment]
Were there any forge mods every created that used your api?

**Comment by thexaero** [comment]
Probably. I basically downgraded the priority of an API for implementing things like cost because it's possible to achieve already with bonus claims, e.g. how NumismaticClaim mod does it.
The API improvement already has an issue on the tracker though.

**Comment by quintaneous** [comment]
On the topic of bonus claims, if I were to lower a players claims, they would have more claims than their max. Is there any way for the excessive claims to either expire or be unclaimed entirely?

**Comment by thexaero** [comment]
No, because the mod can't decide the most important claims to keep.

**Comment by quintaneous** [comment]
There is no overclaim feature correct? That goes by adjacent claims

**Comment by thexaero** [comment]
Not sure what you mean exactly. 
Just got an idea for how to deal with players that have claims over the lowered limit: #354

**Comment by quintaneous** [comment]
Did you ever add commands for adding/subtracting, or is set the only option?
