### ISSUE TITLE
Create Dupe

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#356]
1 - Claim of the first player
2 - Claim of the second player

![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/cdeea525-d0f0-4771-a2a7-3fadcddba2c1)

If they are connected by mechanisms, then the mod does not understand where whose private is and if you twist the mechanisms with a wrench, then they stupidly buged and duped, the mod seems to read that the mechanism itself in full length is considered the property of one player.

**Comment by thexaero** [comment]
This is exactly the same as #300 
Tell me which item exactly is being duped here. This isn't happening to every "mechanism", only to things like water wheels, mechanical belts and train tracks. I assume you found another one.

**Comment by DonorKrovi** [comment]
> This is exactly the same as #300 Tell me which item exactly is being duped here. This isn't happening to every "mechanism", only to things like water wheels, mechanical belts and train tracks. I assume you found another one.

https://youtu.be/J8FCevrm-Vk

As I understood, you can do absolutely all the things that are in the game, for example, using an activator in the form of a finger, here is a video for you

Players triggered a block with a shulker with things after which the shaler fell and all the things inside it, on a large scale

**Comment by thexaero** [comment]
Interesting. Thanks for the video!

**Comment by DonorKrovi** [comment]
> Interesting. Thanks for the video!

Always happy to help

**Comment by thexaero** [comment]
Unfortunately, what you showed in the video doesn't work for me. What create version are you using?

**Comment by thexaero** [comment]
Ok, I was able to do this when I configured being able to interact with deployers and using wrenches in other people's claims. It doesn't have to be a part of a mechanism or be on the claim edge.

**Comment by thexaero** [comment]
You should remove those exceptions until the dupe is fixed.

**Comment by thexaero** [comment]
Or, I'm pretty sure if you add another exception for breaking deployers, not just right-clicking, that'll also fix it.
