### ISSUE TITLE
Permission node/player groups

### ISSUE THREAD

**Issue by FormulaAbyss** [thexaero/open-parties-and-claims#357]
I am trying to help a player setup shop plots, however they don't seem to have access to the Party section (top right) of the image below. Also, is there a list of permission nodes available for use with Luckperms?

How can I give them access to this? 
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/34247c4c-e713-4424-afb5-78fbc946bc58)

**Comment by thexaero** [comment]
The party options are only in the "main" player config, which they probably don't have selected.
Has absolutely nothing to do with setting up shop plots.

**Comment by FormulaAbyss** [comment]
Perhaps I'm missing something? How is this option turned on?

**Comment by thexaero** [comment]
It's already turned on. It's not listed when you have any sub-config other than "main" selected, which I'm 95% confident is what's happening to the player you're helping.
It has absolutely no relation to setting up shop plots though.

**Comment by FormulaAbyss** [comment]
I'm confused. each player can only create one party ever?
Wouldn't the point of sub-configs to allow for different permissions based on each plot? For example, if I was to rent a plot to another player, that would require a different party (and permission set), than say my main claim.

**Comment by thexaero** [comment]
Sub-configs allow you to have different claim configs for different claims. That doesn't mean a separate party for each sub-config. That's not a feature and isn't ever going to be. There will be more ways to make exceptions for specific players, not just party-based, in the future but this is definitely not it.
