### ISSUE TITLE
Claims are not deleted after a while and TNT issue

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#359]
I've noticed that players' cmais are not deleted on the server after a specified period of time in the config, and you most likely forgot to add cart protection with tnt_minecart to the mod

**Comment by thexaero** [comment]
TNT Minecart protection works. I don't think you have explosion protection enabled at all or you're talking about a modded TNT Minecart, which doesn't use the Forge explosion event, which often means that it wouldn't be protectable anyway. 
I don't see a reason why claim expiration wouldn't work either. Please provide the main config file.

**Comment by DonorKrovi** [comment]
> TNT Minecart protection works. I don't think you have explosion protection enabled at all or you're talking about a modded TNT Minecart, which doesn't use the Forge explosion event, which often means that it wouldn't be protectable anyway. I don't see a reason why claim expiration wouldn't work either. Please provide the main config file.

https://mclo.gs/FpVxM1E

**Comment by thexaero** [comment]
Thanks! What version of the mod (not Minecraft) are you using? Is the server running 24/7?

**Comment by thexaero** [comment]
Please also send me the default player config.

**Comment by DonorKrovi** [comment]
> Please also send me the default player config.

I apologize for waiting, I have power outages
Here are the settings of all the configs just in case


openpartiesandclaims-expired-claim-config
https://mclo.gs/zEWDEqU

openpartiesandclaims-server-claim-config
https://mclo.gs/ZZU2ChO

openpartiesandclaims-wilderness-config.toml
https://mclo.gs/l0hJHsF

openpartiesandclaims-default-player-config
https://mclo.gs/1FQEvjF

**Comment by DonorKrovi** [comment]
version=0.20.0 Forge. The server works around the clock, sometimes (very rarely crashes), plays about 100+ players

**Comment by thexaero** [comment]
According to your configs, you have protection disabled for "expired" claims and protection from explosions disabled separately, so even turning the main protection option on still wouldn't protect from explosions, whether normal TNT or minecarts. Are those the claims being exploded?

You have it configured that expiring claims are removed, not converted, but that doesn't remove previously converted claims. I don't know when you changed that option. You also need to make main config changes while the server isn't running, and I don't know if you did that.

**Comment by thexaero** [comment]
Also, get 0.20.1, which has the dupe fixed: https://modrinth.com/mod/open-parties-and-claims/versions

CurseForge is doing a manual review, so it'll take a while to appear there.

**Comment by DonorKrovi** [comment]
> According to your configs, you have protection disabled for "expired" claims and protection from explosions disabled separately, so even turning the main protection option on still wouldn't protect from explosions, whether normal TNT or minecarts. Are those the claims being exploded?
> 
> You have it configured that expiring claims are removed, not converted, but that doesn't remove previously converted claims. I don't know when you changed that option. You also need to make main config changes while the server isn't running, and I don't know if you did that.

Well, I did a lot of stupid things in the configs, I should study them in more detail, thanks to you I understood what the problem was. It also occurred to me that if after the expiration of the term the player claim are generated to a vanilla chunk, what is the point? Players who find a thrown claim won't get the good stuff right away at the beginning of the game, it's like working /regen in the worldedit mod

**Comment by DonorKrovi** [comment]
^ What do you think about such an idea for implementation? If you don't understand something, I can paraphrase it because I used a translator

**Comment by thexaero** [comment]
I'm not sure what you mean. The mod isn't regenerating chunks. It either changes player claims to "expired claims", which you can still protect, kind of like an archive, or unclaims them when they expire, which is probably what you want. They keep everything that was built in them, so players who discover the expired claim can take stuff from it.

**Comment by DonorKrovi** [comment]
> I'm not sure what you mean. The mod isn't regenerating chunks. It either changes player claims to "expired claims", which you can still protect, kind of like an archive, or unclaims them when they expire, which is probably what you want. They keep everything that was built in them, so players who discover the expired claim can take stuff from it.

I mean, is it possible to implement the removal of all buildings and loot in the region, a kind of rollback of the region that will remove all buildings from regenerating everything to the original appearance of the region?

Or is it beyond the scope of this mod?

**Comment by thexaero** [comment]
No, it's not possible. I don't think I'd want to add something like that, because if it goes wrong, it'll go very wrong.

**Comment by thexaero** [comment]
If you don't want new players to steal things from expired claims, then simply turn `playerClaimsConvertExpiredClaims` back to true. Then turn on all the necessary protection in the expired claim config.
