### ISSUE TITLE
Item frames can be interacted with by anyone, even when no exceptions are available. (OFF)

### ISSUE THREAD

**Issue by FormulaAbyss** [thexaero/open-parties-and-claims#363]
I have had two issues. Glass pane was broken by a player, and in the time it took for the glass pane to register it shouldn't be broken, same player was able to interact with the armorstand behind the glass. They were able to remove an item from the armorstand. I have not allowed any exceptions (Party, Allies, Everyone), and have not changed the exceptions for player plots in the default config.

In addition to this, items in item frames can be removed with an empty hand, an item in the hand, and by arrow.

**Comment by thexaero** [comment]
This isn't actually true. You either have actually configured your claim protection wrong (the most likely option) or it's a compatibility issue with another mod. Or you're using a very old version of the mod.

**Comment by FormulaAbyss** [comment]
Am I just not understanding how this works? I have both armorstand and itemframe interactions off, which should prevent them from interacting?
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/a6d72b6b-6810-456d-a8a5-d2fac06644ab)
Also, I think my version is relatively new, as I'm on 1.20.1:
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/5b968568-9d63-4a79-abc2-c2d119c76cf6)
I also don't think any other mod is interfering and have not seen any compatibility lists, so not sure where to start looking.
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/ea99180d-5a8a-41b1-90ae-a1c3d3260209)
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/2f2637ce-0d32-4a01-b5b1-9d3870af2539)
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/7383d194-39d8-4628-98b1-d3b9385499fa)
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/591d0f79-1bf0-4966-bcc1-41414c1ea983)
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/7d82b32d-66b9-483f-84c8-e90cddbfe8d5)
![image](https://github.com/thexaero/open-parties-and-claims/assets/101954645/bd6c5ca8-2913-494c-b576-7696a7eed06d)

**Comment by FormulaAbyss** [comment]
Also, to be clear, they can't break the itemframes or armor stands themselves, just take items off them.

**Comment by thexaero** [comment]
Can you interact with your item frames in non-ally-mode?

**Comment by FormulaAbyss** [comment]
I don't have any allied. My party is just me, no allies,

**Comment by FormulaAbyss** [comment]
Also found an issue where villagers in claims stop farming, even if block
protection is off/everything is set that it isn't protected.

**Comment by thexaero** [comment]
Do `/openpac-claims non-ally-mode` and check if you yourself can interact with your own item frames and armour stands. 
Also send me a screenshot of your sub-configs (open the dropdown menu that currently says "main").

I am starting to lean more towards it being a compatibility issue though.

**Comment by FormulaAbyss** [comment]
At this point I've given up. My cognative function can't handle this right now, so I've temporarily deleted the mod until I can think clearly enough to figure out what is going on.
