### ISSUE TITLE
Cant open Lootr Chests

### ISSUE THREAD

**Issue by Slab-God** [thexaero/open-parties-and-claims#365]
OPAC seems to block opening of Lootr Chests, even with every interact flag on. However it will work if you turn off flag "Protect Blocks From Players". Perhaps it thinks Lootr chest is a regular block. - Its a server claim

**Comment by thexaero** [comment]
You need to configure exceptions for blocks that don't already have them in the main config file. The mod is not limited to the "flags" that exist by default.
