### ISSUE TITLE
How to Protect a Claim from a Nuclear Warhead Alex Caves

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#367]
Recently, the Alex Caves mod was released and it has a nuclear warhead that can blow up a player's clsim, how can you prevent breaking blocks for it?

![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/f05c0778-4087-435d-bfaf-13e21993b75d)

**Comment by thexaero** [comment]
There is no way to protect it on a block-by-block basis. Disable the use of it completely across the server.
