### ISSUE TITLE
Alex Mobs burrowing_arrow

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#368]
/summon alexscaves:burrowing_arrow

I found the vulture with these entities and decided to add them to the ban, I added them to **blockAccessEntityGroups** but it didn't help, yes I restarted the server, probably I added them in the wrong place? I don't understand English well and would be extremely grateful for help

![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/f47d5683-58f3-414d-9be0-a32ebae93b8b)
These Entity can be released from a special bow

![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/30a083eb-c36f-45df-94ff-0dc75e8b73b3)
![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/8f2d1541-a34c-41ae-9578-e46f77f11a71)

**Comment by thexaero** [comment]
Seems like they addressed it.
