### ISSUE TITLE
Alex Mobs burrowing_arrow

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#369]
https://github.com/thexaero/open-parties-and-claims/issues/368

Unfortunately, this hasn't been fixed, but you probably have any ideas?!

**Comment by thexaero** [comment]
It seems that they assumed that they fixed your issue: https://github.com/AlexModGuy/AlexsCaves/issues/166
If not, let them know. It's not something I can fix easily from my end.
