### ISSUE TITLE
Portals on Claimed Chunks 

### ISSUE THREAD

**Issue by Klayment** [thexaero/open-parties-and-claims#373]
Im Currently Hosting a Server through a Webhosting Provider.
Im running Better MC 1.19.2 Fabric BMC 1

It Includes the Open Parties and Claims mod.

How and where exactly do i Enable Portal use for Everybody in my Claim? 

(we have build a world spawn with open nether, aether etc portals and i claimed the chunks, id like for other people to have access to these portals. 

I dont know anything about the files nor do i have any experience with scripts or plugins.

I would appreciate a "noob" answer for me.  

I have all 3 settings turned "off" regarding the portals when looking in "default player settings"

**Comment by thexaero** [comment]
If it's server claims, then disable portal protection for server claims. If you personally claimed them, then disable portal protection in your claims.

**Comment by Klayment** [comment]
I am Server Admin.

How do i disable them ?  

I just used Filezilla to get the openpartiesandclaims TOML File for default Players 
Edited all Portal lines to "false" instead of 0 

Does that do the trick?  cause with ingame settings i tried yesterday ....i turned every single portal setting off but people who didnt have access to the chunk just couldnt use the portal

**Comment by thexaero** [comment]
No, that is not correct. Use the in-game settings. If it's server claims, then disable portal protection for server claims. If you personally claimed them, then disable portal protection in your claims.

**Comment by Klayment** [comment]
I have disabled all Portals Rules in every Claim status possible, server, personal, default etc 

Dosent work 
Somebody whos not in my party cant use that Nether Portal nor the aether portal  (assuming it has the same code and is registered as nether portal in your mod)

**Comment by thexaero** [comment]
I can't help you based on information that is likely not true. Provide screenshots.

**Comment by Klayment** [comment]
I figured it out.

For some reason i needed to reclaim the Chunks ...every since its been working fine with every type of portal

**Comment by thexaero** [comment]
This means that they were not claimed with a config that allowed nether portal usage, which means you did not allow it in every config.
