### ISSUE TITLE
Corpse mod 

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#374]
![image](https://github.com/thexaero/open-parties-and-claims/assets/60231586/a3e4c0ef-0864-4bfc-aefa-a53e0a1dfb87)

You cannot interact with corpses from mods, namely with corpses in chunks of other players, what do you recommend doing?

Config: https://mclo.gs/jUVsML8

**Comment by thexaero** [comment]
Add the entity to forced entity exceptions.

**Comment by DonorKrovi** [comment]
> Добавьте сущность в принудительные исключения сущности.

love you
