### ISSUE TITLE
Brewing Station Interaction

### ISSUE THREAD

**Issue by Marcoleric** [thexaero/open-parties-and-claims#375]
We noticed no option to allow interaction with Brewing Stations. We activated every "Interact (X)" but brewing stations are still out of reach

**Comment by thexaero** [comment]
You can create your own options in the main config file the same way the default ones are.
I'll probably add a default one for this though.

**Comment by Samuel-Chapuis** [comment]
I'm sorry to ask but i really don't understand how to add new option in the openpartieclaims-server.toml can you give me a litle explain please ?
