### ISSUE TITLE
Adding Block Exceptions doesn't work?

### ISSUE THREAD

**Issue by Nohkarthus** [thexaero/open-parties-and-claims#376]
I tried adding Block Exceptions so everybody can interact with them in claims but it just doesn't work, or maybe I did it wrong? I don't think I did it wrong though.
Here's where I added it and the code:
Line 124: `forcedBlockProtectionExceptionList = ["minecraft:crafting_table", "yigd:grave", "fwaystones:waystone", "fwaystones:desert_waystone", "fwaystones:red_desert_waystone", "fwaystones:stone_brick_waystone", "fwaystones:nether_brick_waystone", "fwaystones:red_nether_brick_waystone", "fwaystones:end_stone_brick_waystone", "fwaystones:deepslate_brick_waystone", "fwaystone:blackstone_brick_waystone", "cobblemon:pc", "cobblemon:healing_machine"]`

**Comment by Nohkarthus** [comment]
And to add to it, these changes makes the server unjoinable so I had to reset the config files

**Comment by thexaero** [comment]
You definitely made a mistake in the config file format but probably not this line.
