### ISSUE TITLE
[Fabric 1.19.2] Does not work with Spectrum's decays

### ISSUE THREAD

**Issue by Gronglegrowth** [thexaero/open-parties-and-claims#377]
[Spectrum](https://modrinth.com/mod/spectrum)'s decay blocks (Ruin, particularly) still spread in claimed chunks despite the config to prevent this behavior from occurring in the mod's own config being on (option is only available on the 1.7.0 alphas).

**Comment by thexaero** [comment]
Looks like their claim compatibility does not include this mod.
