### ISSUE TITLE
FTB Teams / Parties Integration Not Working

### ISSUE THREAD

**Issue by MadSciSlack** [thexaero/open-parties-and-claims#378]
This could be something on my end, but the config is set to use "ftb_teams" as the party system; but Teams and Parties do not sync members or anything else.

It was set to "ftb_teams" by default, so it's not a value I entered.  Is there something I'm missing with this integration, or is this a bug?

**Comment by MadSciSlack** [comment]
Additional Info:
- OPAC was just added recently, so most configs are still default.  
- FTB Teams had existing teams when OPAC was installed and configured, but we nuked them and remade them through OPAC commands with no new results.  FTB Teams and OPAC Parties remain separate.
- Server is in development phase, so only has admins on it.  I've been the only one doing config, and have only set the starting chunks per player and forceloads per player. (And set permission manager to be "luck_perms".
- "luck_perms" integration seems to have worked fine.
- No other claim, party, team, or chunk control mods / plugins are installed.

**Comment by thexaero** [comment]
I don't know what you're expecting to happen. The claims respect FTB Teams the same way they do regular parties. OPAC parties are a separate thing that you don't have to use and can even disable completely.
