### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#380]
I've got a good idea about protecting players' chunks from entities like these https://github.com/thexaero/open-parties-and-claims/issues/369
The idea is to add a new feature to prevent entities from infiltrating players' pieces. For example, when a player uses an item whose essence can destroy blocks in a chunk, it will be instantly removed when they cross the line. In this way, you can protect chunks from a large number of crawls on the server.

**Comment by thexaero** [comment]
It's already a feature. You can protect from specific item use and add a barrier for specific entities.

**Comment by DonorKrovi** [comment]
> It's already a feature. You can protect from specific item use and add a barrier for specific entities.

Then why doesn't it remove entities that are forbidden, for example, by using arrows from Alex Caves, this can be bypassed.
Or is it because of the mod mechanics Alex Caves?
