### ISSUE TITLE
Missing parts for Create

### ISSUE THREAD

**Issue by Nanamiya738** [thexaero/open-parties-and-claims#381]
Forge:43.2.8, mod version:0.19.3

the page said already support for Create, but the plough can't till the dirt in my cliam

**Comment by thexaero** [comment]
I'll look into it.

**Comment by Nanamiya738** [comment]
thank you

**Comment by Nanamiya738** [comment]
new discover, the claim stop a train being assamble.
when dissamble, the blocks are break

**Comment by thexaero** [comment]
That's just protection against contraptions working. Assemble and disassemble in compatible/same claims, which means you should claim the chunks where you assemble the train too. Otherwise this is a contraption that is coming in from outside the claims.

**Comment by Faolon12** [comment]
is there a config option to change that? we have limits on our server of claims, and take contraptions out quite often,

**Comment by JpnRndr01** [comment]
the addition of a toggle for protection against contraptions would be a huge Quality Of Life fix, please add a config option for it :)
