### ISSUE TITLE
How To Use With Argonauts Guilds

### ISSUE THREAD

**Issue by TheBrambleShark** [thexaero/open-parties-and-claims#382]
Hello,

I would have made a discussion if this repo had this enabled. I can't figure out how to make this plugin work with Argonauts.

I have created a test guild with Argonauts, but regardless of whether OPAC parties are enabled or disabled, this doesn't seem to have any sort of effect on the relationship between OPAC and Argonauts.

In the server config, I have Argonauts Guilds configured as the party source:
`primaryPartySystem = "argonauts_guilds"`

When creating a claim, whether through the claim or via Xaero's Worldmap, it creates a personal claim. I can turn on server or admin claim mode, but there doesn't seem to be any integration happening between OPAC and Argonauts.

When pressing `'` to open the OPAC menu, Party is described as N/A. `/openpac-parties about` says that I'm not in a party. `/guilds` shows that I am the owner of the test guild that I created.

**What does Argonauts integration actually do?**
I would expect the Argonaut guild to be the "Party" in OPAC and I would expect to be able to make a separate claim for the party rather than just specifically the player, but the latter possibly doesn't exist.

**Comment by thexaero** [comment]
Claim protection checks Argonauts guilds the same way it does OPAC parties. The two are not supposed to become one another. If you use Argonauts, you don't have to look at anything OPAC party related at all. 
There is no such thing as a party claim. All claims are personal and players can give access (it's done by default) or make exceptions for their party members through their config. It doesn't matter what party system the party members come from.
