### ISSUE TITLE
forcedBlockProtectionExceptionList not working

### ISSUE THREAD

**Issue by ghost** [thexaero/open-parties-and-claims#391]
The interaction with the block from the SimpleShops mod is denied in the claimed areas. According to the description of the Config, the following entry should solve the problem. Unfortunately, I still get the message that I am not allowed to interact with the block.

forcedBlockProtectionExceptionList = ["minecraft:crafting_table", "anything$simpleshops:simple_shop"]

in ./world/serverconfig/openpartiesandclaims-server.toml

Either the configuration description is incorrect, or this setting is not working. Especially considering the behavior of the "minecraft:crafting_table" it seems that "$hand" is the default rather than "$anything." The owner of the claim can interact with the shop without any problems.

open-parties-and-claims: open-parties-and-claims-forge-1.20.1-0.20.1.jar 
forge-version: 47.2.6

**Comment by thexaero** [comment]
Did you figure it out?
