### ISSUE TITLE
Forceload not working for server claims.

### ISSUE THREAD

**Issue by NiliusJulius** [thexaero/open-parties-and-claims#392]
I'm playing on a server, and have created some claims in server-claim-mode.
If I mark these as forceloaded, and leave the area, they do not keep the area loaded, but if I make a player claim and forceload them, it does.

One thing that does work is:
If a chunk is forceloaded by for example the /forceload command, and in the server claim settings, forceload offline has been turned on, the forceload offline does get applied, so it seems to just be the forceload part that does not work.

This is on 1.20.2

**Comment by thexaero** [comment]
I'd be surprised if this is actually true. How are you testing whether chunks are forceloaded or not? Is regular forceloading turned on in the server claim config?

The /forceload command does not care about anything in this mod. It would forceload the chunk no matter what you configured. You shouldn't use that to test anything related to the mod.

**Comment by NiliusJulius** [comment]
We first noticed it with a bonemeal farm.
To test I go to a random chunk which I forceload as server-claim, setup a dropper which empties its contents automatically and then teleport 20 chunks away.
When I tp back to the forceloaded chunk a minute later, the dropper has not emptied.

**Comment by thexaero** [comment]
I see, that's a good way to test it. So is regular forceloading enabled in the server claim config? Please double-check.

**Comment by NiliusJulius** [comment]
Yes that is turned on
![image](https://github.com/thexaero/open-parties-and-claims/assets/1352673/014cbacc-53ba-4eaf-a82b-64f6f589f41f)

**Comment by thexaero** [comment]
Interesting. I'll look into it.

**Comment by thexaero** [comment]
Is this Forge or Fabric?

**Comment by NiliusJulius** [comment]
Fabric

**Comment by thexaero** [comment]
Thanks, I'll check it out.

**Comment by thexaero** [comment]
Seems to be working in all my tests. I don't even remember how server claim forceloading is any different from player claim forceloading besides having unlimited forceloads. I don't think it is any different, which isn't making any sense in regards to this issue. I'll make sure though.

**Comment by thexaero** [comment]
I think I know what might be wrong. It is in fact related to server forceloads being unlimited.

**Comment by thexaero** [comment]
Yep, can confirm. The limit is still enforced when forceload tickets are being added. If you toggle forceloading off and on, it'll update the tickets and ignore limits for server claims, fixing the issue.
