### ISSUE TITLE
Droper or other alternative from mods doesnt work

### ISSUE THREAD

**Issue by castilio20** [thexaero/open-parties-and-claims#393]
![2023-11-24_20 29 32](https://github.com/thexaero/open-parties-and-claims/assets/76228548/63ee9c2d-2547-432d-8b78-f02b9f2c5761)
If you claim an area and try to use a droper with a preasure plate it doesnt work 
the items doesnt triger the the presure plate but if i a player throws it work
even other mods alternative for droper doesnt work like create chute or botania (in dev) crate
mod ver 0.20.1
modloader neo 47.1.79
ok so after some searching this is a feature but it doesnt make sense to be on by default?

**Comment by thexaero** [comment]
It's pressure plate protection which you can turn off. It makes sense to have it by default.
