### ISSUE TITLE
Create contraptions break if placed in own chunk

### ISSUE THREAD

**Issue by mikaba-eu** [thexaero/open-parties-and-claims#395]
https://github.com/Creators-of-Create/Create/issues/3976

Its a issue in fabric & forge. (1.19.2)
Please take a look at it, this bug is super annoying and you can lose a lot of items.

How to reproduce:

    Claim a Chunk
    Build or place a contraption with the cart assembler in a wild (not clamed chunk)
    Take the contraption with you
    Place it in your claimed chunk with the assembler.
    Its break.

**Comment by mikaba-eu** [comment]
If I set "Protect Block from Other" to OFF. The bug disappear.

**Comment by thexaero** [comment]
This is because contraption protection works based on where the contraption was assembled from blocks. They don't have owners to go off of.
You can easily work around this by toggling protection off for a moment when you disassemble contraptions.
Might address this with #279
