### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by P14S0P** [thexaero/open-parties-and-claims#397]
![a](https://github.com/thexaero/open-parties-and-claims/assets/100706920/48c043d4-fa98-4164-86a3-2dc8bf3a2c86)
hi, the config file: openpartiesandclaims-server.toml, is not generated on my server, everything else works correctly

**Comment by thexaero** [comment]
It's supposed to be in your world folder serverconfig.

**Comment by P14S0P** [comment]
it's weird since the search tool didn't found it, tyvm for the help xaero, have a wonderful day!

**Comment by thexaero** [comment]
No problem! Have a great day too.
