### ISSUE TITLE
Unstuck command

### ISSUE THREAD

**Issue by mikaba-eu** [thexaero/open-parties-and-claims#398]
It will be awesome if we can get a unstuck command, if you are in a claim there you haven't permission, that you can port out. A config with a cooldown time would be good too. We implement now a /warp with a cooldown, but unstuck would be better.

**Comment by thexaero** [comment]
I feel like servers usually have a warp command for that anyway. I don't know if it needs to be built into this one.

**Comment by mikaba-eu** [comment]
We don't have one. I prefer to implement everything with more "game like" mechanics. My players get scrolls now to teleport into the city; that they can buy. But the "stuck in a claim" scenario happened now very often. Flan have a unstuck command btw.

**Comment by thexaero** [comment]
Can't you get a warp command just for this purpose?

**Comment by mikaba-eu** [comment]
I will do that now, but I have to implement a high cooldown for that. Better would be if the player use a unstuck function and get just teleported to the next "unclaimed" position.
Don't haste something, I don't know how big your TODO list is, its not high prio now.

**Comment by thexaero** [comment]
Teleporting to an unclaimed location isn't a full solution to getting stuck though. You can get stuck surrounded by claimed chunks. It would have to be a spawn teleport or something similar.
