### ISSUE TITLE
how to add a friend in private?

### ISSUE THREAD

**Issue by MrJorman** [thexaero/open-parties-and-claims#40]
how to add a friend in private?

**Comment by MrJorman** [comment]
I have uploaded chunks and I want to give access to them to my friend, how do I do this?

**Comment by thexaero** [comment]
You either create a party and invite them to it with chat commands, or both of you create a party for yourself and add each other as an "ally". The second variant works more similar to a friend list, so you might prefer that. Then you can disable protection against party members or allies in the player config UI.

**Comment by MrJorman** [comment]
Which team? I just created a group and invited a friend there, but he still can't do anything in private. Can you somehow create a party through the GUI interface, it's difficult to write commands..

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/180307229-221b8bfc-770c-490c-ab03-57cedce520ad.png)

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/180307257-4504adb7-e0f1-4d17-a0a3-dd3bf4898bd9.png)

**Comment by MrJorman** [comment]
I'm at his party, why can't I do anything in his region?

**Comment by MrJorman** [comment]
I'm sorry, but your algorithm for creating and inviting to the region is very very complicated, can you do it through the GUI somehow easier?

**Comment by MrJorman** [comment]
I have 1 mod that can help you with this, I'll find it in a minute..

**Comment by MrJorman** [comment]
https://www.curseforge.com/minecraft/mc-mods/craftable-deeds/screenshots mod example GUI.
![image](https://user-images.githubusercontent.com/55187962/180307561-d58332c3-98a9-4a0c-9a0a-5325b92f17bd.png)

you can also add friends to the region through the GUI.

**Comment by MrJorman** [comment]
If you implement it through the GUI, it will be great!!!

**Comment by MrJorman** [comment]
Some bug has just occurred, the player has stolen chunks and could not do anything, re-logging to the server helped.

**Comment by thexaero** [comment]
You had 0 trouble creating a party and inviting someone, so I'm not sure what you're on about. There is no tutorial and you still did it. In fact, the part that you didn't do has a UI:
`Then you can disable protection against party members or allies in the player config UI.`

**Comment by MrJorman** [comment]
I barely figured it out, terrible. Please make everything easier through the GUI.

**Comment by MrJorman** [comment]
I want to see the GUI of my private where there will be flags and players, where I can enter a player's nickname or select a player from the server and add to the private.

**Comment by thexaero** [comment]
Then use a different mod.
