### ISSUE TITLE
How can i make Industrial Foregoings block placer to work on claimed chunks

### ISSUE THREAD

**Issue by ShivanshGupta0073** [thexaero/open-parties-and-claims#401]
Ive been trying to get Industrial Foregoings block placer to work on claimed chunks but nothing works can anyone help?

**Comment by thexaero** [comment]
Take a look at the staticFakePlayers option in the main config file. Read through the comment above it. It may or may not work for you.

**Comment by ShivanshGupta0073** [comment]
> Take a look at the staticFakePlayers option in the main config file. Read through the comment above it. It may or may not work for you.

Well I did look at that but I couldn't figure out the right way to put it there like what's the syntax I've the uuids of fake players so do I put it like ["UUID","IF"] or some other way

**Comment by thexaero** [comment]
Keeping the default in there, it would look like `staticFakePlayers = ["[IntegratedTunnels]", "your UUID or name here"]`.
[IntegratedTunnels] is the name of the fake player Integrated Tunnels uses, which contains the brackets. It's not part of the syntax. You can use either the name or the UUID.

**Comment by ShivanshGupta0073** [comment]
Ah alright thanks for the quick replies.
Regards
