### ISSUE TITLE
Editing default amount of claims - Open Parties and Claims

### ISSUE THREAD

**Issue by HarvestHavenMC** [thexaero/open-parties-and-claims#402]
Hi, is there a way or a command to change the default amount of player claims from 500 to 30?
This is to apply to all server players

Also, how to add bonus claims to individual player? I.E Increase their chunk claim amount?

**Comment by thexaero** [comment]
> Hi, is there a way or a command to change the default amount of player claims from 500 to 30?
This is to apply to all server players

The main config file. Please read through the mod description on CurseForge/Modrinth.

> Also, how to add bonus claims to individual player? I.E Increase their chunk claim amount?

Using the mod's UI, you can edit player configs and bonus claims is one of the options.

**Comment by HarvestHavenMC** [comment]
> > Hi, is there a way or a command to change the default amount of player claims from 500 to 30?
> > This is to apply to all server players
> 
> The main config file. Please read through the mod description on CurseForge/Modrinth.
> 
> > Also, how to add bonus claims to individual player? I.E Increase their chunk claim amount?
> 
> Using the mod's UI, you can edit player configs and bonus claims is one of the options.

@thexaero I believe I had changed it to 30 but still doesnt seem to work, it keeps changing back to 500 when i restart the server
