### ISSUE TITLE
Inactive privates - are not deleted after a reboot or server crash

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#404]
Your privates use local system time - so if I specify to delete a region of a player who has been inactive for more than 7 days, the region will not be deleted, since after a server reboot or crash, the time starts again.

**Comment by thexaero** [comment]
Claims are expired based on server runtime, which is saved to data/server-info.nbt, so a server restart does not reset it.

**Comment by thexaero** [comment]
The default claim expiration time is not 7 days, it's 1 year.

**Comment by NeoFolia** [comment]
Then the question is this. My player has not logged in for 54 days. The configurations indicate that the region will be deleted after 14 days. region is still worth it.

**Comment by NeoFolia** [comment]
@thexaero hello bro. I am using the latest version of your wonderful mod - and I hasten to inform you that the regions are still not deleted after time.
