### ISSUE TITLE
Prevent Lava and Water Bucket use

### ISSUE THREAD

**Issue by AnyankaT** [thexaero/open-parties-and-claims#405]
I'm trying to prevent players on my server from using water and lava buckets in the spawn area, and I've added them to the exception list:
![image](https://github.com/thexaero/open-parties-and-claims/assets/127417685/46bcbb51-1f8b-44a9-bb0b-b61b1216c04b)
But it doesn't seem to make a difference. Am I missing something?
[openpartiesandclaims-server.txt](https://github.com/thexaero/open-parties-and-claims/files/13751422/openpartiesandclaims-server.txt)

Edited to add: the slingshot is still usable also (same line)

**Comment by thexaero** [comment]
Bucket use isn't allowed by default. Is the spawn area claimed? Is item use protected in those claims?

**Comment by thexaero** [comment]
By the way, I'm not sure if you want all those options in opConfigurablePlayerConfigOptions. That makes it so you have to edit configs for each player separately, rather than just editing the default player config and it applying to everyone. That option should really just contain the bonus claims/forceloads in most cases.

**Comment by AnyankaT** [comment]
I want people to be able to use many items, as it's the capital city of the world. I have edited to include/exclude most of the items I want to, but the bucket is eluding me.

And we've deliberately turned off most player claim abilities - I want to edit the configs for certain players separately. We're also using MineColonies, and this offers many protections already for players in their colonies.

**Comment by thexaero** [comment]
Did you turn off the item protection option for those claims? If item protection is turned off, then nothing you do with exceptions will have any effect. Buckets are protected by default, you don't need to do anything to prevent players from using them, so I have feeling you turned it off.

**Comment by AnyankaT** [comment]
So instead I need to turn item protection on and use exceptions for the items I want people to be able to use?

**Comment by thexaero** [comment]
Yes.
