### ISSUE TITLE
Does not work correctly with ftb ranks

### ISSUE THREAD

**Issue by Mapter322** [thexaero/open-parties-and-claims#409]
No matter how many claims I make, there is still a 500 limit on everyone. The rest of the ftb ranks features work.

Maybe I misspelled something?

`{
	member: {
		name: "member"
		power: 1
		condition: "always_active"
		ftbchunks.max_claimed: 1
		ftbchunks.max_force_loaded: 0
	}
	skuf: {
		name: "skuf"
		power: 2
		ftbranks.name_format: "<&bSkuf {name}&r>"
		ftbchunks.max_claimed: 36
		ftbchunks.max_force_loaded: 5
	}
	skufidon: {
		name: "skufidon"
		power: 3
		ftbchunks.max_claimed: 100
		ftbchunks.max_force_loaded: 10
	}
	admin: {
		name: "admin"
		power: 1000
		ftbchunks.max_claimed: 10000
		ftbchunks.max_force_loaded: 1000
	}
}
`

`[serverConfig]
	#The default language used for server-side localization for players that don't have the mod installed.
	defaultLanguage = "en_us"
	#How often to auto-save modified data, e.g. parties, claims, player configs (in minutes).
	#Range: > 1
	autosaveInterval = 10
	#How many sub-configs (sub-claims) can each player create.
	#Range: 0 ~ 1024
	playerSubConfigLimit = 64
	#The permission system to use for everything that requires permission checks (e.g. permission_api, ftb_ranks, luck_perms, prometheus). Non-built-in permission systems can be registered through the API with an addon.
	permissionSystem = "ftb_ranks"
	#The player party system to prefer and use for anything that can't support multiple systems (e.g. default, ftb_teams, argonauts, argonauts_guilds). Non-built-in party systems can be registered through the API with an addon.
	primaryPartySystem = "argonauts_guilds"
	#A list of options in the player config that individual players can reconfigure. If an option is in neither of the configurable option lists,
	#then the value in the default player config is used across the server. Check the default player config .toml file for the option names.
	playerConfigurablePlayerConfigOptions = ["claims.protectClaimedChunks", "claims.forceload.enabled", "claims.name", "claims.color", "claims.protection.fromParty", "claims.protection.fromAllyParties", "claims.protection.buttonsFromProjectiles", "claims.protection.targetsFromProjectiles", "claims.protection.platesFromPlayers", "claims.protection.platesFromMobs", "claims.protection.platesFromOther", "claims.protection.tripwireFromPlayers", "claims.protection.tripwireFromMobs", "claims.protection.tripwireFromOther", "claims.protection.cropTrample", "claims.protection.playerLightning", "claims.protection.fromFrostWalking", "claims.protection.entitiesFromPlayers", "claims.protection.entitiesFromMobs", "claims.protection.entitiesFromOther", "claims.protection.entitiesRedirect", "claims.protection.entitiesFromExplosions", "claims.protection.entitiesFromFire", "claims.protection.netherPortalsPlayers", "claims.protection.netherPortalsMobs", "claims.protection.netherPortalsOther", "claims.protection.fluidBarrier", "claims.protection.dispenserBarrier", "claims.protection.pistonBarrier", "claims.protection.itemTossPlayers", "claims.protection.itemTossMobs", "claims.protection.itemTossOther", "claims.protection.itemTossRedirect", "claims.protection.mobLoot", "claims.protection.playerDeathLoot", "claims.protection.itemPickupPlayers", "claims.protection.itemPickupMobs", "claims.protection.itemPickupRedirect", "claims.protection.xpPickup", "claims.protection.raids", "claims.protection.naturalSpawnHostile", "claims.protection.naturalSpawnFriendly", "claims.protection.spawnersHostile", "claims.protection.spawnersFriendly", "claims.protection.projectileHitHostileSpawn", "claims.protection.projectileHitFriendlySpawn", "parties.name", "parties.shareLocationWithParty", "parties.shareLocationWithMutualAllyParties", "parties.receiveLocationsFromParty", "parties.receiveLocationsFromMutualAllyParties", "claims.protection.exceptionGroups.block.interact.Controls", "claims.protection.exceptionGroups.block.interact.Doors", "claims.protection.exceptionGroups.block.interact.Chests", "claims.protection.exceptionGroups.block.interact.Barrels", "claims.protection.exceptionGroups.block.interact.Ender_Chests", "claims.protection.exceptionGroups.block.interact.Shulker_Boxes", "claims.protection.exceptionGroups.block.interact.Furnaces", "claims.protection.exceptionGroups.block.interact.Hoppers", "claims.protection.exceptionGroups.block.interact.Dispenser-like", "claims.protection.exceptionGroups.block.interact.Anvils", "claims.protection.exceptionGroups.block.interact.Beds", "claims.protection.exceptionGroups.block.interact.Beacons", "claims.protection.exceptionGroups.block.interact.Enchanting_Tables", "claims.protection.exceptionGroups.block.break.Crops", "claims.protection.exceptionGroups.entity.interact.Traders", "claims.protection.exceptionGroups.entity.handInteract.Item_Frames", "claims.protection.exceptionGroups.entity.interact.Armor_Stands", "claims.protection.exceptionGroups.entity.break.Livestock", "claims.protection.exceptionGroups.entity.blockAccess.Villagers", "claims.protection.exceptionGroups.entity.entityAccess.Zombies", "claims.protection.exceptionGroups.entity.droppedItemAccess.Villagers", "claims.protection.exceptionGroups.entity.droppedItemAccess.Piglins", "claims.protection.exceptionGroups.entity.droppedItemAccess.Foxes", "claims.protection.exceptionGroups.item.interact.Books", "claims.protection.exceptionGroups.entity.barrier.Ender_Pearls", "/*remove comment to enable*/claims.protection.exceptionGroups.entity.barrier.Players"]
	#A list of additional options in the player config that OPs can reconfigure for players.
	#This is meant for options that should be configured per player but not by the players.
	#If an option is in neither of the configurable option lists, then the value in the default player config is used across the server.
	#Check the default player config .toml file for the option names.
	opConfigurablePlayerConfigOptions = ["claims.bonusChunkClaims", "claims.bonusChunkForceloads"]`

**Comment by thexaero** [comment]
Did you configure OPAC to use the permissions nodes you defined, e.g. ftbchunks.max_claimed? Those are made for FTB Chunks by default.

**Comment by Mapter322** [comment]
> Did you configure OPAC to use the permissions nodes you defined, e.g. ftbchunks.max_claimed? Those are made for FTB Chunks by default.

I changed it, it works, thank you.
