### ISSUE TITLE
Server Crash with OPAC

### ISSUE THREAD

**Issue by MoonlitLamps** [thexaero/open-parties-and-claims#410]
The server keeps crashing when a player logs in.
[2023-12-25-2.log.gz](https://github.com/thexaero/open-parties-and-claims/files/13766177/2023-12-25-2.log.gz)
[debug-2.log.gz](https://github.com/thexaero/open-parties-and-claims/files/13766179/debug-2.log.gz)
[crash-2023-12-25_12.15.20-server.txt](https://github.com/thexaero/open-parties-and-claims/files/13766180/crash-2023-12-25_12.15.20-server.txt)

**Comment by Lemmmy** [comment]
I'm not terribly familiar with the code, but I believe [fde9fbd](https://github.com/thexaero/open-parties-and-claims/commit/fde9fbd77bdcff87c6ad31430d579a50e077d61d#diff-b4ae76ef2ecbe8e84e275576e918b1d9cf9f290631679bb1de87419c34fb7715L326-R326) removed an instanceof that was acting as a null check for `p`:

https://github.com/thexaero/open-parties-and-claims/blob/6c62d22f4c84ebadecb3c749319e25c699862428/Common/src/main/java/xaero/pac/common/server/claims/protection/ChunkProtection.java#L325-L326

https://github.com/thexaero/open-parties-and-claims/blob/6c62d22f4c84ebadecb3c749319e25c699862428/Common/src/main/java/xaero/pac/common/server/claims/protection/ChunkProtectionEntityHelper.java#L91

**Comment by thexaero** [comment]
Thanks for reporting!
@Lemmmy You're right, thanks!
