### ISSUE TITLE
Create Crash on Server

### ISSUE THREAD

**Issue by rc-nunez-gonzalez** [thexaero/open-parties-and-claims#411]
**Minecraft version:** 1.20.1
**Mod Loader:** Forge: 47.2.0
**Mods involved:** Create and Open Parties and Claims

I created an automatic tree farm based on this video in a claimed chunk in server:
https://www.youtube.com/watch?v=4OfNJkhno-s

After some minutes the server suddenly crashed, after I installed "Neruina - Ticking Entity Fixer" and the server stopped crashing, but the entire machine disappeared, the only thing I did different from the tutorial is using super glue in the entire machine excluding the bearing.

Additionally, the error repeats so I guess it can be reproduced.

PD: I noticed when I reconnected that a wandering villager got hurt by the mechanical saw when the crash happened.

**Logs:**
[crash-2023-12-25_22.04.40-server.txt](https://github.com/thexaero/open-parties-and-claims/files/13767395/crash-2023-12-25_22.04.40-server.txt)
[crashwithcreate.log](https://github.com/thexaero/open-parties-and-claims/files/13767396/crashwithcreate.log)

**Comment by thexaero** [comment]
Thanks for reporting. Same as #410 though.

**Comment by rc-nunez-gonzalez** [comment]
You're welcome, thanks for the reply and your amazing work
