### ISSUE TITLE
Add support Quark, Supplementaries, Abnormals mods please

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#414]
**quark:torch_arrow** - places torches on the region
**supplementaries:rope_arrow** - shoots from a bow and creates a rope in a foreign region
**supplementaries:slingshot** - shoots blocks in a foreign region, you can hold down the button outside the region and go into a foreign region and shoot a block
**endergetic:booflo_vest** - a breastplate that gives a jump, breaks frames, armor stands, paintings in foreign regions if you jump next to them
**savage_and_ravage:wand_of_freezing** - causes freeze damage in foreign regions where pvp is disabled

**Comment by thexaero** [comment]
Please make separate issues for separate issues.
