### ISSUE TITLE
Create's Funnels can steal drop from chest on chunk border

### ISSUE THREAD

**Issue by svesnav** [thexaero/open-parties-and-claims#416]
Forge 1.19.2
Videos

https://github.com/thexaero/open-parties-and-claims/assets/68331759/3c13b593-91d1-4398-af65-c4beea8dfc0a

https://github.com/thexaero/open-parties-and-claims/assets/68331759/3ed1accf-238f-4068-a4b6-9804dc38e09a

**Comment by thexaero** [comment]
Would not consider this a bug. Completely unnecessary to protect from this. Just don't put your chests on the claim border.

**Comment by thexaero** [comment]
In fact, I prefer this because it lets people automatically transfer items between claims if they want to.
