### ISSUE TITLE
support extended drawers

### ISSUE THREAD

**Issue by dynamiteOpanty** [thexaero/open-parties-and-claims#417]
https://modrinth.com/mod/extended-drawers

or please tell me the option to allow player to interact with drawers.

**Comment by thexaero** [comment]
You can look at how the exception group for chests is defined in the openpartiesandclaims-server.toml config and either add a new group the same way or add drawers to the Chests group.

**Comment by drag0no** [comment]
@thexaero Problem with the extended drawers, that taking items from them is "left-click" operation. And I am actually looking how to allow users to do left-click operation with protection from block breaking.

**Comment by thexaero** [comment]
But why is it a left click operation?

**Comment by drag0no** [comment]
https://www.curseforge.com/minecraft/mc-mods/storage-drawers

From their documentation:
* Right-Click: Insert full stack in hand into drawer (or partial stack if the drawer fills).
* Double-Right-Click: Insert all compatible stacks in inventory into drawer (or until drawer fills).
* Left-Click: Remove a single item from the drawer.
* Shift+Left-Click: Remove a full stack from the drawer.
* Shift+Right-Click with empty hand: Open a UI to see exact item counts and manage applied upgrades.

That's the mod implementation I guess and I believe it's connected with the fact that drawers have too many interaction options and the developer added these shortcuts.

**Comment by drag0no** [comment]
Also, I think that this enhancement should fix that: https://github.com/thexaero/open-parties-and-claims/issues/266
