### ISSUE TITLE
Mod is tagged as "Unsupported" on client side on modrinth?

### ISSUE THREAD

**Issue by Einhornyordle** [thexaero/open-parties-and-claims#419]
![image](https://github.com/thexaero/open-parties-and-claims/assets/47315090/1e577e14-8ab4-4103-a6ad-38c6c00b98ca)

If it is a server-side only mod, how can I manage my claims without installing the mod on the client as well?

**Comment by thexaero** [comment]
When I added the mod to Modrinth "unsupported" wasn't even an option. It was either yes or no. I guess we can choose "optional" now, which is what I just set it to. 
You can manage your claims with commands without the client side though.

**Comment by Einhornyordle** [comment]
Huh, that's weird. Cause I only noticed that after trying to install a modpack via the AT Launcher and I know that it worked before, just after the recent update the mod was gone since it doesn't download unsupported mods. Maybe Modrinth added the option in the last update they had.

Anyway, would you mind double-checking if your change (setting it to optional on the client side) went through? Because it still shows up as unsupported to me and therefore still won't download while Modrinth usually is rather quick with changes like that.

**Comment by thexaero** [comment]
I changed it to optional again and it doesn't work. Goes right back to unsupported. Awesome stuff.

**Comment by thexaero** [comment]
Changing it to "required" worked. Changing it to "optional" after that worked too.

**Comment by thexaero** [comment]
And it went to "unsupported" seconds later lol.

**Comment by Einhornyordle** [comment]
Huh, I did notice that the last Modrinth update caused some issues but I didn't know it went *that* bad.

**Comment by thexaero** [comment]
It also takes extremely long for it to save. Setting it to "required" seems to work for now.

**Comment by Einhornyordle** [comment]
can confirm, it now shows required for me as well. Anyway, thank you for your time!

**Comment by thexaero** [comment]
No problem. Thanks for letting me know about this. Can't set server side to optional for my map mods either.

**Comment by Einhornyordle** [comment]
Just looked it up on the Modrinth Discord, seems like they are aware of the bug and working on a fix according to one of the staff members. Setting it to required instead seems to be the only workaround you can do for now.

![image](https://github.com/thexaero/open-parties-and-claims/assets/47315090/2e333a3a-3e21-4a89-b8a1-428c13611fce)
