### ISSUE TITLE
add GUI to add to region (my chunks) and manage it.

### ISSUE THREAD

**Issue by MrJorman** [thexaero/open-parties-and-claims#42]
example: When I go into the GUI of my private, a menu opens with the addition of participants to it, which looks out for online players and the opportunity to add them to private. 

![image](https://user-images.githubusercontent.com/55187962/180321386-e3994a5c-e654-4b92-9e60-6cc1aa517463.png)

**Comment by thexaero** [comment]
Please stop harassing me.
