### ISSUE TITLE
How would I add extra claim chunks relative to the amount a player has?

### ISSUE THREAD

**Issue by zerevoidd** [thexaero/open-parties-and-claims#420]
Is there a way I can add claim chunks based on the amount someone already has instead of setting their total amount to a fixed number? For example I want a way to not have to do "/openpac player-config for player set claims.bonusChunkClaims 21" if I wanted to add 5 chunks to someone on a server where the max was 16. Trying to figure out how you'd do something like "/openpac player-config for zerevoid set claims.bonusChunkClaims +5".

**Comment by thexaero** [comment]
You can't add/subtract from config options with commands atm, but it is planned.
