### ISSUE TITLE
FTBRanks/Luckperms Permissions Issue

### ISSUE THREAD

**Issue by zerevoidd** [thexaero/open-parties-and-claims#421]
I've tried granting on both Luckperms and FTBranks the permission " meta.xaero.pac_max_claims.9999" and "xaero.pac_max_claims: 9999" for the respective mods, but neither of them seem to override the server config limit of 16 chunks. 

OPAC ver: 0.20.0
FTBranks ver: 2001.1.3
Luckperms ver: 5.4.102

Using all of these in the Prominence 2 [RPG] modpack as well.

**Comment by thexaero** [comment]
You're supposed to set an integer permission "xaero.pac_max_claims" on FTB Ranks and an integer meta value on LuckPerms. Not a regular true/false permission with a number at the end.

**Comment by zerevoidd** [comment]
Can you provide an example of what this would look like? Because "meta.xaero.pac_max_claims\.50" permission on luckperms does not override the default config either. I'm not sure what permission on FTBranks I'd set that'd work.

**Comment by ecstaticnoodle** [comment]
@zerevoidd if you never figured it out the example for claims is: meta.xaero\.pac_max_claims.256      example for forceloads is: meta.xaero\.pac_max_forceloads.16


If not this is the answer for future people.

![Image](https://github.com/user-attachments/assets/97270933-8b63-4dda-bcb4-1db73729f008)
