### ISSUE TITLE
Vidoe Tutorial on all settings, how they work and what they impact with examples.

### ISSUE THREAD

**Issue by jrpgam3r** [thexaero/open-parties-and-claims#423]
Hello there, I've found a serious lack of guides and resources on the detailed nuances of all the settings in this mod work and how they impact things. I'd really like to see a video updated every so often to show us exactly how everything works.

**Comment by thexaero** [comment]
Would be cool, but I'm not good at making videos. If somebody makes one, that'd be great. Everything is explained in text in detail in the config files.

**Comment by jrpgam3r** [comment]
Fair enough, maybe just have someone close to you help you out or comission one. You can tell them all the features and what can be done, and they can just make the Video for you. Thanks for the quick response, really appreciate all the hard work you do.
