### ISSUE TITLE
Question about Group Claiming

### ISSUE THREAD

**Issue by Bones3951** [thexaero/open-parties-and-claims#425]
Hi,

So is there a way to do overwrite other player's claims to mimic FTB Chunks party claiming? This is for a private server so I'm not concerned with individual player claims. We are all in a group with our stuff all right next to each other so the ability for claims and force-loads to act together so anyone of use can make changes would be nice but I can't figure out if there is way to do that with this at the moment.

Thanks

**Comment by thexaero** [comment]
Claim protection can very easily be disabled, as explained on the CuresForge/Modrinth page. Or you can join the same party. 
As for forceloads, you can't forceload other people's claims. I have plans to add an option for party-owned claims.

**Comment by Bones3951** [comment]
We are in the same party, I read the curseforge page. What does disabling the claim protection do? I've been in the configs trying to make it so that I can remove someone else's claim and put mine. All players would need to be able to do that, so that we could chunk load an area that was already claimed, without having to coordinate the other person to get on and chunk load it. If this is related to the server/admin mode, how do I enable that via the config? Does it require a permission system?

**Comment by thexaero** [comment]
The only way to do that is to give everyone the permission node for the admin mode (enabled with a claim command) or making everyone OP, which will also let them use the command.
The permission node is "xaero.pac_admin_mode" by default where relevant.

**Comment by mikaba-eu** [comment]
> As for forceloads, you can't forceload other people's claims. I have plans to add an option for party-owned claims.

My Players ask for that so often. Any Idea how we can temporary fix that? I don't like the idea of offline forceloads. (Maybe if we can set the offline forceloads to a limited time - so if the owner of the claim is offline for as example 4 days the offline forceload gets disabled)

**Comment by thexaero** [comment]
@dakiba I'll consider adding an option for that. #471
