### ISSUE TITLE
How do I whitelist universal shop's shops?

### ISSUE THREAD

**Issue by ReallyLane** [thexaero/open-parties-and-claims#429]
I'm using a shop mod that just uses player heads as the "shop", and everything I've tried doesn't let non-allies interact with them. Here's the link to the other mod in question. What can I do to fix this?

https://modrinth.com/mod/universal-shops

**Comment by thexaero** [comment]
I don't think they're using player heads on the server side, it's an actual block, so the block ID you should be adding is different.

**Comment by tamolny** [comment]
you just need to add the block bypass with these things
"universal_shops:trade_block"
"universal_shops:admin_trade_block"
worked for me
