### ISSUE TITLE
[FORGE] Unable to OPEN portal in Server claim

### ISSUE THREAD

**Issue by Neoteric-Dev** [thexaero/open-parties-and-claims#431]
Minecraft: 1.18.2
Forge: 1.18.2-40.2.9

Portal begins to open then shatters. Similar to if the portal frame was to be removed.

I have added both portal frame material, activator, and portal  to openpartiesandclaims-server.toml 
forcedBlockProtectionExceptionList
forcedEntityProtectionExceptionList

I have tried using $anything prefix.

Is there a different prefix that allows the portal to be created?

**Comment by thexaero** [comment]
In addition to block and item interaction protection, there's also general block placement protection that uses a Forge-only event.
In other words, you can't make an exception like this.
This gives me an idea that there should actually be a block placement exception option, separate from block and item interactions. You can already achieve this on Fabric, which doesn't have the separate placement protection, but I should make it available on Forge too.

**Comment by Neoteric-Dev** [comment]
> ... I should make it available on Forge too.

I would really appreciate that functionality, and hopefully it will even be available on older (1.18.2) versions.

**Comment by thexaero** [comment]
Closing this because there's a more specific issue now #432
