### ISSUE TITLE
Modded Items Inclusion(waystones)

### ISSUE THREAD

**Issue by ABagOSunshine** [thexaero/open-parties-and-claims#434]
When in a party and given specific permissions like "Interact (Controls)" or any other "Interact" permission. They are still unable to activate or even right click modded blocks even WITH the permission to do so. Example: party members cannot use waystones even with permissions to interact with objects/blocks.

**Comment by thexaero** [comment]
Server owner can create custom exception groups in the main config file, not just use the built-in ones.
