### ISSUE TITLE
Is there a way to find where someone's claim is from game files?

### ISSUE THREAD

**Issue by silentSquid** [thexaero/open-parties-and-claims#435]
Hi there,

I wonder if there is another way to find where someone's claim is if I can't find it on the map itself.
I've found player's ,nbt files in data\openpartiesandclaims\player-claims but the values from those files are incorrect, as in there are no claims at coordinates from the nbt files.

Thanks!

**Comment by thexaero** [comment]
These are the files. The coordinates are chunk coordinates, not block coordinates, if that's how you interpreted them.
