### ISSUE TITLE
[FORGE] Claim Create bypass

### ISSUE THREAD

**Issue by 56TR** [thexaero/open-parties-and-claims#436]
Describe the bug
Using @create Pipes/Pumps allows to grief chunks, also doing water/lava/water/lava layers allow to lava-cast whole base

Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):
Minecraft: 1.20.1
Forge: 1.20.1-47.2.17

Steps to Produce:

> Install Create
> Install OpenPAC
> Claim Land
> Build @create pipes pointed at claimed chunk with water supply and power
![openparties create_bug_1](https://github.com/thexaero/open-parties-and-claims/assets/52184399/d0cce170-da98-49e5-9fc6-8ad7fa3b1c8d)
![openparties create_bug_2](https://github.com/thexaero/open-parties-and-claims/assets/52184399/fbc0e8ef-6723-4932-b658-3621f77ea28b)
![openparties create_bug_3](https://github.com/thexaero/open-parties-and-claims/assets/52184399/aa94a764-1b68-4dc2-983f-5335822b6567)

**Comment by thexaero** [comment]
Thanks for reporting!
