### ISSUE TITLE
[1.18.2] Lecterns Not Working w/ Use (Books) Config Setting

### ISSUE THREAD

**Issue by VoidTV** [thexaero/open-parties-and-claims#439]
I've been poking around in our server's config files, and even in the mod itself, but I cannot figure out for the life of me why this is happening.

It's as simple as the title of the issue: despite minecraft:lectern being listed in the itemUseProtectionOptionalExceptionGroups Books section, we are unable to get the Use (Books) setting to allow players outside of allies or the owner of a claim to read lecterns with books on them. I have tried every setting that seemed like it could even slightly refer to the use of Lecterns, setting them to Every, but nothing short of unclaiming the chunk or turning off ALL protections seems to allow people to read a lectern.

**Comment by thexaero** [comment]
Interacting with lecterns is not an item use, it's a block use.

**Comment by VoidTV** [comment]
I see. I failed to make that connection. Thank you, thexaero.
