### ISSUE TITLE
Crash with null entity (Tree Harvester mod)

### ISSUE THREAD

**Issue by Mr-Robby** [thexaero/open-parties-and-claims#44]
Hi, a have a server crash because of Tree Harvester mod (when I sneak  and try to break tree with axe).  
Here is crashlog:
[crashlog.txt](https://github.com/thexaero/open-parties-and-claims/files/9212508/crashlog.txt)

**Comment by thexaero** [comment]
Thanks for reporting. 
I don't think there is supposed to be an "entity places block" event fired for something other than entities, but I'll add a null check anyway.

**Comment by thexaero** [comment]
And either way, adding a null check on my end will simply have to break the sapling replacement in protected chunks. So the player entity should ideally be provided to the event on the Tree Harvester end. Otherwise I can't check if the player has access to the chunks or not and will have to block it by default to be safe.

**Comment by jinkhya** [comment]
Hello, 
I believe this is the same kind of issue I'm having in 1.19 with tree harvester and open claims as soon as I try to chop in the wild.
Here's the crash-log : https://gist.github.com/jinkhya/f83f38fc2cab5fa4382eaae3999004c2 
Thanks in advance !
Jin

**Comment by thexaero** [comment]
Thanks for reporting. Yeah, the issue seems to be back.

**Comment by Mr-Robby** [comment]
> Hello, I believe this is the same kind of issue I'm having in 1.19 with tree harvester and open claims as soon as I try to chop in the wild. Here's the crash-log : https://gist.github.com/jinkhya/f83f38fc2cab5fa4382eaae3999004c2 Thanks in advance ! Jin

Hey, you can use temporal fix: set replaceSaplingOnTreeHarvest to false in config file of tree harvester

**Comment by jinkhya** [comment]
Hello ! I appreciate that but it didn't quite work. It prevents the crashing but the tree harvester mod also doesn't work. It is like you're using your axe on the same block over and over and it never breaks until you release Shift key which only breaks that one block.

**Comment by Mr-Robby** [comment]
> Hello ! I appreciate that but it didn't quite work. It prevents the crashing but the tree harvester mod also doesn't work. It is like you're using your axe on the same block over and over and it never breaks until you release Shift key which only breaks that one block.

Hmm, I see, it's worked for me fine when I've created this issue

**Comment by thexaero** [comment]
@jinkhya I can't guarantee that it'll be fixed beyond the crash. Seems like it doesn't specify which entity is breaking the blocks either, if what you're saying is true. I'll have to test it myself though.
