### ISSUE TITLE
Create Big Cannons and VS (Clockwork/Evrika) griefer work

### ISSUE THREAD

**Issue by Sepera-okeq** [thexaero/open-parties-and-claims#441]
Two modifications allow you to griefer claim, although Create mod protection should work.

- Create Big Cannons
- Valkyrien Skies  - [Clockwork - Minecraft Mod](https://modrinth.com/mod/create-clockwork) , [Eureka! Ships! for Valkyrien Skies (Forge/Fabric) - Minecraft...](https://modrinth.com/mod/eureka), [Create: Interactive - Minecraft Mod](https://modrinth.com/mod/interactive)

Version 1.20.1, Forge loader.

**Comment by thexaero** [comment]
Create Big Cannons are not a part of the base Create mod.
Please create separate issues for separate suggestions.
