### ISSUE TITLE
Sync Advancements between party members and allies

### ISSUE THREAD

**Issue by iledesma08** [thexaero/open-parties-and-claims#445]
It would be great if you could add two features: sharing a recently achieved advancement with all party members and/or sharing it with allies. I've been looking for a mod that does this with minecraft teams but I couldnt find it.
Also, another feature Im thinking of right now would be able to link a minecraft team with a party or the other way around.

Either way, this is an incredible mod and Im sorry if this isnt the right place to post an idea or feedback

**Comment by thexaero** [comment]
Thanks for the suggestion!
Sharing advancements isn't something that I would build into this mod. This mod is supposed to add parties and claims. Everything else can be handled by other mods that can interact with this one.
I don't want to touch vanilla teams either to avoid any conflicts with things that make use of those. And I don't like the idea of syncing different team systems in general.
I appreciate the feedback though!
