### ISSUE TITLE
Settings for create contraptions missing [FORGE]

### ISSUE THREAD

**Issue by Swoofterkitty** [thexaero/open-parties-and-claims#447]
Hello!

Im going through the Open Parties and Claims player config menu to allow create contraptions to break blocks, and I do not see ANY settings related to create. I did a little bit of digging, and found that there is create support, but I cant see it.

Im not sure if I am blind or what, but I would appreciate some help with this issue.

I am using Open Parties and Claims 1.20.1-0.22.0 (forge), with Xearos World map, create, and create interactive

if there is anything I can do to help, please let me know!

(IDK if these will help but im trying)

![2024-04-11_02 03 14](https://github.com/thexaero/open-parties-and-claims/assets/105351053/6f6c7ab8-5927-4f81-b548-7e5e701a1a25)
![2024-04-11_02 03 14_2](https://github.com/thexaero/open-parties-and-claims/assets/105351053/fa5e5573-c13a-4f78-811c-cc2749fc284e)
![2024-04-11_02 03 15](https://github.com/thexaero/open-parties-and-claims/assets/105351053/0f6fd6c1-3146-4152-89d5-97a431a0aa86)
![2024-04-11_02 03 16](https://github.com/thexaero/open-parties-and-claims/assets/105351053/c88c92a6-5f49-4f8b-9985-c954510f59b6)
![2024-04-11_02 03 17](https://github.com/thexaero/open-parties-and-claims/assets/105351053/3e32c74b-1cdb-4217-8284-91e30c8b7792)
![2024-04-11_02 03 17_2](https://github.com/thexaero/open-parties-and-claims/assets/105351053/8ff8f2f8-9b2d-4354-9941-d54068d3958d)
![2024-04-11_02 03 18](https://github.com/thexaero/open-parties-and-claims/assets/105351053/4beb1d5e-b787-498c-a7df-3a8f2ea4372f)

![2024-04-11_02 03 18_2](https://github.com/thexaero/open-parties-and-claims/assets/105351053/85b96d25-2880-4b3b-acd3-855a3f12c2c8)
![2024-04-11_02 03 13](https://github.com/thexaero/open-parties-and-claims/assets/105351053/b8057444-e97d-40d2-b4a3-7b714efe072c)

**Comment by thexaero** [comment]
There are no Create settings, it uses the same settings as every other mechanic.
The mod will automatically let contraptions break blocks inside claims if they're not placed on the very edge of your claimed area or outside of it.
