### ISSUE TITLE
openpac dose not work with Erics retail mod 

### ISSUE THREAD

**Issue by idkthbt** [thexaero/open-parties-and-claims#448]
i have a server with openpac and ercis retail witch adds vending tiles but even if i set the claimed chunks to allow all interractions with everything it still dosent allow me to inteerract with the vending tile unless i dissable all protection witch isnt ideal since players shouldnt be able to break the blocks

**Comment by thexaero** [comment]
You can add custom exceptions in the main config file, outside of the default ones.
