### ISSUE TITLE
Create Mod Deployer not working in claimed territories

### ISSUE THREAD

**Issue by agentsixtynine** [thexaero/open-parties-and-claims#45]
I was just using this mod with create when I realized that deployers cannot place blocks in claimed areas, is there a setting to fix this in the local config files that I couldn't find?

**Comment by thexaero** [comment]
That makes sense, since there's protection against entities placing blocks. 
I think I'll add an exception for deployers and add custom protection that works similar to drill and harvester protection.

**Comment by thexaero** [comment]
Thanks for reporting, btw!

**Comment by agentsixtynine** [comment]
I figured out it must be something like that, I look forward to seeing your fix and to my tree farm working in my claimed area :D

**Comment by thexaero** [comment]
Turns out there was no protection against deployers placing blocks on Fabric, only breaking blocks. Oops.
Deployers should be properly supported on both Forge and Fabric now though.
