### ISSUE TITLE
Create Item Dupe 

### ISSUE THREAD

**Issue by MarkapToGo** [thexaero/open-parties-and-claims#459]
When you Shift + RMB an item vault with a Wrench that is placed in 2 chunks (1 claimed & 1 unclaimed) the item vault doesn't break, but you gain the item vault and the items inside.

https://youtu.be/jRw6Zx-WMA0

**Comment by thexaero** [comment]
What version of OPAC is installed on the server?

**Comment by MarkapToGo** [comment]
I installed the latest version from Modrinth for Forge 1.20.1

**Comment by thexaero** [comment]
Please tell me the exact version number. Also, please look at it on your server, not on Modrinth.

**Comment by MarkapToGo** [comment]
open-parties-and-claims-forge-1.20.1-0.22.0.jar
