### ISSUE TITLE
[question] How would I test wether or not an mod conflicts in singleplayer?

### ISSUE THREAD

**Issue by Merith-TK** [thexaero/open-parties-and-claims#46]
I want to test to see if the Fabric version of Computercraft and Create have issues, but I am unsure how to go about testing that in singleplayer, 

could you make an guide on how to do so?

**Comment by thexaero** [comment]
ComputerCraft (I think) and Create should be supported. Create needs this extension though: https://www.curseforge.com/minecraft/mc-mods/opac-fabric-create-support
You can test protection using the non-ally-mode command, which temporarily blocks you from your own claims.
