### ISSUE TITLE
Ally status is removed at random?

### ISSUE THREAD

**Issue by totrider** [thexaero/open-parties-and-claims#460]
This is the third time this has happened now, where suddenly, the ally status between members is rewoked on its own. Is this an intended feature when players don't come online for an extended period of time? - or is it a bug? Not sure if it happens after server restart, but I have only noticed it happen after updating our server/restarting it.

No idea why it is happening, but Ihave it happen to other players once, and now myself for the second time. I know the other person has not removed the ally status, so something else is going wrong somewhere. Otherwise the mod works as intended.

I tried looking through the files and stuff, so might have missed something, but let me know if there is anything I can do to help etc.

**Comment by thexaero** [comment]
When you say "ally status", do you mean that a party is disbanded? If so, then yes, it is a feature where inactive parties get removed. You can configure the expiration time for parties in the main config file.
