### ISSUE TITLE
[Help/Question]: Add non standard blocks

### ISSUE THREAD

**Issue by Jadan1213** [thexaero/open-parties-and-claims#461]
How can I add non standard blocks/items/entities interactable in server claims? The server claim config doesn't have sections for adding item names/tags like the other configs.

**Comment by thexaero** [comment]
New exceptions can be added in the main config file, not the server claim one, just the server one.
Please read the comment above the "blockProtectionOptionalExceptionGroups" option. You can create toggleable exceptions there.

**Comment by Jadan1213** [comment]
> New exceptions can be added in the main config file, not the server claim one, just the server one. Please read the comment above the "blockProtectionOptionalExceptionGroups" option. You can create toggleable exceptions there.

Ok, so i understand that i can add things to the main server config, but are you saying i can just create an arbitrary group of blocks? I've read and re-read the comments, but i don't understand how i can get something to ONLY apply to server admin claims. 

are you saying that i make an arbitrarily named group of blocks here?
![image](https://github.com/thexaero/open-parties-and-claims/assets/68805162/6a521b59-0a0f-4bfb-8686-c2b2756c9a5d)

Then, how do i apply it to only the server claims?

**Comment by Jadan1213** [comment]
Or are you saying that adding the group adds an option/button in game to toggle for the claims?

**Comment by thexaero** [comment]
Yes, adding a group creates a whole new player config option, which creates a button. Server claims have their own "player config". 
The simplest thing you can do is add a "ServerClaim" group of blocks and enable that group in the server claim config.

That option won't be toggleable by regular players by default, which is fine in this case. But if you decide to create new groups for regular players, you would have to add the new options to the player-configurable options list, which already has some options there that you can use as an example.

**Comment by Jadan1213** [comment]
ohhh ok. that makes sense now. So far I've only been adding blocks/items/entities in the server wide sections. I hadn't realized i could add a whole toggle group of things. Thank you for explaining that for me.

**Comment by thexaero** [comment]
No problem. I want to write a detailed wiki explaining everything one day. Before the proper release of the mod most likely. I know the beta has been going on for 2 years now, but I still feel like the mod isn't quite ready... Wish I had more time to work on it. Should happen eventually though.

**Comment by Jadan1213** [comment]
> No problem. I want to write a detailed wiki explaining everything one day. Before the proper release of the mod most likely. I know the beta has been going on for 2 years now, but I still feel like the mod isn't quite ready... Wish I had more time to work on it. Should happen eventually though.

Honestly, I love the mod. It has so much granularity and configurability available. It is admittedly a bit of a learning curve lol. I love the integration with the world/mini map too, definitely icing on the cake.

**Comment by thexaero** [comment]
@Jadan1213 Thank you! That's what I'm going for. I want it to be as configurable as possible, for both the server owner and the players. That's why I think that it's missing a better claim permission system for player claims. Just party-based exceptions aren't enough in a lot of cases. It needs personal player lists too, separate from your party. It's going to be tricky to keep it user-friendly though. 
A wiki should hopefully make it less of a learning curve.
