### ISSUE TITLE
[NeoForge 1.20.4] Server crash when one player joins

### ISSUE THREAD

**Issue by waddon1** [thexaero/open-parties-and-claims#462]
The server crashes when a player who you can see in the crash report joins.

[crash-2024-05-08_04.29.43-server.txt](https://github.com/thexaero/open-parties-and-claims/files/15250097/crash-2024-05-08_04.29.43-server.txt)

**Comment by thexaero** [comment]
Please check for errors in the full log right before the crash.

**Comment by thexaero** [comment]
It's almost definitely another mod causing an issue which prevents most of the player login code from running, but I would definitely like to prevent such cases from pointing at my mod.

**Comment by waddon1** [comment]
Someone else just had the same crash seems to be caused by Applied Energistics

**Comment by waddon1** [comment]
I removed OPAC and it doesn't crash, so I am a bit confused now

**Comment by waddon1** [comment]
The latest log 
[latest.log](https://github.com/thexaero/open-parties-and-claims/files/15391236/latest.log)

**Comment by thexaero** [comment]
@waddon1 Thank you, this will be very useful!

**Comment by thexaero** [comment]
Did this begin occurring after you removed a mod/datapack that adds a dimension?
