### ISSUE TITLE
[1.20.6] [Neoforge] Crash on lauch

### ISSUE THREAD

**Issue by ffuentesm** [thexaero/open-parties-and-claims#463]
Minecraft version: 1.20.6
Modloader: NeoForge
Forge version: 20.6.61
Environment: Singleplayer
Mod version: 0.22.2
Looks like NeoForge removed the FinalizeSpawn method in 20.6.50-beta. 

![image](https://github.com/thexaero/open-parties-and-claims/assets/44974827/8b98f377-1b5d-4267-b468-a6155188cb63)

**Comment by thexaero** [comment]
Thanks for reporting! Going to fix this ASAP.
