### ISSUE TITLE
[Feature request]: Option for players and teams should not have multiple claims

### ISSUE THREAD

**Issue by Iker21dev** [thexaero/open-parties-and-claims#464]
Occasionally, on an SMP server with modifications, players use the mod to take over significant structures or areas of the world. This can detract from other players' experience by limiting their exploration and forcing them to limit themselves in building their homes.

**Proposed Solution:**

It would be beneficial to implement an option that allows players to own a single claimed area "that they can expand." This option should restrict players from owning multiple separate claimed areas (multi-claims). In this way, a balance in the gaming experience could be maintained.

It could also be a global setting for everyone, except for ops or players with special permissions from the server admin, these would be among the few who can have separate multi-claims.

![multi claim](https://github.com/thexaero/open-parties-and-claims/assets/80030992/73d7130b-f145-4ed9-ab3c-d5051c0c5d06)

**Comment by thexaero** [comment]
Thanks for the feedback.
This is already on the issue tracker #312
How should the mod prevent people from having multiple separate claimed areas? Keep in mind that players can create 2 separate areas by unclaiming chunks in-between.
I'm not saying that it's impossible, but it's a lot more complicated in practice than in theory, so I'd love to hear your ideas. Even if I successfully implement separate claim detection, it can get very annoying for players trying to unclaim chunks.

**Comment by Iker21dev** [comment]
for what it's worth, the central idea is that players and teams can only have a single claim, and this claim can be expanded, be bigger.
