### ISSUE TITLE
"(Main Hand) You are not allowed to use this item this close to somebody else's claim! Try empty hand?"

### ISSUE THREAD

**Issue by 0wenss** [thexaero/open-parties-and-claims#465]
Me and my friends all have claims very close to eachother and we keep having issues trying to use certain items in our own claims, I am guessing just based on how close we are to eachother this is causing issues. Is there a config setting or a fix to this?

**Comment by thexaero** [comment]
The best solution is to have a 1 chunk neutral zone between your claims. You can turn off item protection in neighbor chunks with your or the default player config but I don't recommend doing that, as it can create ways to grief.
