### ISSUE TITLE
Unable to change max claims on a server

### ISSUE THREAD

**Issue by ellio98** [thexaero/open-parties-and-claims#468]
I have edited the openpartiesandclaims-server.toml file to set claims to be 40 but for some reason its still 500 for everyone. 

 I tried removing the override permissions to see if that was causing it but nope everyone still has 500 claims. I added luck_perms to the server since we didn't have any of the permission mods that was mentioned but still not fixed it. 

The bonus chunk claims are set to 0 too. 

I have added the config file, just wondered if im doing something wrong here as im new to running a server.

[openpartiesandclaims-server.txt](https://github.com/thexaero/open-parties-and-claims/files/15431608/openpartiesandclaims-server.txt)

**Comment by thexaero** [comment]
Stop the server, make sure the changes are still in the config file, restart it. If it still doesn't work, then you're editing the wrong file.

**Comment by thexaero** [comment]
The config file can be in 2 places:
1. directly in the "config" folder
2. world/serverconfig

You might have one in each and only one of them is the real one.
