### ISSUE TITLE
Same translation key in config

### ISSUE THREAD

**Issue by Paper-wand** [thexaero/open-parties-and-claims#469]
When I was translating this mod, I noticed that two of the configs in [Common/src/main/java/xaero/pac/common/server/config/ServerConfig.java](https://github.com/thexaero/open-parties-and-claims/blob/818b1739a73d0d21d6693273a3e5a142b3f835be/Common/src/main/java/xaero/pac/common/server/config/ServerConfig.java#L210) used the same translation key, which caused them to display the same text when translated into other languages.
<img width="1552" alt="截屏2024-05-26 15 35 45" src="https://github.com/thexaero/open-parties-and-claims/assets/112165427/5fe2a87f-e29d-4a66-83bf-131392986766">

For example:
<img width="1136" alt="截屏2024-05-26 15 51 27" src="https://github.com/thexaero/open-parties-and-claims/assets/112165427/375c55af-346e-4fe0-833d-85e895427edd">
<img width="1072" alt="截屏2024-05-26 15 51 41" src="https://github.com/thexaero/open-parties-and-claims/assets/112165427/b79c2745-e244-476f-b639-ac76f45021ab">

**Comment by thexaero** [comment]
Thanks for letting me know! Definitely a problem I should fix.
