### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [thexaero/open-parties-and-claims#47]
Command to see a list of all players with claims and a command to TP to each claim
A command to delete all of a players claimed chunks
A config setting that when enabled prevents players from making claims until they have first joined the server 24 hours ago (configurable) 

Edit: a command to allow claiming chunks for other players when in admin mode

Edit2: shorten the initial commadn prefix from /openpac-claims to just /claims and /openpac-parties to just /parties

Edit3: a command for players to see a list of parties with more than one member (/openpac-parties list) 

Edit4: why cant party members bypass claim protection of other party members

Edit5: admin command to delete party/add members to a party

**Comment by thexaero** [comment]
Please create a separate issue for each suggestion.
Party members can bypass claim protection if the claim owner allows it in their config.

**Comment by thexaero** [comment]
Should I create the issues myself?

**Comment by ghost** [comment]
> Should I create the issues myself?

I did it

**Comment by thexaero** [comment]
Thanks!
