### ISSUE TITLE
[Suggestion] More readable config

### ISSUE THREAD

**Issue by Amythyss** [thexaero/open-parties-and-claims#470]
Hello, today I was updating this mod on my server and I noticed that comments take most of the mod config file making it quite hard to update if you already know what to do.

Is it possible to move the comments out and explain the settings in a wiki file or page ?

Thanks

**Comment by thexaero** [comment]
I don't think that's a good idea. Both a wiki and the comments should exist. You need to use a text editor that supports the .toml format. I personally just switch the language on Notepad++ to "Python" and it works pretty well.

**Comment by Amythyss** [comment]
I mean, it works on my end too with Atom.

But still I think it could look cleaner without!
