### ISSUE TITLE
[BUG] All chunks act as if claimed

### ISSUE THREAD

**Issue by Synxhronize** [thexaero/open-parties-and-claims#473]
I dont know if it's a config error or pure dumbassetry but in a server i used to play for there was a gamebreaking bug where all claims, regardless of claim status, acted as if claimed by server. I have no clue how to replicate this, if at all. But i felt i'd bring it up on the issue page in case someone else has anymore info than i do.

**Comment by thexaero** [comment]
They had wilderness protection enabled.
