### ISSUE TITLE
Assembling/disassembling mechanisms (drill) in someone else's private

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#475]
If you assemble a drill from Create in another private and place it outside the private or vice versa, it completely breaks

**Comment by thexaero** [comment]
What is your OPAC version? I've recently improved this.

**Comment by NeoFolia** [comment]
> What is your OPAC version? I've recently improved this.

no fixed bro :-( i use **open-parties-and-claims-forge-1.19.2-0.22.0.jar**

**Comment by NeoFolia** [comment]
Just before my eyes, a player assembled a drill from the Create mod outside his region, and brought it to his region to pick up resources; as soon as he placed it, it broke and the resources were gone.

**Comment by thexaero** [comment]
@kitovoi111 I believe you are not actually using 0.22.0 on the server side. All of the issues you're reporting should be fixed. Can you prove you are using that on the server side?

**Comment by NeoFolia** [comment]
> @kitovoi111 I believe you are not actually using 0.22.0 on the server side. All of the issues you're reporting should be fixed. Can you prove you are using that on the server side?

yes bro. 
![image](https://github.com/thexaero/open-parties-and-claims/assets/147491823/81d0ad6c-15d6-4de8-ace1-9f3e846f8f5b)

**Comment by NeoFolia** [comment]
and logs
[latest.log](https://github.com/user-attachments/files/15594529/latest.log)

**Comment by NeoFolia** [comment]
> @kitovoi111 I believe you are not actually using 0.22.0 on the server side. All of the issues you're reporting should be fixed. Can you prove you are using that on the server side?

Unfortunately, the problems have not been fixed and remain relevant. I’m not deceiving you, and I tested many versions, the latest version also does not correct this error.

**Comment by thexaero** [comment]
Thanks, seems like you are actually on 0.22.0 which is extremely weird.
How exactly are you placing the contraptions? From inventory or are you moving it on rails into another claim?

**Comment by NeoFolia** [comment]
> Thanks, seems like you are actually on 0.22.0 which is extremely weird. How exactly are you placing the contraptions? From inventory or are you moving it on rails into another claim?

The player collects a drill in his region, then he places it to work in a mine OUTSIDE of his region, after which he takes the trolley and puts it back in his region = it breaks and half of the drill disappears and the things in the chests also disappear.

**Comment by NeoFolia** [comment]
https://github.com/thexaero/open-parties-and-claims/issues/408 this problem

**Comment by thexaero** [comment]
@kitovoi111 Hard to believe for 0.22.0, so please provide screenshots or a video.

**Comment by NeoFolia** [comment]
> @kitovoi111 Hard to believe for 0.22.0, so please provide screenshots or a video.

I couldn't reproduce it now, I'll record a video for you as soon as it happens again.

**Comment by NeoFolia** [comment]
Problem found. When the drill is at the intersection of two regions, then entering or touching another region, it breaks, although the player is in that region in the list of participants, with the command: /openpac-parties ally add

**Comment by NeoFolia** [comment]
It is when the drill rides on rails and does not stand, that is, if you make an incline and the drill rolls, it will break, although the player (the owner of the drill) is in the region of another player.

**Comment by NeoFolia** [comment]
Sorry, I explained it wrong.

**Comment by NeoFolia** [comment]
I'll send you a video and explanation now.

**Comment by NeoFolia** [comment]
https://youtu.be/AEkJsiU4iOM - In the video, the player assembles a drill in the region of his friends. He is not the owner of these regions, he was added by friends to their regions. He collects a drill in one region of a friend, and places it in another region of a friend. After which the drill breaks. This is a bug.

/openpac-parties ally add - With this command on my server, players add each other to regions.

**Comment by thexaero** [comment]
Yep, this is exactly what should work, so it is bugged, you're right. It's supposed to take note of the position of the contraption when placed and ignore where it was assembled,. Very confusing but I'll look into it.
