### ISSUE TITLE
item create:potato_cannon places pumpkins when shot in a foreign region.

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#477]
item create:potato_cannon places pumpkins when shot in a foreign region.

**Comment by NeoFolia** [comment]
I forbade the use of a cannon in a foreign region, and also set a private boundary so that pumpkins would not fly into someone else’s private, but the player writes /spawn and holds down the shoot button and then shoots pumpkins in a foreign region or at spawn. You just need to cancel the pumpkin staging event in a foreign region.

**Comment by thexaero** [comment]
Thanks for reporting! Might be something to this.
