### ISSUE TITLE
The Wither mob breaks blocks in foreign regions.

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#478]
The Wither breaks blocks in foreign regions. To prevent it from breaking, I had to set up a gamerule, but I would like the wither to not be able to break other people’s regions, but the normal world to be able to do so.

**Comment by thexaero** [comment]
There's no way that is true, the Wither can't break protected blocks, unless you turn off the protection for it.

**Comment by NeoFolia** [comment]
Honestly. I have regions and blocks are broken in them

**Comment by thexaero** [comment]
In your claim, are blocks configured to be protected "from mobs" and "from other" and "from explosions"?

**Comment by NeoFolia** [comment]
> In your claim, are blocks configured to be protected "from mobs" and "from other" and "from explosions"?

hm.i check.

**Comment by NeoFolia** [comment]
> In your claim, are blocks configured to be protected "from mobs" and "from other" and "from explosions"?

oh, off :D sorry
