### ISSUE TITLE
[Create 0.5c Out for Fabric] - Newest Version crashes with opac-create-support

### ISSUE THREAD

**Issue by xR4YM0ND** [thexaero/open-parties-and-claims#48]
[latest.log](https://gist.github.com/SpigotDE/770ef4b4d3b9b40ab9441a24dea70a5e)

Newest Feature: Trains <3 <3 <3

**Comment by thexaero** [comment]
Thanks for letting me know.

**Comment by xR4YM0ND** [comment]
Hope you find a way protecting own trains <3 

Love your mods <3

**Comment by thexaero** [comment]
Trains should already be protected as they are on Forge. Let me know if you find a workaround though (when it comes out or on Forge).
Thanks!
