### ISSUE TITLE
Translation for text from chat doesn't work

### ISSUE THREAD

**Issue by Kisuny** [thexaero/open-parties-and-claims#482]
Translation keys don't work for chat text:

![image](https://github.com/thexaero/open-parties-and-claims/assets/56004431/9d35a45e-3997-4dc0-8eeb-339b29eac426)

```json
	"gui.xaero_claims_protection_interact_block_any" : "Вы не можете взаимодействовать с этим блоком!",
	"gui.xaero_claims_protection_interact_block": "(%1$s) Вы не можете взаимодействовать с этим блоком!",
	"gui.xaero_claims_protection_interact_block_try_empty": "(%1$s) Возможно, это сработает, если вы попробуете с пустыми руками.",
	"gui.xaero_claims_protection_block_disabled": "Взаимо-ие. с этим блоком отключено на сервере.",
	"gui.xaero_claims_protection_interact_entity_any" : "Вы не можете взаимодействовать с этой сущностью в этом чанке!",
	"gui.xaero_claims_protection_interact_entity": "(%1$s) Вы не можете взаимодействовать с этой сущностью в этом чанке!",
	"gui.xaero_claims_protection_interact_entity_try_empty": "(%1$s) Возможно, это сработает, если вы попробуете с пустыми руками.",
	"gui.xaero_claims_protection_entity_disabled": "Взаимо-ие. с этим существом отключено на сервере.",
	"gui.xaero_claims_protection_use_item_any" : "Вам не разрешено использовать этот предмет так близко к чужому участку! Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_use_item": "(%1$s) Вам не разрешено использовать этот предмет так близко к чужому участку! Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_item_disabled_any" : "Этот предмет отключен на сервере. Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_item_disabled": "(%1$s) Этот предмет отключен на сервере. Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_chorus": "Вам не разрешено использовать эфирное яблоко для перемещения в эту локацию!",
	"gui.xaero_claims_protection_interact_item_apply_any" : "Вам не разрешено применять этот предмет в этой позиции! Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_interact_item_apply": "(%1$s) Вам не разрешено применять этот предмет в этой позиции! Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_interact_item_apply_too_close": "(%1$s) Вам не разрешено применять этот предмет так близко к чужому участку! Попробуйте пустыми руками?",
	"gui.xaero_claims_protection_main_hand": "Основная рука",
	"gui.xaero_claims_protection_off_hand": "Вторая рука",
```

MC: fabric 1.19.2
mod version: b0.22.0

**Comment by thexaero** [comment]
Is the mod with this language file installed on the client side?

**Comment by Kisuny** [comment]
> Is the mod with this language file installed on the client side?

Yes

**Comment by thexaero** [comment]
I can only guess that the file is not correctly formatted then.

**Comment by Kisuny** [comment]
> I can only guess that the file is not correctly formatted then.

Translation of most of the interface works correctly, only the text in chat is not translated!

I attach the Russian translation so you can see for yourself!
[ru_ru.json](https://github.com/user-attachments/files/15929717/ru_ru.json)

**Comment by thexaero** [comment]
I've seen this done by other people, it was also Russian, so I'm 90% sure you're doing something wrong.

**Comment by thexaero** [comment]
By the way. The "default" lines you have translated are supposed to be translated from what you see in the config tooltips in the game. The "default" is just a placeholder that tells the mod to use the default config comment, which is already in English. Translating that will simply break tooltips.
Example from your file:
```
"gui.xaero_pac_player_config_tooltip_playerConfig.claims.protection.exceptionGroups.block.handInteract": "по умолчанию"
```

**Comment by Kisuny** [comment]
> By the way. The "default" lines you have translated are supposed to be translated from what you see in the config tooltips in the game. The "default" is just a placeholder that tells the mod to use the default config comment, which is already in English. Translating that will simply break tooltips.

Thanks for that info, I'll fix it.

Some of the mods in the modpack breaks translations in chat, checked only with your mod - everything works correctly.

**Comment by Kisuny** [comment]
If I understand correctly, there is no way to translate the default text?

**Comment by thexaero** [comment]
There is, you just put the actual translation of the config option comment there instead of translating the word "default".
