### ISSUE TITLE
[Fabric] Claim Griefing 

### ISSUE THREAD

**Issue by Frontenac95** [thexaero/open-parties-and-claims#483]
Hi, i've found a few issues where the claims system of this mod can be ignored.

Several of Botanias additions can bypass the protections of claims, including different lenses on mana spreaders/blasters (Weight, Bore being the easiest to grief with) and other items such as Rod of Terra Firma or Shard of Laputa.

Verions 0.22.0 for Fabric 1.20.1 (Tested in Prominence 2 modpack)

**Comment by thexaero** [comment]
This is what you should expect. I added an issue on the tracker for adding Botania support #485, but it'll be faster if somebody makes a third party addon.
