### ISSUE TITLE
Claims not loaded after going through a portal

### ISSUE THREAD

**Issue by Amythyss** [thexaero/open-parties-and-claims#484]
After you go through a portal (nether portal in my testing, haven't tested end portals) the chunk claims are not loaded for the player.

(meaning players have no indicator of which claims they are in)

**Comment by Amythyss** [comment]
![Screenshot from 2024-06-15 11-25-05](https://github.com/thexaero/open-parties-and-claims/assets/105288801/e03e06d8-17d3-4f7f-bb76-f29fa630584a)
![Screenshot from 2024-06-15 11-24-58](https://github.com/thexaero/open-parties-and-claims/assets/105288801/7cecfbdb-a2a2-49fc-989d-b6de52e120ea)
![Screenshot from 2024-06-15 11-25-10](https://github.com/thexaero/open-parties-and-claims/assets/105288801/53cec87b-b42f-49e7-bd46-ee09332bd0b1)

Note the claims disappearing as they are loaded in the map. Exiting and joining back in the server allows the claims to be read as normal.

**Comment by thexaero** [comment]
Is there anything unusual about the server I should know? This seems to be the only server that is experiencing this.
Please also tell me your Minecraft, mod, Forge/Fabric/NeoForge versions.

**Comment by thexaero** [comment]
And please send me the `openpartiesandclaims-server.toml` config file

**Comment by Amythyss** [comment]
[openpartiesandclaims-server.txt](https://github.com/user-attachments/files/15846405/openpartiesandclaims-server.txt)
File type is changed in .txt so that I could have it here

- 1.20.6
- Latest version of Fabric
- Mods:
![Screenshot from 2024-06-15 11-58-40](https://github.com/thexaero/open-parties-and-claims/assets/105288801/3588f1b3-645b-4a67-982a-13e2eade2134)

**Comment by thexaero** [comment]
Thanks! I'll look into it.

**Comment by thexaero** [comment]
When you talk about going through the Nether portal, you mean the vanilla function of the Nether portal? Going in the Nether? Are claims unloaded in the Nether as well?

**Comment by Amythyss** [comment]
Yes, and yes

**Comment by Amythyss** [comment]
@thexaero any update?

**Comment by thexaero** [comment]
I can't work on my mods that much atm because I'm sick. 
You can investigate this further for me, if you want to speed things up when I get to this. Try testing in singleplayer and/or without some of your mods.

**Comment by Amythyss** [comment]
oh no! I hope you get better soon!

**Comment by thexaero** [comment]
Oh wow, it's not even a compatibility issue with another mod. I was just able to reproduce this. Weird how nobody else is reporting the issue.

**Comment by Amythyss** [comment]
The joys of being a professional software tester: you find bugs

**Comment by thexaero** [comment]
Alright, seems like Fabric started handling packets in a scheduled main thread task with 1.20.6, affecting the order in which some packets are handled in relation to vanilla ones. This made the client mistakenly assume that the server doesn't have OPAC installed. Seems very easy to fix the issue though.
