### ISSUE TITLE
Crash when pondering create fluids

### ISSUE THREAD

**Issue by DaftHunk** [thexaero/open-parties-and-claims#489]
Hello, I have a crash on my server when we try to ponder pipes, it appens everytime :
- Use OPAC
- Use Create
- Use Create Enchantment Industry
- Ponder a pipe
- Crash occurs during the second scene

[crash-2024-06-17_19.14.07-client.txt](https://github.com/user-attachments/files/15874653/crash-2024-06-17_19.14.07-client.txt)

**Comment by thexaero** [comment]
Thanks for reporting!
