### ISSUE TITLE
opac not detected, crashing server 

### ISSUE THREAD

**Issue by cj360** [thexaero/open-parties-and-claims#49]
[Console log](https://gist.github.com/cj360/60790f1eaa0d020f31457772cc5ba7a8)

I've added both the opac-fabric-create-support, and opac itself via ftp to my server running darkrpg 3.2.3 on mc 1.18. Could there just be another mod in the modpack causing the server to crash on inital startup?

**Comment by thexaero** [comment]
It says that you don't have Create installed. The Create extension for this mod requires Create.

**Comment by thexaero** [comment]
Make sure it's 0.4.1 or older though. It's not compatible with 0.5.0 on Fabric yet.

**Comment by cj360** [comment]
Omg that's embarrassing, yet with create-mc1.18.2_v0.4.1 added console still says incompatible version/ incompatible mods. Shouldn't it work with: 
```
create-mc1.18.2_v0.4.1
opac-fabric-create-support-1.0.0
open-parties-and-claims-forge-1.18.2-0.8.0
```
?

**Comment by thexaero** [comment]
You have the Forge file for this mod instead of the Fabric one.

**Comment by thexaero** [comment]
You used to have the Fabric one on the screenshot you posted.

**Comment by cj360** [comment]
Now I see, thank you for your help of my failure to read.
