### ISSUE TITLE
Notification Disable Option

### ISSUE THREAD

**Issue by 704Prod** [thexaero/open-parties-and-claims#490]
Hey is there a way to disable the notification that you get for trying to interact with blocks?
It's not really needed, and someone who's honestly just playing around with their mouse would end up spamming their chat log pretty quickly. I feel like them attempting to break a block, and it not breaking, should be noticeable enough to get rid of the red lettering.

So, am I able to disable it?

[Example](https://i.imgur.com/4RZJpg4.png)

**Comment by thexaero** [comment]
No, and I think it's a such a bad idea to disable the messages that I'm not even going to add an option. Less problems that way. Sorry.
