### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Qdeeme** [thexaero/open-parties-and-claims#492]
Hey!
I don't know how to ask about it directly but having this thread over here might be helpful for others.
Is there any way to translate the gui? I've tried via resource pack and failed.  As i can see there's no additional language packs, is it like entirely rooted to the code ?

**Comment by thexaero** [comment]
Yes, the same way anything on Minecraft is translated.

**Comment by Qdeeme** [comment]
Yeah, but everything can be translated via resourcepacks. What i am asking about is whether there is or not a way to translate the gui?

**Comment by thexaero** [comment]
Yes, you can translate the GUI with a resource pack.

**Comment by Qdeeme** [comment]
Hm... i cannot because it does not work unless i've done something wrong... My custom MC translation works fine, another one as well but openpac's one does not. It seems to be independent like rooted to the code and it cannot be changed. That's why i'm asking

**Comment by Qdeeme** [comment]
like custom server's permissions, if i add server-side permission to allow players fishing, it prints the whole path like minecraft:fishing_rod, not just a fishing and it cannot be changed... Do you get my point?

**Comment by Qdeeme** [comment]
Solved! Thanks :D
