### ISSUE TITLE
Possible Version Update? 

### ISSUE THREAD

**Issue by BossMad08** [thexaero/open-parties-and-claims#493]
Hey not trying to push or sound mean but I really need this mod to be updated to run with Minecraft 1.21 cause all my other mods are working but some aren't, and I really need this mod to make my other mods work that I had to take out,
thank you

**Comment by thexaero** [comment]
*proceeds to push*

**Comment by BossMad08** [comment]
I'm sorry man I didn't mean to push

**Comment by BossMad08** [comment]
but i do want to say i love your work on what you do to Minecraft
