### ISSUE TITLE
Piglin Barter Farm

### ISSUE THREAD

**Issue by toffi3** [thexaero/open-parties-and-claims#494]
Hi, is there a way to make this simple Piglin Barter farm work in claimed chunks? Whenever i claim the chuck the farm is in, the dropper stops working
https://imgur.com/a/Aq6NX2g

**Comment by thexaero** [comment]
Yes. Have you figured out why it doesn't work? I assume you need to allow pressure plates.

**Comment by toffi3** [comment]
I set it to 3 in the config and the dropper still stops working whenever i claim the chunk

**Comment by toffi3** [comment]
I've set everything related to plates in the server config to three and it still stops working whenever i claim the chunk

**Comment by thexaero** [comment]
Why are you calling it "three"? You're normally supposed to edit player/claim configs using the UI screen. And if this isn't a server claim but your personal one, then you're also editing the wrong config to begin with.

**Comment by toffi3** [comment]
I was editing it in the file, not in the game. I clicked CTRL + F, typed "Plate" and changed everything related to that.

So what should i excatly do in the config that can be found in the game?

**Comment by thexaero** [comment]
Did you open your player config screen? There's a key binding for the mod's UI you can check/set in the vanilla controls menu.

**Comment by toffi3** [comment]
Oh, this one, okey. I had it not binded for some reason. Now it works perfectly, thank you!

**Comment by thexaero** [comment]
Great! No problem.
