### ISSUE TITLE
[Feature Request] Add config option excepting snow golem snow placement from claim protection

### ISSUE THREAD

**Issue by powerboat9** [thexaero/open-parties-and-claims#495]
Would allow snow golem based snow farms in claimed chunks

**Comment by thexaero** [comment]
I have a feeling you can already achieve this by creating a block access group for snow golems in the server config. Have you tried that?

**Comment by powerboat9** [comment]
I wasn't aware you could do that. It would have to be a server-side config change?

**Comment by thexaero** [comment]
Yes, there's an option for it in the main config file.
