### ISSUE TITLE
Why are these options grayed out and how do I edit them? 

### ISSUE THREAD

**Issue by HTMLDevelopment** [thexaero/open-parties-and-claims#496]
I am the owner of an SMP, sometimes the nations can declare war on eachother, but for that to happen they need to be able to change these options, how do I do so and why are they grayed out? Thanks for advance
![image](https://github.com/thexaero/open-parties-and-claims/assets/82397029/e58cf397-d3d0-4f59-89f8-2632c5e260c0)

**Comment by thexaero** [comment]
It's explained on the mod page. https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims

**Comment by HTMLDevelopment** [comment]
Should I use FTB Ranks or another perm mod to do so?

**Comment by thexaero** [comment]
No. Did you read about the greyed out options on the mod page?

**Comment by HTMLDevelopment** [comment]
I couldn't do at the time I messaged you, I'm sorry, but I understood now how it's done, so thank you.
