### ISSUE TITLE
Server Claim Function Conflicts

### ISSUE THREAD

**Issue by 704Prod** [thexaero/open-parties-and-claims#502]
So I'm lost, is there any way at all to be able to claim an area as spawn, and allow people to use the right click interact function with entities, but still not be able to break blocks? These functions seem to be listed under the same permission, but that handicaps the function as a whole

Either I'm blind, which I'm hoping, or there's no current way to allow people to enter a server claim, restrict them from breaking blocks, while also allowing them to interact with NPCs.

**Comment by thexaero** [comment]
Have you not found the player config UI and the main config file?

**Comment by 704Prod** [comment]
Here is the player config https://pastebin.com/2yJMvr3b
Here is the server claim config https://pastebin.com/jgkHLd4F
Here is the server config https://pastebin.com/PXFDaAZZ

**Comment by thexaero** [comment]
Did you find the UI screens for player/claim configs?

In the last config file you sent, the only one you should edit as a file, there are options that let you create specific exceptions and exception groups that you can toggle for each claim separately. Stop the server before replacing that file.

**Comment by johndelker** [comment]
I'm having a similar issue. I have server claimed my spawn area, and I changed the server claim settings to allow interaction with chests, doors, and pressure plates. People are able to use the pressure plates, but doors and chests are unusable.

**Comment by thexaero** [comment]
@johndelker It is in no way a similar issue. Closing this since there was no response.
