### ISSUE TITLE
[NeoForge 1.20.6] Mod crashes upon load 

### ISSUE THREAD

**Issue by Barrer898** [thexaero/open-parties-and-claims#504]
I am using Prisim Launcher and OPAC b0.23.0 on NeoForge 1.20.6, OPAC is the only mod installed and i get java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/player/EntityItemPickupEvent Error, i am attaching my full log 
[latest.log](https://github.com/user-attachments/files/16198829/latest.log)

**Comment by thexaero** [comment]
Thanks for reporting!
Kind of strange because I can see that they have removed this class but when I download the latest version of NeoForge it's still there.

**Comment by thexaero** [comment]
Fixed in 0.23.1.
