### ISSUE TITLE
[Crash] ticking entity

### ISSUE THREAD

**Issue by JellyBubb1e** [thexaero/open-parties-and-claims#506]
https://pastebin.com/ser5D6ey

**Comment by thexaero** [comment]
I think it's caused by Sinytra Connector. Possibly NeoForge not properly implementing the Forge 47.1.106 API.

**Comment by JellyBubb1e** [comment]
https://pastebin.com/EDcBXiyY
I tried only arsnouveau and its dependencies.

**Comment by Barking3086** [comment]
I'm also getting this crash:
[crash-2024-09-14_20.02.22-server.txt](https://github.com/user-attachments/files/17003533/crash-2024-09-14_20.02.22-server.txt)
 If I had to hazard a guess, I'd say it has something to do with Open Parties and Claims trying to protect a claimed block whilst another mod tries to destroy it. Doesn't seem to only occur with Sinytra, but NeoForge does seem to be a common factor.

**Comment by Einhornyordle** [comment]
Must be the projectile block protection that's bugged. My game crashed after a skeleton's arrow missed me and hit a block inside of my claim. https://paste.myftb.de/duyocihoge.properties

**Comment by thexaero** [comment]
What's bugged is that version of NeoForge. The 1.20.1 version of it was supposed to support Forge mods but doesn't do it right in this case. They don't even offer 1.20.1 downloads anymore. Not going to fix this as the OPAC file you are using is not intended for NeoForge in the first place. I'm pretty sure the whole modpack will still work if you switch to Forge but don't quote me on that and do it at your own risk.
