### ISSUE TITLE
1.19.2 Forge - Regions are removed even from active players

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#508]
Regions are removed even from active players
 Players are complaining that their regions are being removed, even though they play every day. In my configuration, I have it set that regions should be deleted after 7 days if the player (region owner) does not log into the game.

**Comment by thexaero** [comment]
OPAC version? And please post your openpartiesandclaims-server.toml config.
Don't really see how this could be possible though.

**Comment by thexaero** [comment]
Nevermind, I think I know how this could happen if your server is still restarting every 6 hours and expiration is never checked except on server start.

**Comment by NeoFolia** [comment]
Version mod: **open-parties-and-claims-forge-1.19.2-0.23.0.jar**
Config: 
[openpartiesandclaims-server.txt](https://github.com/user-attachments/files/16346014/openpartiesandclaims-server.txt)

**Comment by NeoFolia** [comment]
As I wrote, regions are indeed deleted even for active players (but not for all)

**Comment by NeoFolia** [comment]
Please add the function of prohibited commands for players in foreign regions. I have a PVP server and other players set their /sethome in other regions and kill players endlessly
