### ISSUE TITLE
[Feature Request] Single chunks for private 3x3 or 5x5 or 10x10

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#509]
Is it possible to somehow make me select a point on the map and click “claiming” and so that 3x3 or 5x5 chunks or 10x10 are automatically private from this point (middle), so that I can issue the number of chunks for private. Otherwise, players litter the map with single private chunks

**Comment by thexaero** [comment]
It's not really compatible with how claiming works in this mod, so no.
