### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by love-garfilds** [thexaero/open-parties-and-claims#510]
![image](https://github.com/user-attachments/assets/0c9377d8-93e1-4860-9c59-b22ad135b8e5)
it claims that there  is a virus detected on "open-parties-and-claims-fabric-1.20.1-0.23.2.jar"

**Comment by thexaero** [comment]
Probably a false positive. Where did you download it from?

**Comment by thexaero** [comment]
Nothing gets detected on my end and the MD5 hash matches, so it's either something on your end giving you a virus or most likely a false positive.
