### ISSUE TITLE
How could I transfer ownership of a party as an admin?

### ISSUE THREAD

**Issue by Spookysaw** [thexaero/open-parties-and-claims#512]
One of my players who is in a vastly different timezone than the person they want to transfer the party to cannot transfer their party, as it is incredibly rare for them to be online at the same time. I was wondering if I could, as an admin, transfer the party myself.

**Comment by thexaero** [comment]
Are both players in the same party? The player you're transferring the party to doesn't have to be online, just needs to be in the party.

**Comment by Spookysaw** [comment]
my mistake, in this specific instance the player was referring to the claims themselves, not the party

however there are other situations where transferring parties as an admin would be needed
recently one of the players of my server completely left and did not transfer their party to anyone, meaning everyone in the party was locked out of having anyone who could contrl it

**Comment by thexaero** [comment]
To transfer claims one must simply unclaim the chunks and let the other player claim them. If they can't ever play at the same time, then they can use a middle man who should claim the chunks after the original owner unclaims them and then unclaim them for the new owner to claim.
The party stuff is not that complicated for smaller parties. You just need to create a new party with everyone who is still active. But I agree, there should be commands for both claim and party transfer.
