### ISSUE TITLE
[Question] Is there a way to allow for players to interact with every block but unable to break them?

### ISSUE THREAD

**Issue by Polyblank01** [thexaero/open-parties-and-claims#516]
I'm making a map but I've learned that despite allowing for players to interact with every block that I can allow as an exception I couldn't find a way to allow them to use vanilla lecterns and other blocks from cobblemon. Also is there a way to allow them to use items in a claimed area? Is there a bypass list somewhere that I can allow certain blocks to be interacted with?

**Comment by thexaero** [comment]
I would not recommend allowing interaction with every block, but yes, you can add custom blocks and items in the main config file. The exception options you are able to toggle in player configs are also configurable through the main config file. You can add your own toggles.
