### ISSUE TITLE
Can't disable forceloading on server?

### ISSUE THREAD

**Issue by SageofTurtles** [thexaero/open-parties-and-claims#517]
I may be doing something wrong, but I want to change the maximum limit of forceloadable chunks per player to a different value and can't seem to find a setting for this anywhere., and there doesn't seem to be anything on the Modrinth or CurseForge pages explaining how to do this.  Could you point me in the right direction for this?

**Comment by thexaero** [comment]
It's a basic option in the main config file. Make sure to stop the server before changing the config.
