### ISSUE TITLE
[bug] projectiles disappear when I throw them into someone else's regions

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#518]
You recently fixed the potato cannon. But it broke, if you throw a trident into someone else's region or ender pearl or other shells - they just disappear. How to fix it?

**Comment by NeoFolia** [comment]
![image](https://github.com/user-attachments/assets/a8dd2051-7f1a-4063-a053-9f9b87001920)

**Comment by NeoFolia** [comment]
How can I whitelist projectiles so they can be thrown in another region?

**Comment by NeoFolia** [comment]
I can't even throw a potion of instant damage in a region where PVP is enabled

**Comment by NeoFolia** [comment]
Fixed.

**Comment by thexaero** [comment]
I'm confused why you didn't get the exceptions for vanilla projectiles added automatically after updating. Did you replace the config file after updating?

**Comment by NeoFolia** [comment]
I used my old configuration.

**Comment by NeoFolia** [comment]
Problem solved.

**Comment by thexaero** [comment]
How did you solve it?

**Comment by AlexGonz62** [comment]
How was this solved? I am having this issue.

**Comment by NeoFolia** [comment]
> How was this solved? I am having this issue.

delete old configs
