### ISSUE TITLE
I can't see my friends' regions on the map.

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#519]
I turned on the function to see my chunks that I have privated. But if I am added to a group - I do not see the regions of my friends, it is terribly inconvenient!!

**Comment by NeoFolia** [comment]
To add to a group - I use this command /openpac-parties ally add

**Comment by NeoFolia** [comment]
Please add a function so that I can see the regions of my friends (those who are in my group)

**Comment by NeoFolia** [comment]
#Allowed Values: NOT_SYNCED, OWNED_ONLY, ALL
claimsSynchronization = "OWNED_ONLY"

**Comment by NeoFolia** [comment]
I can't enable the ALL function - because I have a PVP server and it's very easy to find and kill everyone at other players' houses.

**Comment by thexaero** [comment]
Can't do this because it would be a performance nightmare to let players affect claim visibility. The only usable way to achieve this would simply create a fake sense of security/privacy when the claims would actually still be available as data on the client side.
