### ISSUE TITLE
CLAIM NOT BEING DELETED

### ISSUE THREAD

**Issue by beanlover345** [thexaero/open-parties-and-claims#523]
me and my friend are playing on a Minecraft server and we want to build on this one guys claim. This guy hasn't been online for around 3 months (90 days) which is weird since I have noticed that claims should expire after 60 days. We have confirmed that the user hasn't been active so we don't know what's up with the claims. Please help since we would like to build there. thanks.

**Comment by thexaero** [comment]
What version of OPAC is installed on the server? The expiration system until recently was broken for servers that restart too often. After it was fixed, the expiration timers were reset to avoid issues.

**Comment by beanlover345** [comment]
sorry, how do I check that? And that must be why anyways; my server would restart too often,

**Comment by thexaero** [comment]
If you update the mod on the server side, then the issue should be fixed.
