### ISSUE TITLE
Is there a way to disable the words "XXXXX's Claim" once a name is assigned to a claim?

### ISSUE THREAD

**Issue by IAmEchino** [thexaero/open-parties-and-claims#524]
Currently, a claim with a name looks like this:

![image](https://github.com/user-attachments/assets/d41da191-1cbd-4b56-bee3-4ab26a5df825)

And like this on the map:

![2024-08-04_03 27 00_edited](https://github.com/user-attachments/assets/baaa3f52-2908-486d-98d3-0d1819705519)

I would like to be able to disable the use of a player's name once a name for the claim has been supplied by the player. My server is nation-based and claims never belong to a single person. In these examples, all the name would say is "New Exavia", rather than "New Exavia - CommandoEchino's Claim".

**Comment by IAmEchino** [comment]
I see that this may be a duplicate of #216, but this was never followed up on.

**Comment by kirjorjos** [comment]
Sorry to necro this, but it's not actually fixed?  All it would take is adding a player config option check in the [ServerPlayerClaimWelcomer](https://github.com/thexaero/open-parties-and-claims/blob/1.18.2/Common/src/main/java/xaero/pac/common/server/claims/player/ServerPlayerClaimWelcomer.java) and anywhere else the custom name is used.
