### ISSUE TITLE
[Suggestion] Dynmap api implementation

### ISSUE THREAD

**Issue by Subthy** [thexaero/open-parties-and-claims#525]
Hello there,

Would it be possible for dynmap api to be implemented in the mod? With this implementation it will show the claims on dynmap like how it dose with flan mod.

Example of how it would be show in dynmap is in the added image
![image](https://github.com/user-attachments/assets/14e27df5-cd71-4222-a348-68d7d2666a96)

**Comment by IAmEchino** [comment]
Agreed, but in the meanwhile I modified the .jar file for [OpenPaC BlueMap](https://modrinth.com/mod/openpac-bluemap-remapped) to update it to 1.21:

https://drive.google.com/file/d/1JC5oWATyWeiSSVjwkn3_c4k55vk8dbMj/view?usp=sharing

It connects to the Dynmap alternative BlueMap and works pretty well IMO:

![image](https://github.com/user-attachments/assets/339f9faf-4735-4204-ad52-c7bbf9441608)

**Comment by thexaero** [comment]
This should be done by a third party addon, just like what @CommandoEchino posted for BlueMap.
