### ISSUE TITLE
What does FTB Teams integration do?

### ISSUE THREAD

**Issue by AndrewGraber** [thexaero/open-parties-and-claims#527]
My question is as stated above - what is the expected behavior when I go into the server config and set `primaryPartySystem` to `ftb_teams`? I was under the impression that this would make it so that openpac would use the FTB claims system as its backend, but changing this setting seems to have done nothing?

I have set it to ftb_teams, but my claims from FTB Teams do not appear in the World Map or minimap, and the openpac claims I make from within the world map don't seem to register on FTB Teams' end.

**Comment by thexaero** [comment]
FTB Teams does not add chunk claims, it adds a party system. This mod supports it by default, just like the built-in party system. The `primaryPartySystem` option is for cases where only 1 system can be used. I don't think it ever matters what you have it set to at the moment.
