### ISSUE TITLE
Team-based claims synchronization

### ISSUE THREAD

**Issue by NathanAdhitya** [thexaero/open-parties-and-claims#530]
Hi, is an option available for the claimsSynchronization option to be able to sync claims to the client for the entire party/team?
```toml
                #Whether to synchronize world chunk claims to the game clients. Enables client-side mods to access the claims data, e.g. to display it on a map.
		#ALL - all claims are synced. OWNED_ONLY - only the claims that the client player owns and server claims are synced. NOT_SYNCED - claims are not synced.
		#Allowed Values: NOT_SYNCED, OWNED_ONLY, ALL
		claimsSynchronization = "OWNED_ONLY"
```
For context, the mod for team management currently being used is FTB Teams, and we wish that everyone in the team can see each other's claims without being able to see others outside of the team.

**Comment by thexaero** [comment]
It's not available and not going to be because it would destroy the server performance if players were able to frequently hide/unhide their claims in any way, for example by joining/leaving teams. All such changes would have to be synced to every player affected.
