### ISSUE TITLE
Grappling hook mod

### ISSUE THREAD

**Issue by FireFox1324** [thexaero/open-parties-and-claims#531]
I was wondering if there was something I could change in the config file to allow grappling hooks from the grappling hook mod to be used in claims. I'm on 1.20.1 and when I try to use a hook in my claim it launches but then disappears before hitting a block.

**Comment by thexaero** [comment]
You need to add the projectile entity of the grappling hook to `entitiesAllowedToGrief` in the main config file, where things like eggs, arrows, tridents are already included by default.
