### ISSUE TITLE
trains are destroyed when disasembled on claims

### ISSUE THREAD

**Issue by OpalSoPL** [thexaero/open-parties-and-claims#537]
trains are destroyed when dissembled even if on claim that player has access
version: 1.20.1-0.23.0

Steps to reproduce:
- assemble train in wildness
- ride to the station that is on claim
- dissemble train

**Comment by thexaero** [comment]
It's working as intended. This is something anyone without claim access could also do, allowing them to place blocks if it wasn't protected against. Contraptions don't have owners, so protection is based on where it was assembled or placed. 

The same person should claim both stations if they want something like this to work.
