### ISSUE TITLE
Several botania items, most notably mana spreaders, fail to function when in claimed chunks.

### ISSUE THREAD

**Issue by LuveelVoom** [thexaero/open-parties-and-claims#540]
Hi,
I've been playing the Valhelsia 6 modpack (6.2.2) and encountered an issue: Botania mana spreaders (and other blocks relating to mana bursts) fail to function in claimed chunks. I eventually isolated the issue down to this mod and botania, and a developer of botania confirmed
![Screenshot 2024-08-22 12 13 18 PM](https://github.com/user-attachments/assets/86351ef6-2a5b-460e-bf1a-3a90498ab411)
that the issue is not on their end.
I would greatly appreciate a fix; while this issue does not make botania unuseable, it makes me unable to forceload the chunks that it's in and leaves my setup vulnerable to attack by other players. Thanks 😁

**Comment by thexaero** [comment]
It's not something that needs to be fixed as it is not a bug. You need to add a "block access" exception for the mana spreader's projectile entity in order to let it land on blocks. You can either make a global forced exception or create a group, all in the main config file. Similar global exceptions are already configured there for arrows, eggs, tridents, if you're looking for an example.

**Comment by LuveelVoom** [comment]
Thanks! Do you know what config file this is in and what exception I have to add to the file to make it work? I found a reddit post that claimed to have a solution but it didn't seem to work for me.

**Comment by ChickenDestroyer** [comment]
Part of the issue is that inside a claim, it wont create the mana burst entity. this is when the mana spreader is located inside the claim itself. If it is outside it blocks the interaction as the mod intends.

**Comment by thexaero** [comment]
@ChickenDestroyer I have specifically tested the mana spreader in the past and there was no issue like this. I don't even know which protection type would cause that. It was only preventing the entity from landing, which is intended behavior, unless an exception is added.

**Comment by ChickenDestroyer** [comment]
> @ChickenDestroyer I have specifically tested the mana spreader in the past and there was no issue like this. I don't even know which protection type would cause that. It was only preventing the entity from landing, which is intended behavior, unless an exception is added.

Gotcha. I can make a new issue if it helps, with video on it, if desired. 
I know that toggling claim protection in the settings allows bursts to be made, but with claim protection enabled, it wont even generate a burst from the mana spreader block itself. Unless this has something to do with owner of the entity or the block generating the entity inside a claim. 
If I recall from another post, mana burst extend off of the generic thrown property, but I may be mistaken. I know the mana blaster (player held and fired spreader) works as intended for all instances that I have seen, pointing to the fact that it links to the creator of the burst.

**Comment by thexaero** [comment]
There is no such thing as protection against entity generation, except for the mob spawn protection, which does not affect projectiles. Please create a new issue and a video would be very helpful.

**Comment by DomezTheDragon** [comment]
![image](https://github.com/user-attachments/assets/5976856c-22dc-4c99-bb01-94bc031a889d)
@LuveelVoom @ChickenDestroyer 
this fixes the issue of botania not working in claimed chunks, if only it was by default that it was allowed

**Comment by thexaero** [comment]
@DomezTheDragon That's exactly what my first reply tells them to try.

**Comment by LuveelVoom** [comment]
We are playing with a new modpack which doesn't use OPAC, this is no longer an issue

**Comment by DomezTheDragon** [comment]
@thexaero your first reply doesn't tell them exactly what entity and what location it needs to be added to, and it's rather tricky due to the configs being so dense, my screenshot just adds some more clarity to what you said, because i know plenty of people who wouldn't be able to figure out what to do with a vague reply that doesn't say exactly what or where

**Comment by thexaero** [comment]
@DomezTheDragon I did tell them the location by telling them about existing exceptions. They would find them very quickly. I'm not here to lookup entity ids for people.
