### ISSUE TITLE
[Question] How do I add to `playerConfigurablePlayerConfigOptions` for `anything$` prefixed options?

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [thexaero/open-parties-and-claims#543]
Hello, I'd like to add `"anything$Cobblemons{cobblemon:pokemon}"` to `entityProtectionOptionalExceptionGroups` like the following:

```
entityProtectionOptionalExceptionGroups = [
  "Traders{minecraft:villager, minecraft:wandering_trader}", 
  "hand$Item_Frames{minecraft:item_frame}", 
  "anything$Cobblemons{cobblemon:pokemon}"
]
```

Additionally I'd like to add to `playerConfigurablePlayerConfigOptions` but I am not sure how I can do it. 

Looking at `"hand$Item_Frames{minecraft:item_frame}"` and the corresponding `"claims.protection.exceptionGroups.entity.handInteract.Item_Frames"`, should I use `anythingInteract` identifier which result in like this?

```
playerConfigurablePlayerConfigOptions = [
  "claims.protection.exceptionGroups.entity.interact.Traders", 
  "claims.protection.exceptionGroups.entity.handInteract.Item_Frames",
  "claims.protection.exceptionGroups.entity.anythingInteract.Cobblemons"
]
```

**Comment by thexaero** [comment]
It would be "anyItemInteract". You can see the exact paths of the new player config options being added when adding new exception groups by checking the default player config file after you start the server with the new configuration. This is explained in the comment for `entityProtectionOptionalExceptionGroups`.

**Comment by KiwiFlavoredApollo** [comment]
Before reading your post, I gave a test run with "anythingInteract" and it worked. I am not sure why though. I’ll try "anyItemInteract" and report back.

**Comment by thexaero** [comment]
I think you're misunderstanding what `playerConfigurablePlayerConfigOptions` does if "anythingInteract" supposedly worked.

**Comment by KiwiFlavoredApollo** [comment]
OPAC version I am currently using is 0.22.0. I still don't understand why but I get configurable options like following:

## 1. Without prefix
![2024-08-25_19 24 22](https://github.com/user-attachments/assets/c0e55be5-fe8b-48c2-ac7f-c62aadeaad75)

```
entityProtectionOptionalExceptionGroups = [
  "Cobblemons{cobblemon:pokemon}"
]

playerConfigurablePlayerConfigOptions = [
  "claims.protection.exceptionGroups.entity.interact.Cobblemons"
]
```

## 2. `anything` prefix and `anyItemInteract`
![2024-08-25_19 32 49](https://github.com/user-attachments/assets/cc8faacd-1e49-4910-b4e4-136f91dd6dec)

```
entityProtectionOptionalExceptionGroups = [
  "anything$Cobblemons{cobblemon:pokemon}"
]

playerConfigurablePlayerConfigOptions = [
  "claims.protection.exceptionGroups.entity.anyItemInteract.Cobblemons"
]
```

## 3. `anything` prefix and `anythingInteract`
![2024-08-25_19 37 19](https://github.com/user-attachments/assets/d883741b-855b-4fec-a104-8f4db2a717fc)


```
entityProtectionOptionalExceptionGroups = [
  "anything$Cobblemons{cobblemon:pokemon}"
]

playerConfigurablePlayerConfigOptions = [
  "claims.protection.exceptionGroups.entity.anythingInteract.Cobblemons"
]
```

EDIT: Maybe configuration option appears like above when using `anythingInteract` but the entity itself isn't put into exception.

**Comment by thexaero** [comment]
`playerConfigurablePlayerConfigOptions` does not affect the server claims config. This means I was right that you're misunderstanding what it does.

**Comment by KiwiFlavoredApollo** [comment]
Now I understand what you mean. Sorry if I bothered you. Thank you for the help!

**Comment by thexaero** [comment]
No problem!
