### ISSUE TITLE
java.lang.UnsupportedOperationException: Late invocations of Mob#setSpawnCancelled are not permitted.

### ISSUE THREAD

**Issue by JeeNearAll** [thexaero/open-parties-and-claims#545]
...Happened during playing near server claim with spawn-denying flags turned on
[crash-2024-08-28_14.07.09-server.txt](https://github.com/user-attachments/files/16782506/crash-2024-08-28_14.07.09-server.txt)

**Comment by thexaero** [comment]
The crash report you included is not related to what you have put in the title. Do you have another one?

**Comment by JeeNearAll** [comment]
> The crash report you included is not related to what you have put in the title. Do you have another one?

I'm sorry. After updating the mod to the newest version everything started to work fine. The issue is irrelevant now, I guess
