### ISSUE TITLE
[Question] Block break/place

### ISSUE THREAD

**Issue by chubalalalala** [thexaero/open-parties-and-claims#550]
I currently have al my configs set as I want with "Claimed Chunk Protection: ON" &  "Protect Blocks From Players: Every" but I want to remove block protection for breaking/placing so I set it to "Protect Blocks From Players: Off" but these includes all blocks like chest etc.

I want to prevent access to inventory blocks like chest/barrels/shulkers but still keep the ability to break block/place blocks but I can't seem to figure out how or if that's even doable.

**Comment by thexaero** [comment]
I think what you need is a separate mod that handles chest/container locks. It is technically possible to get that with this too, but you'd have to create an exception group filled with every block except chest/barrels/shulkers, which would be difficult.
