### ISSUE TITLE
Assign Parties to Server Claim Sub-Configs

### ISSUE THREAD

**Issue by russinet** [thexaero/open-parties-and-claims#552]
I have a factions server where I define all the claimed areas for all of the factions. Is it possible to assign a party to each server claim sub-config so that only that party can build there? Maybe through editing configs or anything, but I need this functionality. Having players define their own claims is not an option for gameplay purposes.

**Comment by thexaero** [comment]
Sorry, it's not possible. Claim each area by a different player you can trust.

**Comment by russinet** [comment]
One last thing, is it at least possible to claim land for another person? I tried different commands for hours but I couldn't wrap my head around it. I tried to do it through the config menu (where I can claim as others) but it doesn't seem to be doing anything, just making me claim as myself even with server claim and admin modes.
