### ISSUE TITLE
Interact with item frames/chests and shulker boxes not working

### ISSUE THREAD

**Issue by TojiMC** [thexaero/open-parties-and-claims#554]
I'm trying to prevent my ally members (and everyone else) from stealing/messing up my storage system but even though I protected it from them, they can still interact. Why? Also what's the configurable player option name for breaking/placing blocks

**Comment by thexaero** [comment]
How are you protecting it from them?

**Comment by TojiMC** [comment]
I just realized I had protect from allies off. Sorry for wasting your time. Can I still ask what the configurable player option name is for placing and breaking blocks?

**Comment by thexaero** [comment]
There is no option that is exactly that. There's "Blocks From Players" which includes breaking and interacting with blocks. Block placement is item use + block interaction, which is additionally protected by the item use option.

**Comment by TojiMC** [comment]
Okay thanks
