### ISSUE TITLE
Changing the amount of chunk allowed per player

### ISSUE THREAD

**Issue by Aoimina** [thexaero/open-parties-and-claims#555]
Hi i would like to know how can i change the amount of chunks allowed perf player currently its defaulted to 500, i checked the config files there is no config for it i checked the commands there is no commands for it

im on forge 1.20.1

**Comment by thexaero** [comment]
There is a config option and it's one of the most obvious ones. Read the answer to "How do I configure the mod on my server?" on one of the official mod pages on CurseForge/Modrinth.
