### ISSUE TITLE
Can't change some functionality in the config

### ISSUE THREAD

**Issue by cutekitticat** [thexaero/open-parties-and-claims#556]
I need to change a parameter for some reason but it is locked, I don't know why, is that a bug or do I need to change something?

![image](https://github.com/user-attachments/assets/3c0f711b-6ad2-47c6-a309-0b55425b7ef9)

**Comment by thexaero** [comment]
There's an answer to this in the FAQ on Curse/Modrinth.

**Comment by cutekitticat** [comment]
It's not helping me ! People need to right click but it's impossible, "Protect Item Use" is off in every config and it is not working.
I add "claims.forceload.enabled" in the config file option "playerConfigurablePlayerConfigOptions" but it still greyed

**Comment by thexaero** [comment]
Read the whole FAQ. You're probably not stopping the server before replacing the config file.

**Comment by thexaero** [comment]
Also, "claims.forceload.enabled" is there by default. It is not the "Protect Item Use" option if that's what you thought.

**Comment by cutekitticat** [comment]
So how I can deactivate "Protect Item Use" ? I can't find it
I add "claims.protection.itemUse" but when I restart my server it is gone 
![image](https://github.com/user-attachments/assets/f4bb857c-e2fe-4d8d-a937-0248120a4780)
