### ISSUE TITLE
Question more of an issue - add blocks to exception list without a server restart

### ISSUE THREAD

**Issue by jinkhya** [thexaero/open-parties-and-claims#558]
Hello,
Is there a way to add specific blocks to be interacted with in claims to exception list without restarting the server? 
Thanks in advance,
Jin

**Comment by johndelker** [comment]
I would really like this as well. If there isn't an existing solution, I think it should be added. If we were able to simply hit a keybind or run a command to make the block we're looking at interactable by anyone right away, that would be incredible. Would save me so many server restarts.

**Comment by thexaero** [comment]
You can do this already. Add a block tag to the exception list, instead of a concrete block, and then you can add blocks to the tag using datapacks without restarting the server.
