### ISSUE TITLE
Lost a Coral Spear / Trident when thrown onto another players claimed area.

### ISSUE THREAD

**Issue by AlexGonz62** [thexaero/open-parties-and-claims#560]
Hello playing on a server and my friend threw a coral spear into my claimed area he lost it/ never returned it to him although it had built-in loyalty. Is there a way to prevent this, or is there a configuration to allow these projectiles to be thrown into claimed areas?

**Comment by AlexGonz62** [comment]
Error in chat says "This projectile of yours is not allowed to land on blocks in this chunk!"

**Comment by thexaero** [comment]
The server owner needs to add the projectile entity of the coral spear to the block access exceptions the way regular tridents and arrows are by default.
