### ISSUE TITLE
Synchronize name & color from other teams mods

### ISSUE THREAD

**Issue by hexagonelle** [thexaero/open-parties-and-claims#562]
Hi, this is just a suggestion, but:

Would it be possible to add an option to synchronize the name and color of claims from other mods? For example: suppose I have OPaC's party system disabled, and the default party system set to `ftb_teams`. If I make a new claim, then the rules of that claim will apply to my FTB team. That's great!

However, the new claim will in general have a different name from the FTB team name, unless I manually make them the same. It also works the same for color: the color of the FTB team is, in general, different from the color of the claims on Xaero's World Map/Xaero's Minimap.

It's not a big deal, just a little annoying to have to set the color and name twice if you want it consistent.

**Comment by thexaero** [comment]
Claims don't use team colors and they are not team-owned. This is not any different when using FTB Teams.

**Comment by hexagonelle** [comment]
Sorry, I think I was unclear. Perhaps these images will communicate the idea better.

First, I set up a team using FTB Teams. The Display Name is set to "Cool Skeletons" and the Color is set to #0000AA (blue). See the first image.

In the second image, I have made a claim using FTB Chunks. It shows on the FTB Chunks map in a blue color, and with the name "Cool Skeletons".

In the third image, I have made a claim using OPaC. It shows on Xaero's map in an orange color, and with the name "hexagonelle's claim".

If I want to, I can manually edit "My Player Config" in-game, so that the OPaC color matches the FTB team color, and FTB team name. The result is shown in the fourth image.

The OPaC claim will recognize players in the FTB Team "Cool Skeletons", and apply the OPaC claim rules accordingly. I like this part of the integration. But, it would be nice if I didn't have to manually change "My Player Config" so that the OPaC color and name matches the FTB team color and name. Since OPaC is already using FTB Teams data to determine who is my party member, maybe there could be an option that it also uses FTB Teams data to name and color the OPaC claims that I (or any team member) make.

If this is not possible or desired, that's fine, I just thought I would check. I can always change the settings manually. But automatic is nice.

![image](https://github.com/user-attachments/assets/905f5e20-4738-4a85-975f-68f237c9a87e)

![image](https://github.com/user-attachments/assets/6f07a43c-eb15-4313-b2f1-bcc7931ff4b3)

![image](https://github.com/user-attachments/assets/e62a5a01-e25e-4026-ab30-108b61ffe490)

![image](https://github.com/user-attachments/assets/ba2706af-e94a-46ac-83d4-49eb7d783067)

**Comment by thexaero** [comment]
Chunk claims in OPAC are not owned by teams, they are owned by individual players. FTB Chunks has team-owned claims. It's not about "synchronizing name and color of claims from other mods". The 2 mods just don't work the same. Whether you use the built-in OPAC party system or FTB Teams, it works the same.

**Comment by hexagonelle** [comment]
Right, I understand that the mods work differently, I get that OPAC claims are owned by individual players and FTB Chunks are owned by FTB Teams. I was just wondering if OPAC could automatically sync the name and color of the FTB Team you are on to the OPAC claim name and color. Since FTB Teams only allow you to be on one team at a time (afaik), even if the OPAC claims are individually owned, made, and controlled, the OPAC claims made by individuals in the same FTB team could all have the same name and color. This can be achieved manually, I was curious if it could be done automatically.

**Comment by thexaero** [comment]
If I were to add this, enabled by default, it would create further confusion as to whether claims are team-owned or not. If it is not enabled by default, then it won't be that different from just typing in the name, which shouldn't change too often for a party. You'll likely only have to do it once. 
I am planning to add party-owned claims as an option in the future though.

**Comment by hexagonelle** [comment]
I was imagining the case where each member of an FTB team would have to change the name/color of their claims to match the team they are on, and if there's any team-switching that becomes cumbersome. But, all of that is resolved with party-owned claims in the future.

Thank you for taking the time to explain, I really appreciate it.

**Comment by thexaero** [comment]
I guess that is possible. Although I can't imagine someone switching teams so often for any reason that would require renaming your claims. It seems like a permanent thing. If someone is just temporarily joining a different team for some reason, then it most likely doesn't matter what their claims are called for that short period of time. It could happen but I can't really think of a situation like that.

**Comment by thexaero** [comment]
Thanks for the feedback!
