### ISSUE TITLE
Need help !

### ISSUE THREAD

**Issue by cutekitticat** [thexaero/open-parties-and-claims#563]
How can I unclaim all claims in a server?

**Comment by thexaero** [comment]
Your claims or the entire server?

**Comment by cutekitticat** [comment]
the entire server

**Comment by thexaero** [comment]
Go in the world folder on the server, data, openpartiesandclaims and delete the folder "player-claims".

**Comment by cutekitticat** [comment]
It's not working, i delete it but the claims still here

**Comment by thexaero** [comment]
Stop the server, delete the player-claims folder again, start the server. If that doesn't work, then you're deleting the player-claims folder for the wrong world save.

**Comment by cutekitticat** [comment]
Can I claim a chunks who only prevent mobs spawn ? 
Because a claims prevent me from doing certain things I want to authorize but I can’t change them.
