### ISSUE TITLE
Is there a way to add other interactive blocks for the ''Interact (Controls)'' ?

### ISSUE THREAD

**Issue by Senkodore** [thexaero/open-parties-and-claims#565]
Since I play on a modded mod pack. There is a chair in my claims that I want other people to sit on it too.

But when interacting to the chair, it prompts this message:
![image](https://github.com/user-attachments/assets/aa4d61f7-56d8-478a-a02a-481f895e2cef)

This option that I saw makes me think that there could a way to add a block ? If it is possible... how?
![image](https://github.com/user-attachments/assets/7a06269a-5a78-4f15-862b-766d3eaf4117)

@thexaero

**Comment by thexaero** [comment]
In the main config file openpartiesandclaims-server.toml, you can add blocks to exception groups or create new ones altogether. The group "Controls" is in the config file by default.
