### ISSUE TITLE
[Question] Is there a way to remove all claims of a player?

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [thexaero/open-parties-and-claims#567]
Hello, one player in my server made claims in a way that can be considered griefing. 

Removing them one by one can an option but is quite painful. I wonder if there is a way to remove those claims easier way.

**Comment by thexaero** [comment]
Why one by one? Do you know you can select an area by dragging the right click on the world map?
The only way to delete all claims of a player in 1 action is to remove their claim file in the world data. That requires stopping the server though. It's probably easier to remove them normally.

**Comment by KiwiFlavoredApollo** [comment]
yes I am aware that I can drag multiple chunks and bulk claim/unclaim them. However in my case, the player (griefer) claimed his/her chunk around other players' claims all around the overworld.

> The only way to delete all claims of a player in 1 action is to remove their claim file in the world data.

This can be my solution! Thank you for the advice!
