### ISSUE TITLE
server claim's

### ISSUE THREAD

**Issue by yoblex** [thexaero/open-parties-and-claims#570]
Hello, I created an admin claim, but I didn’t find how I can add other players to the server claims? 

I want a certain group of players from different parties to build at spawn

**Comment by thexaero** [comment]
If you're using a permission mod, there's a permission node which is "xaero.pac_server_claims" by default that lets a player claim/unclaim as the server and access server claims in server claim mode:
`/openpac-claims server-claim-mode`
