### ISSUE TITLE
[Neoforge] Request for 1.20.1

### ISSUE THREAD

**Issue by GStefanowich** [thexaero/open-parties-and-claims#571]
There are a lot of mods that are still on `1.20.1` (including the one raising this crash in particular), but NeoForge for OPAC only goes back as far as `1.20.2`, is there any chance of getting a `1.20.1` release?

I've been using the Forge version of OPAC `b0.22.2` but have been running into some of the issues fixed in `b0.23.x` versions, including active-players parties becoming expired and removed.

Upgrading from `b0.22.2` to `b0.23.0` starts raising a crash between OPAC and Botania, particularly when trying to fire Botanias Mana Spreaders, as soon as a Mana Spreader runs an `onProjectileImpact` event is raised, and in OPAC the class `net/minecraftforge/event/entity/ProjectileImpactEvent$ImpactResult` isn't found

Crash report [crash-2024-10-17_23.24.40-server.txt](https://github.com/user-attachments/files/17427459/crash-2024-10-17_23.24.40-server.txt)

Much appreciated

**Comment by thexaero** [comment]
It's a problem with NeoForge which is supposed to support Forge mods on 1.20.1 but doesn't do it right in this case.
