### ISSUE TITLE
[1.21.x][Neoforge] Crash under the new neoforge 21.1.72

### ISSUE THREAD

**Issue by ffuentesm** [thexaero/open-parties-and-claims#572]
Crash: https://pastebin.com/DC2qArxT
open-parties-and-claims-neoforge-1.21-0.23.2

When using neoforge 21.1.76 it works, just that the new version causes the crash.

**Comment by thexaero** [comment]
Someone reported the exact same crash on 21.1.62. Are you sure it's not a compatibility issue?

**Comment by thexaero** [comment]
Why did you close the issue?

**Comment by ffuentesm** [comment]
Tried to launch the game again, and it worked in the newer version.
