### ISSUE TITLE
Right click anything with a backpack in hand

### ISSUE THREAD

**Issue by daggontale** [thexaero/open-parties-and-claims#576]
Right now some of the players on my server are complaining about not being able to open non-keybound backpacks in someone elses claims. I am not really seeing an issue with them being able to do that so I would like to do it. 

Unfortunately I am not seeing a way to allow players to right click on blocks with specific items in their hands. Basically the same as `hand#backpacks{sophisticated_backpacks:*backpack}` as a rule but pretty much the exact opposite? like `sophisticated_backpacks:*backpack#backpacks{minecraft:*}`. Is this possible?

**Comment by thexaero** [comment]
What you're asking for would turn backpacks into an item that can be used to circumvent all block protection everywhere, which is not something you actually want.
I'm 90% certain that if you simply add an **_item interaction_** exception for backpacks, they'll work. You don't need to allow block interaction.

**Comment by daggontale** [comment]
actually, that's exactly what I am wanting. How would I do that?

**Comment by thexaero** [comment]
In that case add `Everything{*}` to `blockProtectionOptionalExceptionGroups`, start the server, enable the exception in the default player config and server claim config and deal with the consequences of that. This will enable right-click interaction with all blocks when holding unprotected items. Everyone will be able to open all doors and chests anywhere and do anything you can do with a right click. This would be exactly the same, if exactly what you're asking existed, they would just be required to hold a backpack specifically.
If the backpacks are in `itemUseProtectionExceptionList`, you'll be able to interact with any block while holding one too. I doubt you need the block protection circumvention part at all but you seem to be very confident.

**Comment by joeystombaugh** [comment]
Sorry lol, I meant I wanted exactly what you said, adding an item interaction exception for backpacks. I couldn't find anything in the config for it but maybe I'm just blind. I really do appreciate the help! I'm using World Map, Minimap, and Parties and Claims on my server and they have been absolutely incredible to use so far!

**Comment by daggontale** [comment]
Sorry lol, I meant I wanted exactly what you said, adding an item interaction exception for backpacks. I couldn't find anything in the config for it but maybe I'm just blind. I really do appreciate the help! I'm using World Map, Minimap, and Parties and Claims on my server and they have been absolutely incredible to use so far!

**Comment by thexaero** [comment]
Ah, gotcha. It's `itemUseProtectionExceptionList` for global exceptions and there's an option for groups too `itemUseProtectionOptionalExceptionGroups`.
Glad you like the mods!
