### ISSUE TITLE
Please make regions display when the value is OWNED_ONLY - so that I can also see the chunks to which the group added me!

### ISSUE THREAD

**Issue by NeoFolia** [thexaero/open-parties-and-claims#582]
Please make regions display when the value is OWNED_ONLY - so that I can also see the chunks to which the group added me!

A friend added me to a group, but I can't see his chunks, it's terribly inconvenient! Please make it so that I can see the chunks of the group I'm in.

Forge 1.19.2

**Comment by thexaero** [comment]
It's not possible without ruining server performance or making OWNED_ONLY insecure.
