### ISSUE TITLE
Can I make it where players can claim certain server sub claims but not the main server claim?

### ISSUE THREAD

**Issue by NotDocs** [thexaero/open-parties-and-claims#584]
I really want this to work so I can make it to where there are certain named regions on the map that also say "entering x y z", but allow players to settle there and claim chunks in those regions. Is this possible? I've been looking in all the configs but I cant find any for that. It is also mainly for the world map, as people can more easily see how much of a named region is claimed by people. Or can I somehow do this task through Xaero's world map instead? Thank you!

**Comment by thexaero** [comment]
No, sorry. I added an issue on the tracker though. #585

**Comment by NotDocs** [comment]
Thanks Xaero :)
