### ISSUE TITLE
Default resource pack for entering claim messages?

### ISSUE THREAD

**Issue by astridos2go** [thexaero/open-parties-and-claims#59]
Hi, I have this mod installed on a Vanilla-style server. (Vanilla clients can join, but has tons of server-side mods to better gameplay without requiring mod downloads). 

While I personally run a modded Vanilla client, including this mod, as well as Xaero's Minimap and Worldmap, many of my players do not, as they run Vanilla. When they enter a claim, they get the translation string message. (i.e. `gui.xaero_pac_title_entered_claim`)

I was wondering if there was any way for you to include those translations by default in the mod? That would prevent my players from being confused by what is going on. Obviously, I can just add the `en_us.json` file to my server resource pack, and resolve the issue myself, but I figured I would reach out and see if including it by default would be possible!

Thank you!

**Comment by thexaero** [comment]
I am aware that the mod is pretty much unusable without the client side atm. There's already an issue for it #5. I think I should be able to do something here.

**Comment by astridos2go** [comment]
Ah sorry, I didn't see that when I was commenting. Thank you!
