### ISSUE TITLE
Allow players to trade with eachother

### ISSUE THREAD

**Issue by Neoteric-Dev** [thexaero/open-parties-and-claims#590]
Would this option
forcedEntityProtectionExceptionList = ["minecraft:minecart","minecraft:player"]

Allow the players to click on each other in a claim, to be used in conjunction with
https://www.curseforge.com/minecraft/mc-mods/player-trade-secure-trading-between-players
or
https://www.curseforge.com/minecraft/mc-mods/hand-over-your-items

**Comment by thexaero** [comment]
I don't think so. Player protection works differently from other entities. I think there should be separate options for attacking and interacting with players though. I'll look into it.
