### ISSUE TITLE
[1.18.2] Permission error?

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#62]
Players without OP cannot create a private, they are told Insufficient permission
![image](https://user-images.githubusercontent.com/86433158/185187250-f414ef05-a6f8-4b51-babc-d0733114eeff.png)

How to allow /openpac-claims claim to use ?

**Comment by thexaero** [comment]
Nothing to do with me. The command doesn't require being an OP. You are probably using a mod that adds it's own requirements to commands.
