### ISSUE TITLE
[MineColonies] Questions

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#64]
I'm very curious if this mod can work correctly with this mod if you disable the Minecolonies regions? Will the inhabitants of the colony be able to use blocks or break them? I doubt it, but it would be sooo cool to implement support!

**Comment by thexaero** [comment]
I doubt it's compatible. Probably doesn't let entities do anything on Forge and allows them to do too much on Fabric. But it'd be nice if you could test it for me.
