### ISSUE TITLE
Question: How do I set up so I can protect the spawn but let players press buttons or use Waystones?

### ISSUE THREAD

**Issue by Lion4K** [thexaero/open-parties-and-claims#69]
"allow some block interactions" doesn't let use the waystones.

**Comment by thexaero** [comment]
I would add the waystone block to the `blockProtectionExceptionList` with the `force$` prefix so that they are usable in any claim.
I think that would be `"force$waystones:waystone"`.
Let me know how it goes.

**Comment by Lion4K** [comment]
where can I find this list?

**Comment by thexaero** [comment]
In the server config file. You can only edit it while the server is offline though.

**Comment by Lion4K** [comment]
Found it! thanks!

Is it possible to limit the maximum amout of chunks one can have?

**Comment by thexaero** [comment]
Yes, it's configured in the same file.
