### ISSUE TITLE
Player config options to allow the configured "some block interactions" exclusively for the party/allies

### ISSUE THREAD

**Issue by thexaero** [thexaero/open-parties-and-claims#7]
The current player config setting for this affects all players, which isn't ideal.

**Comment by GoatHobo** [comment]
Bump, not sure how these kinda forums work so sorry if im messing this up but.

Unable to use waystones in claimed chunks, means if you TP to someone you can not leave their area if their waystone is claimed.

**Comment by thexaero** [comment]
@noTuniQue9 Not what this issue is about. You need to add the waystone block(s) to the allowed block interactions list in the server config file (while the server isn't running).
