### ISSUE TITLE
[QUESTION] How can I claim a zone for the party? Is it possible?

### ISSUE THREAD

**Issue by darkkillertw** [thexaero/open-parties-and-claims#70]
I have a server with friends, and we made groups. We did parties for the groups, but we dont know to claim for a party (and all the users of the party can open a chest or do something else).

If is not possible, i think is a good suggestion.

Thank you

**Comment by thexaero** [comment]
Each player has their own claims and player config. Every player can give access to their claims to their party through the player config UI.
If you want to make it automatic across the server, you can remove the option from the player-configurable options list in the server config file and set the option to true in the default player config.
