### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#74]
Sorry again, I can't figure out how to add a player to chunks so that he can set block, break blocks.

**Comment by XionioXMaster** [comment]
I also noticed that zombies cannot kill residents in private, which is why vanilla mechanics break, how to fix this?

**Comment by thexaero** [comment]
Are you aware that this mod has a UI? Genuinely not sure if you are.

For players, you need to either be in the same party or ally parties and disable protection from parties/allies in your player config.
