### ISSUE TITLE
Create Potato Cannon Grief [1.18.2] (entity fire damage protection)

### ISSUE THREAD

**Issue by XionioXMaster** [thexaero/open-parties-and-claims#75]
![image](https://user-images.githubusercontent.com/86433158/188942926-f1c349e3-b34c-411f-a845-2bc7e8a2aa7b.png)
![image](https://user-images.githubusercontent.com/86433158/188943274-a29e8519-b0d8-4ebd-ac7a-87c1a14cd044.png)

If another player shoots a cannon using for example a blaze cake, he will be able to deal damage and kill any mob

**Comment by XionioXMaster** [comment]
As far as I understand, there is no damage from the cannon itself, this is fire damage, so you can even set fire to entities through the dispenser from a distance

**Comment by thexaero** [comment]
What are you shooting from the dispenser to set them on fire? I don't think it worked during any of my tests.

**Comment by thexaero** [comment]
Or maybe I'm remember it wrong, I'll have to check.
