### ISSUE TITLE
[1.18.2 Forge bug Create mod] The spawner from the Create mod cannot be transported to privates, they break down.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#76]
The spawner from the Create mod cannot be transported to regions, they break down.

**Comment by GitJhopa** [comment]
I transferred it with the help of a trolley collector, as it is done in the video.

https://youtu.be/NfJr2m1cHkY

**Comment by GitJhopa** [comment]
When I moved it from Wilderness to my region, it disappeared in my private when I decided to place it as a block.

**Comment by thexaero** [comment]
How is that a bug? Your claim is protected.

**Comment by GitJhopa** [comment]
This is a bug! The spawner is not transferred to my region! It just disappears (breaks)

**Comment by thexaero** [comment]
That's what is supposed to happen. Contraptions coming from outside the claim can't be placed inside it, for very obvious reasons.

**Comment by GitJhopa** [comment]
so the region is me, not someone else's.

**Comment by thexaero** [comment]
It doesn't know whose contraption it is.

**Comment by GitJhopa** [comment]
This is inconvenient :( I would like to make it so that it remembers the owner who puts the block. Since the players complain that they cannot bring a spawner or drill to their region.

**Comment by GitJhopa** [comment]
The drill seems to work in the region - everything is fine. But here's the real problem, it breaks the mechanics of the Create mod. I can't bring a spawner from the Wilderness region to my region when I bring it and activate it - it just breaks and disappears.

**Comment by GitJhopa** [comment]
Although the players were able to bring some kind of spawner like that. But it seems just lucky. The rest of the spawners just disappear.

**Comment by thexaero** [comment]
It's not up to my mod whether Create remembers contraption owners. It simply doesn't. 
I doubt anyone was able to place a spawner from outside the claim. It should only work inside the same claim. 
You can try claiming the chunk where you find the spawner and then taking the contraption to your other claimed chunks. I don't know if it'll work though.

**Comment by thexaero** [comment]
Or you can probably unclaim the chunk you want to place it in, place the spawner and then reclaim the chunk.

**Comment by GitJhopa** [comment]
The players won't do that. To tell this to all the players is hemorrhoids. Can you add a spawner exception in your mod?

**Comment by thexaero** [comment]
It's not a good idea to add a spawner exception, even if it's possible (probably not). People will be able to grief using them.

**Comment by GitJhopa** [comment]
The spawner is placed from constructions. Can it check the owner or participants of the region who unlock this construction so that the spawner is installed in the region?

**Comment by thexaero** [comment]
It can't. All it knows is where the spawner contraption was assembled from blocks.

**Comment by GitJhopa** [comment]
> It can't. All it knows is where the spawner contraption was assembled from blocks.

sec,  i give you my fixes create where owners are taken into account, you can take the code from there.

**Comment by GitJhopa** [comment]
https://drive.google.com/file/d/1TjBXvZmAmFhjxII4e-sHcDNQp19He6iP/view?usp=sharing

**Comment by GitJhopa** [comment]
https://drive.google.com/file/d/1NKthTni1zXgkHrbL2FcbG6nblRJzJZMa/view?usp=sharing

**Comment by GitJhopa** [comment]
https://drive.google.com/file/d/1-yJsg8PVMPgUXHrMrmpsunsHXmmcsv_n/view?usp=sharing

**Comment by GitJhopa** [comment]
In some of these fixes, there is a code that does so that the owner of the mechanism is remembered!

**Comment by GitJhopa** [comment]
You can take it to yourself and you will have a mod to remember the owner. And everything will work!
