### ISSUE TITLE
[1.18.2 Forge] Bug open doors and Quark mod Tweak (double door opening)

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#77]
![image](https://user-images.githubusercontent.com/86250668/189204629-47aefecb-2d64-42b5-9e56-c65c87f7aabe.png)

**Comment by thexaero** [comment]
It's just a visual glitch on the client side. I guess I can fix this in the future but it's not critical.

**Comment by GitJhopa** [comment]
Bug open doors Quark mod Tweak (double door opening) (one door opening and this no visual bug)

**Comment by thexaero** [comment]
Why did you include that screenshot then? It doesn't show one of the doors being open.

**Comment by thexaero** [comment]
And why is the screenshot from 1.16.5?

**Comment by GitJhopa** [comment]
> And why is the screenshot from 1.16.5?

1.18.2 , it's my custom name game

**Comment by GitJhopa** [comment]
By the way, thank you for noticing an error in the names, it will need to be changed)

**Comment by thexaero** [comment]
Alright, gotcha. Still, the screenshot doesn't show a non-visual issue.

**Comment by GitJhopa** [comment]
> Alright, gotcha. Still, the screenshot doesn't show a non-visual issue.

yes. But it exists!

**Comment by thexaero** [comment]
Alright, I see it now. The issue definitely needs to be fixed on Quark's end: https://github.com/VazkiiMods/Quark/issues/3873
Doing it on my end would be unreasonably bulky and even require an extension on Fabric, when you can just disable this feature for your server, until they fix it, as it's not that important.

**Comment by GitJhopa** [comment]
> Alright, I see it now. The issue definitely needs to be fixed on Quark's end: [VazkiiMods/Quark#3873](https://github.com/VazkiiMods/Quark/issues/3873) Doing it on my end would be unreasonably bulky and even require an extension on Fabric, when you can just disable this feature for your server, until they fix it, as it's not that important.

my friend fixed this. sec i give you fix, take the code from there, maybe it will help

**Comment by GitJhopa** [comment]
client: https://drive.google.com/file/d/1FMWbKweAzTfLyI0z0lGixU7853_47UuD/view?usp=sharing 
server: https://drive.google.com/file/d/1ObvTlyqxD5JZk2QM3qQ5rd1v-QWIPL3V/view?usp=sharing

It's fixed there. True, the fix was for the Flan mod (private regions)

**Comment by GitJhopa** [comment]
But he was even able to fix a visual bug on opening doors.

**Comment by thexaero** [comment]
Cool, doesn't matter.

**Comment by thexaero** [comment]
Would really appreciate it if you stopped sending me "fixes" to copy. I have absolutely no need for that.

**Comment by GitJhopa** [comment]
okay

**Comment by thexaero** [comment]
This mod is open source. If you want to add your own bulky fixes, do it yourself and run a modified version on your server.
