### ISSUE TITLE
[1.18.2 Forge] Supplementaries - The slingshot puts blocks in the regions.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#79]
The slingshot puts blocks in the other regions players.

Mod: Supplementaries.
Item: supplementaries:slihgshot

**Comment by thexaero** [comment]
Thanks for reporting!
I'll check it out.

**Comment by thexaero** [comment]
Make sure to add "supplementaries:slingshot" to "additionalBannedItemsList" when the fix update comes out.
