### ISSUE TITLE
[Question] Please tell me!

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#80]
The problem is that I want to allow players in my region to poke buttons, levers, open doors. But they cannot do this if they have an object in their hands, but only with an empty hand. How to fix it?

I also found a bug, if I have the Artifacts mod and the CuriosAPI mod, then the player can't even wear an artifact in someone else's private, how can I fix it?

**Comment by thexaero** [comment]
Empty hand requirement is not a bug and you can't fix it.
To allow players to use some items, add them to the item exception in the server config file while the server isn't running.
