### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#81]
How do I make it so that players in the regions can open blocks from a white sheet (not with an empty hand)?

**Comment by GitJhopa** [comment]
It is very inconvenient that the opening of blocks is allowed only with an empty hand. I want to make it so that everyone can open it.

**Comment by thexaero** [comment]
If I allow interacting with blocks not with an empty hand, then people will be able to use items at the blocks. This is especially problematic when you play with other mods. I can fix each individual item use in vanilla but a billion mod compatibility issues will arise.
I don't understand why you expect chunk protection to have no inconveniences.
