### ISSUE TITLE
[question] how do I enable the use of an Item inside a server claim (or any claim for that effect)?

### ISSUE THREAD

**Issue by Lion4K** [thexaero/open-parties-and-claims#90]
Like I wanna open the Transmutation Tablet "projecte:transmutation_tablet" or the Alchemical Bag "projecte:white_alchemical_bag" and it's not possible

**Comment by thexaero** [comment]
In the server config file while the server is turned off.

**Comment by Lion4K** [comment]
I tried there on the blocks line but didn't worked.

**Comment by thexaero** [comment]
You should use the item exceptions option.

**Comment by Lion4K** [comment]
this:
itemUseProtectionExceptionList = []

**Comment by thexaero** [comment]
Yes, that's the option

**Comment by thexaero** [comment]
Every single option there has a comment above it that explains the option.
