### ISSUE TITLE
No ability to use commands for Parties

### ISSUE THREAD

**Issue by Darkvulpine** [thexaero/open-parties-and-claims#94]
I use a modpack,  Create Flavored, I added Open Parties and Claims because issues with FTB parties.  But while I can claim chunks, I cannot make parties.  Many options are greyed out, and trying to type in commands says there is no command, and errors.  I can open the main menu with keybind, but again many options are greyed out.

Forge 40.1.70
minecraft 1.18.12
OP&C: 0.13.0

![2022-09-18_22 09 18](https://user-images.githubusercontent.com/69316348/190939681-516d7ab8-eec0-4ae0-9768-8e161ef3bb47.png)
![2022-09-18_22 13 07](https://user-images.githubusercontent.com/69316348/190939752-0be25acc-c439-4841-9262-be7aa9a9e223.png)

**Comment by thexaero** [comment]
Do claim chat commands work, not from the world map?

**Comment by thexaero** [comment]
I think the buttons are supposed to be greyed out, unless Asheru is you. The about party button only works when you're in a party.

**Comment by thexaero** [comment]
The most likely explanation is that all of the chat commands from this mod don't work because you have a mod installed that adds additional requirements to commands, and you have not given your players the ability to use them.

**Comment by Darkvulpine** [comment]
> Do claim chat commands work, not from the world map?

I cannot use any commands from the mod.   However I can still claim chunks via the world map one at a time by R-clicking and selecting claim chunk.  However I cannot find anywhere on how to invite players to a party.  I have been abled to name what I assume is my party, nothing more.   And Asheru is my friend, not me.

> The most likely explanation is that all of the chat commands from this mod don't work because you have a mod installed that adds additional requirements to commands, and you have not given your players the ability to use them.

If there is, I do not know which mod, nor did I set it.  I also added OP&C to Create Flavored, so unless whatever mod adds that feature has it by default or limits any command that isn't specified, I do not see why it would.

**Comment by Darkvulpine** [comment]
> The most likely explanation is that all of the chat commands from this mod don't work because you have a mod installed that adds additional requirements to commands, and you have not given your players the ability to use them.

But after messing around for a bit, which in hindsight, now that I know what possibly is the problem, should have just done that first before messaging back.

  I found it was was a mod called Server Utilities that was the problem.  I disabled it, and now I am able to access the menu.

Thank you!

**Comment by thexaero** [comment]
Alright, that makes sense. You can probably enable the commands in the Server Utilities mod though.
